### ISSUE TITLE
3.9 Critical issue with GPS altitude recorded

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/OsmAnd#10864]
- Altitude is not displayed
- Ascent / descent are not calculated correctly
![image](https://user-images.githubusercontent.com/1042025/107849356-0e5b1080-6dfb-11eb-9c4c-32c48c0f29ef.png)

**Comment by Zefling** [comment]
Same problem for me.
![Screenshot_20210214_001837](https://user-images.githubusercontent.com/3032555/107864226-362d9100-6e5a-11eb-9768-c8af0d0779ff.png)

**Comment by vshcherb** [comment]
Problem is not with graph but problem is with recorded location.
- We definitely need to round to xxx.x m (to avoid zigzags)
- we need to fix the data somehow

**Comment by vshcherb** [comment]
Looks like track was recorded with 3.9.5 that has location only once per 5 seconds and that might be a problem

**Comment by vshcherb** [comment]
Reference to documentation - https://docs.osmand.net/en/main@latest/osmand/troubleshooting/track-recording-issues#osmand-39---google-play-services-altitude-issues

**Comment by sonora** [comment]
When I go through my old OsmAnd recordings where we tried to record ele with two decimal digit precision, it appears that the digits stored after the decimal point seem bogus: the values are xxx.yy, where xxx seems the correct value in meters, but .yy seems *the same* two digits zhroughout each recordings,, e.g. always ".86".

Have not imvestigated yet, but it seems OsmAnd had behaved like this for several years and across different devices, can anyone confirm?

**Comment by scaidermern** [comment]
> When I go through my old OsmAnd recordings where we tried to record ele with two decimal digit precision, it appears that the digits stored after the decimal point seem bogus: the values are xxx.yy, where xxx seems the correct value in meters, but .yy seems _the same_ two digits zhroughout each recordings,, e.g. always ".86".
> 
> Have not imvestigated yet, but it seems OsmAnd had behaved like this for several years and across different devices, can anyone confirm?

Nope, can't confirm. In my old recordings the digits after the dot look valid:

```
      <trkpt lat="50.8627204" lon="6.5735569">
        <ele>97.821</ele>
        <time>2020-10-12T14:40:07Z</time>
        <hdop>4</hdop>
        <extensions>
          <osmand:speed>34.789</osmand:speed>
        </extensions>
      </trkpt>
      <trkpt lat="50.8628783" lon="6.5739844">
        <ele>97.225</ele>
        <time>2020-10-12T14:40:08Z</time>
        <hdop>4</hdop>
        <extensions>
          <osmand:speed>34.792</osmand:speed>
        </extensions>
      </trkpt>
      <trkpt lat="50.8630379" lon="6.5744103">
        <ele>96.703</ele>
        <time>2020-10-12T14:40:09Z</time>
        <hdop>4</hdop>
        <extensions>
          <osmand:speed>34.799</osmand:speed>
        </extensions>
      </trkpt>
      <trkpt lat="50.863198" lon="6.5748356">
        <ele>96.224</ele>
        <time>2020-10-12T14:40:10Z</time>
        <hdop>4</hdop>
        <extensions>
          <osmand:speed>34.79</osmand:speed>
        </extensions>
      </trkpt>
      <trkpt lat="50.8633595" lon="6.5752603">
        <ele>95.666</ele>
        <time>2020-10-12T14:40:11Z</time>
        <hdop>4</hdop>
        <extensions>
          <osmand:speed>34.822</osmand:speed>
        </extensions>
      </trkpt>
```

**Comment by sonora** [comment]
Thanks! What OsmAnd version had recorded this?

**Comment by scaidermern** [comment]
Version 3.8.3 according to the GPX file.

**Comment by sonora** [comment]
Ok, thanks!

I now went through many tracks recorded with OsmAnd in recent years on a range of devices, and find all sorts of behavior regarding decimal place digits: Some always report ".0". Many report a seemingly random ".xy", where this value varies between tracks, but remains the same throughout each recodring. I found one group of tracks featuring always ".23". or ".36", never anything else.

I would conclude that with the range of devices I had recorded this the capture of decimal places was mostly bogus. But it seems largely chipset/device dependent.

**Comment by scaidermern** [comment]
Yes, seems to be device/chipset specific. I can confirm bogus digits (always the same .xy) with a Samsung Galaxy S4 and OsmAnd 3.8.3.

**Comment by vshcherb** [comment]
For GPlay version fix was provided in 3.9.8-3.9.9 version it fixes some devices but not all of them.

**Comment by kreuzschnabel** [comment]
Confirmed. Osmand+ 3.9.6 records GPS altitude data in very rough steps, changing every few minutes only, even in hilly terrain. This does not only affect the recorded track but also the altitude display in the panel.

On my phone (Oneplus 5T, latest LineageOS), this behaviour only appears with the internal GPS. When using an external GPS receiver linked per bluetooth and mock position app, Osmand records the altitude correctly. On the other hand, another GPS app reads correct altitude data from my phone’s GPS. So, it’s just the co-operation of Osmand and the internal GPS which is somewhat faulty.

**Comment by TWa-IT** [comment]
Issue started with 3.9.6 (PlayStore, Moto One Action / Android 10) and still exists with v3.9.9 (screenshot).

Regarding digits :
.xx with **v3.9.4** -> no issues
` <?xml version='1.0' encoding='UTF-8' standalone='yes' ?>
<gpx version="1.1" creator="OsmAnd+ 3.9.4" xmlns="http://www.topografix.com/GPX/1/1" xmlns:osmand="https://osmand.net" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.topografix.com/GPX/1/1 http://www.topografix.com/GPX/1/1/gpx.xsd">
  <metadata>
    <name>2021-02-04_14-47_Thu</name>
  </metadata>
  <trk>
    <trkseg>
      <trkpt lat="48.8130796" lon="9.9249712">
        <ele>410.32</ele>
        <time>2021-02-04T13:47:53Z</time>
        <hdop>9.279</hdop>
        <extensions>
          <osmand:speed>0.141</osmand:speed>
        </extensions>
      </trkpt>`

.x with **v3.9.9**
` <?xml version='1.0' encoding='UTF-8' standalone='yes' ?>
<gpx version="1.1" creator="OsmAnd+ 3.9.9" xmlns="http://www.topografix.com/GPX/1/1" xmlns:osmand="https://osmand.net" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.topografix.com/GPX/1/1 http://www.topografix.com/GPX/1/1/gpx.xsd">
  <metadata>
    <name>2021-02-24_13-00_Wed</name>
  </metadata>
  <trk>
    <trkseg>
      <trkpt lat="48.8130979" lon="9.9250937">
        <ele>410.3</ele>
        <time>2021-02-24T12:00:20Z</time>
        <hdop>15.7</hdop>
        <extensions>
          <osmand:speed>0.7</osmand:speed>
        </extensions>
      </trkpt>`

![Screenshot_20210224-141656_2](https://user-images.githubusercontent.com/79587398/109013796-d5048980-76b3-11eb-9330-b8ec8d7416bc.png)

**Comment by grosjo** [comment]
Same issue here on 3.9.9, android 11 (Aosp)

![Screenshot_20210214-150436_OsmAnd+.png](https://user-images.githubusercontent.com/2287111/109153273-fbd2c680-776c-11eb-9020-0dd393fd3d08.png)

All other apps are working properly with GPS , not OsmAnd

(you can see it on the screenshot)

**Comment by fredko48** [comment]
The same problem with version 3.9.9 ans a Nokia 7plus Android 10

**Comment by EugeneZmeuk** [comment]
https://issuetracker.google.com/issues/180218747
waiting fix from Google on 7th March

**Comment by TWa-IT** [comment]
> https://issuetracker.google.com/issues/180218747
> waiting fix from Google on 7th March

Seems that this update already reached my device.
->
![photo_2021-03-02_21-30-40](https://user-images.githubusercontent.com/79587398/109710924-92a0e800-7b9e-11eb-996d-dc503f433cb7.jpg)

**Comment by OldFartAtPlay** [comment]
Just to say it isn't only Osmand that suffers from this - eg Bosch ebike connect app and Maps.Me report the same incorrect altitude (for me) as Osmand

**Comment by sonora** [comment]
Looks like sooner or later google will have produced enough silly issues to make people despise Android for good, coders and users alike... :(

**Comment by kreuzschnabel** [comment]
Issue isn’t solved yet, and doesn’t seem to be Android’s fault.

Yesterday I recorded the drive to a 13 km walk, the walk itself, and the drive back. See attached image.

The drive to was recorded by OSMtracker on the same device, showing perfect altitude resolution (just a bit too high for lacking ellipsoid correction). 

The drive back was recorded by OsmAnd (3.9.10) at 1 s interval, showing the altitude issue discussed here.

Funnily, the walk itself, recorded by OsmAnd too, at 5 s interval, shows almost perfect altitude recording, just two small glitches.

In all tracks, the internal GPS unit was used, so the hardware is not to blame here.

System: OnePlus 5T, LineageOS 17.1, latest nightly as of March 2nd.

--ks

![Screenshot_20210307_104758](https://user-images.githubusercontent.com/22165960/110236202-cb411880-7f34-11eb-926e-4a3686f1a108.png)

**Comment by OldFartAtPlay** [comment]
Hello there... I was just about to email and saw this. For me, the issue has been resolved. I went for a short bike ride yesterday and observed while Osmand+ reported the altitude, varying as I went uphill and downhill. I don’t have a tracker image from Osmand, but at the same time my route data was captured by Bosch ebike app and I have an image from that:   The altitudes shown here, eg 83m at start and finish and c. 145m at the top, are the same as Osmand+ was displaying. Before yesterday Bosch was displaying a flat line just like Osmand+ Cheers, John  From: kreuzschnabelSent: 07 March 2021 10:04To: osmandapp/OsmAndCc: Old Fart At Play; CommentSubject: Re: [osmandapp/OsmAnd] 3.9 Critical issue with GPS altitude recorded (#10864) Issue isn’t solved yet, and doesn’t seem to be Android’s fault.Yesterday I recorded the drive to a 13 km walk, the walk itself, and the drive back. See attached image.The drive to was recorded by OSMtracker on the same device, showing perfect altitude resolution (just a bit too high for lacking ellipsoid correction).The drive back was recorded by OsmAnd (3.9.10) at 1 s interval, showing the altitude issue discussed here.Funnily, the walk itself, recorded by OsmAnd too, at 5 s interval, shows almost perfect altitude recording, just two small glitches.In all tracks, the internal GPS unit was used, so the hardware is not to blame here.System: OnePlus 5T, LineageOS 17.1, latest nightly as of March 2nd.--ks—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe. 

	
        
		Virus-free. www.avast.com

**Comment by OldFartAtPlay** [comment]
Hello again...Just did the same short route today, and recorded it in Osmand+. Here is the result:  Very similar to yesterday’s profile in the Bosch app. Cheers, John From: kreuzschnabelSent: 07 March 2021 10:04To: osmandapp/OsmAndCc: Old Fart At Play; CommentSubject: Re: [osmandapp/OsmAnd] 3.9 Critical issue with GPS altitude recorded (#10864) Issue isn’t solved yet, and doesn’t seem to be Android’s fault.Yesterday I recorded the drive to a 13 km walk, the walk itself, and the drive back. See attached image.The drive to was recorded by OSMtracker on the same device, showing perfect altitude resolution (just a bit too high for lacking ellipsoid correction).The drive back was recorded by OsmAnd (3.9.10) at 1 s interval, showing the altitude issue discussed here.Funnily, the walk itself, recorded by OsmAnd too, at 5 s interval, shows almost perfect altitude recording, just two small glitches.In all tracks, the internal GPS unit was used, so the hardware is not to blame here.System: OnePlus 5T, LineageOS 17.1, latest nightly as of March 2nd.--ks—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe. 

	
        
		Virus-free. www.avast.com

**Comment by vshcherb** [comment]
The issue is solved by Google with new Google Play release rolled out 7 of March.

**Comment by sonora** [comment]
@vshcherb  I assune you mean a 'Google Play services' update? Can you elaborate which version? I cannot find one published in March 7?

**Comment by kreuzschnabel** [comment]
Recording of today. Arbitrary changes of rough-steppy and precise recording :) Car profile, tracking interval 1 second.

![Screenshot_20210309_205555](https://user-images.githubusercontent.com/22165960/110530177-6cd58f00-811a-11eb-9c34-6799030e94e2.png)

**Comment by OldFartAtPlay** [comment]
HiyaI Think it is FuseLocationProvider API Cheers, John From: HardySent: 09 March 2021 19:41To: osmandapp/OsmAndCc: Old Fart At Play; CommentSubject: Re: [osmandapp/OsmAnd] 3.9 Critical issue with GPS altitude recorded (#10864) @vshcherb I assune you mean a 'Google Play services' update? Can you elaborate which version? I cannot find one published in March 7?—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe. 

	
        
		Virus-free. www.avast.com

**Comment by j-schneid** [comment]
On my Samsung XCover 4s with Android 10 and Osmand+ 3.9.10 the issue is not solved. Google Play services version is 21.06.13 (120406-358943053) - how can I determine if this is current? Googeling seems to result it's from March 09, 2021.
I tried a cycling trip with this phone running 3 apps simultaneously (no. 1-3 below) and another old phone (Samsung S5 active, Android 4.4.2, Osmand+ 3.9.6; see no. 4 below)
If it helps you, I can provide the original gpx files via pm.

The following screenshots only cover ~1/3 of the track's length to which the numbers apply to better show the smoothness of the recording.

1) Current Android, current Osmand+, recording in 5sec interval:
![grafik](https://user-images.githubusercontent.com/34659835/111070253-1036f300-84d1-11eb-8468-c1aa1ec6e0d9.png)
584 trackpoints, 1113.1m up and 1135.8m down. Wow!!!

2) Current Android, GPSLogger version 106, set to all GPS info that other apps provide, so minimum interval while gps unit is running
![grafik](https://user-images.githubusercontent.com/34659835/111070367-bedb3380-84d1-11eb-9e57-a480e4a07433.png)
3219 trackpoints, 129m up, 155m down. Comes close to what I expect.

3) Current Android, recording with Sports tracker app, exported via the web portal (so I'm not sure what sort of processing might have been applied by them):
![grafik](https://user-images.githubusercontent.com/34659835/111070498-53de2c80-84d2-11eb-9a22-fbbeeb0a0fe6.png)
1218 trackpoints, 112m up, 135m down.

4) Old phone, recording with Osmand+ 3.9.6 in 5sec intervals:
![grafik](https://user-images.githubusercontent.com/34659835/111070541-80924400-84d2-11eb-82ab-5a2bbeff1f39.png)
587 trackpoints, 250.7m up, 272.9m down.

5) Current phone, recording from October 13, 2020 with Android and Osmand+ versions presumably current at that day:
![grafik](https://user-images.githubusercontent.com/34659835/111070798-9a805680-84d3-11eb-86b4-a36e7e4cdf77.png)
1197 trackpoints, 119.4m up, 154m down.

I have the impression this is not only Google Play services, there seems to be an Osmand issue as well.

**Comment by vshcherb** [comment]
@j-schneid please try https://download.osmand.net/latest-night-build/OsmAnd-default.apk without google play services, so you can say for sure if it's google play services issue or not. Your results looks better then before but not as the other apps

**Comment by j-schneid** [comment]
Hello @vshcherb, thank you for the hint. First try was: Looks a lot smoother. I have yet to make a real comparison like the above. Would there be an Osmand+ version of it available?

**Comment by j-schneid** [comment]
Hello, now I did a systematic try including the Nightly. Unfortunately GPSLogger failed for unknown reason, it would have been my reference for the best recording I would expect. But anyway the nightly performed quite well I believe:
![grafik](https://user-images.githubusercontent.com/34659835/111542477-126bac80-8772-11eb-891f-1e5265a292dd.png)
(The last graph doesn't show the absolutely identical part of the track, but you get the idea.)

Did I understand correctly, the nightly behaves differently because it doesn't rely on Google Play services? So I can't expect a remedy when the next OsmAnd update comes via Playstore?

**Comment by vshcherb** [comment]
Version on Google Play **has to** use Google Play services (dot). It doesn't depend on us, so please don't ask us to upload nightly version to Google Play :-)

**Comment by sonora** [comment]
Does anyone know if google has communicated a defined Google Play Services version number where they claim this is fixed for all devices? Or is this still officially 'work in progress' on their side?

Mandating app providers to use their faulty mechanism and not fixing it seems like something we should maybe all addtess elsewhere, I am sure they take some heat for it somewhere?

**Comment by j-schneid** [comment]
So it looks as if I had to stay with the nightly version without the plus-features till Google fix their system.

**Comment by hmwallner** [comment]
i have been faced with this issue month ago on an Samsung xCover 4s Device with Android Version 10.
Until now...
an Android Aystem Update was deployed and installed
some Google Play Updates were deployed and installed
Failure persists...
so i keep on recording my Tracks with GPS Logger to Save...
and also record the Track in Osmand to see where i am going until the recording.
its a mess. is there an solution in sight?
with GPS Logger also downloaded from Google Play Store there is no problem.
![Unbenannt](https://user-images.githubusercontent.com/80352644/115588627-3a997e80-a2cf-11eb-8aac-ee948d28059c.JPG)

**Comment by bellera** [comment]
I have the same problem on BQ Aquaris X | Android 8.1.0 | OsmAnd 3.9.10
I started using **OsmAnd** on March, in order to replace **ViewRanger** for my trekkings.
I love opensource (I'm writing from my Linux) and I uses a lot **Viking GPS data editor and analyzer** with DEM data (for the elevations).
On **ViewRanger** I have IGN Spain Topographic maps and I have an **Elevation Graph** with GPS Elevation & Map Elevation. Of course, there are some differences, but not much. In general, it depends of the weather and orography. And normally I put my Android in **Airplane mode** when I start walking, in order to save battery.
I exported many **OsmAnd** traces to **ViewRanger** and **Viking GPS** and I see a lot of difference between GPS & Map & DEM elevations. So, something it's wrong for **OsmAnd**.

### Total Ascent/Descent on OsmAnd are pretty good
![1_OsmAnd_Statistics_Screenshot_20210521-093953](https://user-images.githubusercontent.com/8041180/119111157-168ea180-ba23-11eb-9ee0-8712027517ac.jpg)

### An OsmAnd track have a lot difference between GPS & Map elevations
![2_OsmAmd_track_at_ViewRanger_Altitudes_Screenshot_20210521-101702](https://user-images.githubusercontent.com/8041180/119111162-17273800-ba23-11eb-9d54-abe2cb8e147d.jpg)

### An OsmAnd track have a lot difference between GPS & DEM elevations
![3_OsmAnd_track_at_Viking_with_DEM_2021-05-21-105009_1920x1080_scrot](https://user-images.githubusercontent.com/8041180/119111165-17bfce80-ba23-11eb-8adf-0e44db3af207.png)

### A ViewRanger track, with few differences between GPS & Map elevations. Same zone and weather conditions that the OsmAnd track
![4_ViewRanger_track_Screenshot_20210521-101639](https://user-images.githubusercontent.com/8041180/119111167-18586500-ba23-11eb-8ea7-2b0246b809ee.jpg)

**Comment by kreuzschnabel** [comment]
@bellera This is a different issue. Your elevation recording shows a perfect tracking with just a constant offset, but not a straight level line where there was a considerable elevation profile with ups and downs. Your issue seems to base on different altitude interpretations (raw GPS measurement vs. ellipsoid correction).

--ks

**Comment by j-schneid** [comment]
This is an issue that would be worth a feature request. Ideally the possibility to choose different ellipsoids. Easiest and fastest to implement would be the possibility to manually enter a correction value. In my region I would have to enter -50m.

What is astonishing to me: Bellera seems to have good recordings currently whereas the discussion here seemed to show that there is a general problem of Osmand dealing with Google Play Services. Is it possible that not all devices experience the same problem?

Regards Joachim

**Comment by bellera** [comment]
@kreuzschnabel & @j-schneid thanks for your answers.
I installed [https://download.osmand.net/latest-night-build/OsmAnd-android-full.apk](https://download.osmand.net/latest-night-build/OsmAnd-android-full.apk) and also the app **GPS Status**.

### Staying at home, the compass shows 144 m and **OsmAnd** 194 m
![Screenshot_20210521-202902](https://user-images.githubusercontent.com/8041180/119184301-7f066e80-ba75-11eb-93c9-24a1ee1d023c.jpg)

**Comment by bellera** [comment]
**There is also about +50 m offset on iOS (Apple iPhone) traces.**
Matagalls summit elevation is 1697.2 m (official topo maps, Catalonia & Spain). OsmAnd recording says 1742 m (+44.8 m).
Applying DEM data to the track (with Viking GPS), Matagalls summit elevation is 1674 m. Osmand said +68 m (1742 m).

### OsmAnd iOS trace exported to ViewRanger. OsmAnd also shows +50 m
![6_Screenshot_20210522-122734](https://user-images.githubusercontent.com/8041180/119223520-3f359a80-bafa-11eb-9d7b-11eb698f8fdc.jpg)

**Comment by bellera** [comment]
I want to apologize if here is not the place to discuss the *elevation offset.* It seems an old problem. I've done some searching [https://www.google.com/search?q=osmand+elevation+offset](https://www.google.com/search?q=osmand+elevation+offset) and I found:

[altitude calibration for OsmAnd on Android phone ?](https://groups.google.com/g/osmand/c/9bRqJlSQrCk)
[Elevation of Irish mountains: Why the discrepancy OSM/Wikipedia](https://help.openstreetmap.org/questions/15397/elevation-of-irish-mountains-why-the-discrepancy-osmwikipedia)
[Android: How to get accurate altitude?](https://stackoverflow.com/questions/9361870/android-how-to-get-accurate-altitude)
[BasicAirData GPS Logger](https://learnosm.org/en/mobile-mapping/basicairdata-gpslogger/)

I found very interesting the comment on the last webpage, **This app is very accurate in determining your altitude if you enable EGM96 automatic altitude correction on settings.**

I don't know how **OsmAnd** process altitude. But I think should do better, specially for hiking. Thanks!

**Comment by bellera** [comment]
I think, finally, I understand ... **OsmAnd** doesn't use ellipsoid correction. Many other apps, yes.
**GPS Logger** doesn’t by default, but you can activate EGM96 or/and manual offset.
**GPS Status** uses by default WGS84 and you can add also a manual offset.
**ViewRanger** is not documented, but obviously it uses ellipsoid correction.
I think **OsmAnd** could do the same than **GPS Logger** because *the app is 100% Free and Open Source.*

Like this, as it shows @hmwallner at [https://github.com/osmandapp/OsmAnd/issues/10864#issuecomment-824198152](https://github.com/osmandapp/OsmAnd/issues/10864#issuecomment-824198152) we will have also a more stable curve of altitudes. I have some tracks at zones with **cliffs** with horrendous elevation data. 

### GPS Logger vs OsmAnd altitude curves (by @hmwallner)
![Unbenannt](https://user-images.githubusercontent.com/80352644/115588627-3a997e80-a2cf-11eb-8aac-ee948d28059c.JPG)

### GPS Logger and elevation corrections
![7_Screenshot_20210522-142357](https://user-images.githubusercontent.com/8041180/119227064-7ad96000-bb0c-11eb-9254-75bf684ab583.jpg)

### GPS Status and elevation corrections
![8_Screenshot_20210522-142249](https://user-images.githubusercontent.com/8041180/119227078-8cbb0300-bb0c-11eb-9329-e1ee427aa6ad.jpg)

**Comment by OldFartAtPlay** [comment]
Hiya...I have a feeling that you just need to download the correction database. I had consistently about 50m above actual altitude until I downloaded ‘worldwide altitude correction’ found under world maps. Hope this helps. Cheers, John   From: Josep Pujadas-JubanySent: 22 May 2021 14:02To: osmandapp/OsmAndCc: Old Fart At Play; CommentSubject: Re: [osmandapp/OsmAnd] 39 Critical issue with GPS altitude recorded (#10864) I think, finally, I understand .. OsmAnd doesn't use ellipsoid correction. Many other apps, yes.GPS Logger doesn’t by default, but you can activate EGM96 or/and manual offsetGPS Status uses by default WGS84 and you can add also a manual offset.ViewRanger is not documented, but obviously it uses ellipsoid correction.I think OsmAnd could do the same than GPS Logger because the app is 100% Free and Open Source.Like this, as it shows @hmwallner at #10864 (comment) we will have also a more stable curve of altitudes. I have some tracks at zones with cliffs with horrendous elevation data.GPS Logger vs OsmAnd altitude curves (by @hmwallner)GPS Logger and elevation correctionsGPS Status and elevation corrections—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe. 

	
        
		Virus-free. www.avast.com

**Comment by bellera** [comment]
>Hiya...I have a feeling that you just need to download the correction database. I had consistently about 50m above actual altitude until I downloaded ‘worldwide altitude correction’ found under world maps. Hope this helps. Cheers, John

@OldFartAtPlay, many thanks! It worked, after restarting **OsmAnd**!

I googled some more and (curioslly) **OsmAnd** has [EGM96 geoid offset correction for GPS altitude readings](https://osmand.net/downloads) since version 1.1 !!!

Other pages with your solution:
[Incorrect Altitude](https://www.reddit.com/r/OsmAnd/comments/dopb83/incorrect_altitude/?utm_source=amp&utm_medium=&utm_content=post_body)
[13. Altitude correction](http://www.ksrk-edu.ru/osmand/en/index.php?man=10)

I learned also the difference between [altitude/elevation](https://mapscaping.com/blogs/geo-candy/what-is-the-difference-between-elevation-relief-and-altitude) and [geoid/ellipsoid](https://gis.stackexchange.com/questions/80533/which-of-egm96-geoid-or-wgs84-ellipsoid-fits-the-earth-better). **These links content very interesting explanations/images**.

### About Google Play Services (GPSS for short)
[OsmAnd 3.9 - Google Play Services (Altitude issues)](https://docs.osmand.net/en/main@latest/osmand/troubleshooting/track-recording-issues#osmand-39---google-play-services-altitude-issues) **OsmAnd OFFICIAL doc**
[Reddit thread about OsmAnd and GPSS](https://www.reddit.com/r/OsmAnd/comments/lgyiua/google_play_services/)
[Why we decided to get rid off GPSS location library](https://www.mocaplatform.com/blog/moca-releases-location-aware-android-sdk-removing-google-play-services) MOCA Platform

**Comment by sonora** [comment]
In the app please go Menu / Download maps/All downloads, either enable or disable the "World altitude correction" file. Depending on your device chipset, you will receive the correct values either with or without that file.

**Comment by j-schneid** [comment]
On my Samsung XCover 4s with Android 10 "World altitude correction" doesn't work. Enabling doesn't change anything.
(@OldFartAtPlay, could you please fix your email client so it doesn't spam the tracker with gibberish?)
