### ISSUE TITLE
London (and other city?) borough boundaries need to be corrected

### ISSUE THREAD

**Issue by daslondon** [osmandapp/OsmAnd#11345]
I looked for 149 Westbourne Grove, London, which I found (named 147-149 Westbourne Grove), but the return said it was in the City of Westminster.  It is actually in the Royal Borough of Kensington and Chelsea (RBKC).

I appreciate it is tricky around there, because that section of Westbourne Grove is a boundary road, so the south side (odd numbers) is in RBKC and the north side (even numbers) is in Westminster.

However, on checking 292 Westbourne Grove, where both sides of the road are in RBKC, it still called it City of Westminster (and identified it as “288-292 Westbourne Gr”).

=>Clearly something needs to be done about correcting borough boundaries.

daslondon
info@schmetterling.com

**Comment by JonnyTech** [comment]
Feel free to edit the map yourself - openstreetmap.org is a community project powered by everyone. See the beginners guide to get started: https://wiki.openstreetmap.org/wiki/Beginners%27_guide

**Comment by daslondon** [comment]
JonnyTech, thanks, but the borough boundary is correct on OpenStreetMap, and search results appear somewhat differently.
This it looks like the borough boundary issue arises in the OsmAnd app.

**Comment by vshcherb** [comment]
As I see here https://nominatim.openstreetmap.org/ui/details.html?osmtype=W&osmid=363468834&class=amenity
it belongs to 2 city, so OsmAnd should be able to search both alternatives I guess in London and in Westminster. Unfortunately OsmAnd doesn't detect properly side of the street yet, so it will attach houses to the roads and check if the road belongs to the city itself.

**Comment by daslondon** [comment]
Yes, vshcherb, that is correctly shown on the OpenStreetMap, with the “City of Westminster” on the north side of that stretch.

The south side is Royal Borough of Kensington and Chelsea.  It is not marked and I was wondering how to add this.
I only started editing OSM recently and then only a few in my local area), so haven’t go the hang of everything.
--

**Comment by Zirochkabila** [comment]
`OsmAnd~ 5.2.0#6115m, Released: 2025-09-22`
`5238`

Map shows (Edgware) after Finchley, though Edgware is a separate town within the London Borough of Barnet. 
It should read (Barnet), since the borough contains both Finchley and Edgware.  

**Expected**: Queen's Road (Barnet), Finchley

`Live & without updates`

<details><summary>Details Android & iOS</summary>
<table style="width:100%">
  <tr>
 <th><img src="https://github.com/user-attachments/assets/30f27b84-aeec-4a68-b7b5-b9b1098cd4c1"  width="300" height="auto"/> </th>
<th><img src="https://github.com/user-attachments/assets/ba69e624-cb8b-46a8-b2db-fb541d785963"  width="500" height="auto"/> </th>
  </tr>
</table>  
</details> 

__________


[OSM Edgware](https://www.openstreetmap.org/node/279640#map=13/51.60693/-0.22779)

<details><summary>Details - Edgware</summary>
<img width="900" alt="Screenshot 2023-01-31 at 11 19 41" src="https://github.com/user-attachments/assets/ac3f65d7-d4b0-43c5-b241-058e89b5bb4f">
</details> 

[OSM Finchley](https://www.openstreetmap.org/node/27729625#map=17/51.598767/-0.178850)

<details><summary>Details - Finchley</summary>
<img width="900" alt="Screenshot 2023-01-31 at 11 19 41" src="https://github.com/user-attachments/assets/3658b893-a245-4d75-990b-ed3e27228e50">
</details>

[OSM Tudor Primary School](https://www.openstreetmap.org/way/41670358#map=17/51.600467/-0.176929)

<details><summary>Details - Tudor Primary School</summary>
<img width="900" alt="Screenshot 2023-01-31 at 11 19 41" src="https://github.com/user-attachments/assets/ed7f5393-7f96-48f1-83c1-985463d9a69b">
</details>

**Comment by vshcherb** [comment]
Something weird going on with these addresses
- https://www.openstreetmap.org/way/363468834
- During search `147 Westbourne Grove London` assigns wrong to Westminster - Westbourne Grove (City of Westminster), London
- During search `147 Westbourne Grove` it assigns correct? Westbourne Grove (Notting Hill), Kensington
- Where am I prefers Notting Hill - 1. 147-149 str. Westbourne Grove (Notting Hill) city Kensington dist=3
- Where am I: on the north side - 1. 122 str. Westbourne Grove (Westbourne Green) city City of Westminster

So it looks like only 1 search broken or not only? 


Some links
- https://www.openstreetmap.org/relation/51793#map=13/51.50378/-0.18929  Royal Borough of Kensington and Chelsea (place in)
- Kensington suburb https://www.openstreetmap.org/node/27467182
- https://www.openstreetmap.org/relation/51781#map=13/51.51184/-0.16359 City of Westminster (place not in)
- Suburb Victoria - https://www.openstreetmap.org/node/2288030394
- City of Westminster  - https://www.openstreetmap.org/node/27365306#map=17/51.497429/-0.134341
- Neighboorhood Westbourne Green  https://www.openstreetmap.org/node/716816528#map=14/51.51895/-0.19080


------------------

I believe the issue is still in the OSM data however it's very subtle or it's very tricky in the understanding. Basically OsmAnd assigns streets to cities (not to suburbs) as suburbs are part of the cities. 
1. However City of Westminster is a city and Kensington is a suburb. Creates a tricky situation
2. None of boroughs have associated admin_center pointing which makes it tricky and faulty to assign boundaries to the city and suburb. Probably the issue as well.
3. Technically by OsmAnd standard city is London - https://www.openstreetmap.org/relation/65606#map=10/51.4898/-0.0882. So probably we didn't implement city inside city like a suburb we did?

However I might be missing some understanding how it should be interpreted.

**Comment by vshcherb** [comment]
Example of place-municipality City of Melbourne - https://www.openstreetmap.org/relation/2404870#map=13/-37.81307/144.94416

**Comment by vshcherb** [comment]
Issue is finally clear
- Street from City of Westminster - Westbourne Grove  is incorrectly merged with street from Kensington which also linked to (Notting Hill). 

So in London city it becomes 1 street, which technically is correct as it is the same street. However while streets are merged their buildings are also merged and 147-149 belongs to it but with name (City of Westminster). And search result highlights it.

Based from data perspectivity they could be stored as separate streets - Westbourne Grove (City of Westminster) and Westbourne Grove (Kensington) but it could create other issues. Probably it's easier to fix search without changing the data

**Comment by JonnyTech** [comment]
> Probably it's easier to fix search without changing the data

I disagree. Wrong data is wrong data. For every OSM user. Maybe share your findings and get a conversation going at https://community.openstreetmap.org/

**Comment by vshcherb** [comment]
@JonnyTech I first didn't understand what's the complain is about and found very tricky situation with tagging like "place-city" inside "place-city" which as I see the only exception in the world. However it turns to be not the issue itself.

Main issue is merging street. And because streets could easily duplicate in Greater London (Wood street etc...), we add suburb / borough to the name "Wood Street (City of London)". However street goes from 1 borough to another and remains same street, so they are merged but the merging name is incorrect.

Possible solution as I see only 1
1. We can't keep it separate like "Wood Street (City of London)", "Wood Street (Westminster)" cause it will create issues in the rest of the world. Mainly it forces user. to know exactly the borough house belongs to which is very tricky sometimes.
2. We can't rename to "Wood Street" as it creates duplicate of in large cities
3. We can assign name "Wood Street (City of London, Westminster)" to indicate it belongs to 2 boroughs we need to check how long it is.

**Comment by Zirochkabila** [comment]
[OsmAnd Love hotel](https://osmand.net/map/poi/?name=%D0%9F%D0%BE%D0%B4%D1%83%D1%88%D0%BA%D0%B8%D0%BD&type=Love+hotel&pin=55.751102%2C37.578632#19/55.75100/37.57882)


- [x] 1. iOS displays the location as “Москва” while the web and Android display it as “Арбат” 


<details><summary>Details</summary>
<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/04f79749-1b8c-4677-ba64-f06699737120"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/ac99af35-1e0e-4e7b-b55e-0d2ba1fa3222"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/8f47c208-a375-4ab5-ba12-40b7f5682c9a"  width="600" height="auto"/> </th>
  </tr>
</table>     
</details>

**Comment by RZR-UA** [comment]
@Zirochkabila, the iOS bug with the Love hotel in City "404" is fixed. Now I'm working on the main subject.

**Comment by RZR-UA** [comment]
The Issue must have been fixed recently, together with the connected Issues: https://github.com/osmandapp/OsmAnd/issues/24832 and https://github.com/osmandapp/OsmAnd/issues/23547

I will include this 3 locations as test cases for the upcoming reverse geocoding [auto tests](https://github.com/osmandapp/OsmAnd/issues/23547#issuecomment-4395386153).

**288-292 Westbourne Gr**

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/0edcd05f-d8b7-4710-bfb6-d06cb0911dd9"  width="300" height="auto"/> </th>
  </tr>
</table>  

**147-149 Westbourne Grove**

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/24cb5df1-bef1-4b52-8c60-a60fb57d8c50"  width="300" height="auto"/> </th>
  </tr>
</table>  

**134 Westbourne Grove**

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/4eb61f0f-f116-4ca8-94d0-0f00b80eb8b4"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by Zirochkabila** [comment]
# Testing 1

> OsmAnd~ 5.4.0#7763m, released: 2026-05-13
> Web - prod

Map shows (Edgware) after Finchley, though Edgware is a separate town within the London Borough of Barnet.
It should read (Barnet), since the borough contains both Finchley and Edgware.

- [ ] **Expected**: Queen's Road (Barnet), Finchley - **Still not fixed**

[OSM](https://www.openstreetmap.org/way/41670358#map=18/51.600178/-0.176103)

<details><summary>Details - School = Queens Road, Finchley, London N3 2AG</summary>
<img width="900" alt="Screenshot 2023-01-31 at 11 19 41" src="https://github.com/user-attachments/assets/c039a858-b236-478c-9f40-121c2a9a9fcd">
</details> 


<details><summary>Details</summary>
<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/5701f1ab-ace6-41fa-ae76-29700c4c97b6"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/0932918d-4c2b-4bdb-8082-3609089e4070"  width="900" height="auto"/> </th>
  </tr>
</table>  
</details> 



________

iOS - waiting for

**Comment by RZR-UA** [comment]
@Zirochkabila, did you test the main locations for this issue?

- [x] 288-292 Westbourne Gr
- [x] 147-149 Westbourne Grove
- [x] 134 Westbourne Grove

`Tudor Primary School` is another, more complicated case.

OSM Way (Amenity): https://www.openstreetmap.org/way/41670358
Nominatim reverse: https://nominatim.openstreetmap.org/ui/reverse.html?lat=51.600257&lon=-0.177240&zoom=18

`Tudor Primary School, Queen's Road, Finchley, London Borough of Barnet, Greater London, England, N3 2AG, United Kingdom`

**Comment by Zirochkabila** [comment]
@RZR-UA 



1. **147-149 (South side**) now correctly shows **Kensington** instead of Westminster

`51.514764, -0.196606`
`147-149 Westbourne Grove`

<details><summary>Details</summary>
<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/22794075-167c-4302-856e-096e76f11dfc"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/094e02e3-9d91-493d-90c3-690af1c8cfbe"  width="300" height="auto"/> </th>
  </tr>
</table>  
</details> 

2. **134 (North side)** correctly shows **City of Westminster**

`51.515219, -0.196180`
`134 Westbourne Grove`

<details><summary>Details</summary>
<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/87a5dd13-7fea-4181-a648-8b30fd566c0e"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/1ae77941-4390-4131-b57b-154b3d03df00"  width="300" height="auto"/> </th>
  </tr>
</table>  
</details> 




- [ ] 3. **Around 292 Westbourne Grove**

> There is still some inconsistency: neighboring buildings are labeled interchangeably as **Kensington** or **Notting Hill**. While both are within RBKC (an improvement over Westminster), the address display remains unstable. Ideally, it should consistently refer to the borough level (RBKC) to maintain uniformity along the boundary road.


`51°30'48.8"N 0°12'13.6"W`
`292 Westbourne Grove`

<details><summary>Details</summary>
<video src="https://github.com/user-attachments/assets/c1649e8e-05e0-4257-9552-b4bb67176248"></video>
</details> 

- [ ] 4. Tudor Primary School (Hierarchy Issue)
Therefore, the expected result should be **School, Queens Road, Finchley**

> Regarding Tudor Primary School - OsmAnd currently shows `School, 14 Abingdon Road, Edgware` 
The school's address (on its official website) is listed as `Queens Road, Finchley, London N3 2AG` 
Nominatim shows `Tudor Primary School, Queen's Road, Finchley, London Borough of Barnet`

**Comment by Zirochkabila** [comment]
# Testing 1

> OsmAnd Maps 5403, released 25.05.26
> OsmAnd~ 5.4.0#7809m, released: 2026-05-25

- [ ] 1. **Around 292 Westbourne Grove**

> There is still some inconsistency: neighboring buildings are labeled interchangeably as **Kensington** or **Notting Hill**. While both are within RBKC (an improvement over Westminster), the address display remains unstable. Ideally, it should consistently refer to the borough level (RBKC) to maintain uniformity along the boundary road.


`51°30'48.8"N 0°12'13.6"W`
`292 Westbourne Grove`

<details><summary>Details</summary>
<table style="width:100%">
  <tr>
    <td><video source src="https://github.com/user-attachments/assets/c1649e8e-05e0-4257-9552-b4bb67176248"  width="300" height="auto"/></td>
<th><img src="https://github.com/user-attachments/assets/7a1fbdbb-a8ee-4647-b3da-f6a2d39dae6b"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/6defb582-7fde-45ac-aa65-aac8ba6e7ae8"  width="300" height="auto"/> </th>
  </tr>
</table>  
</details> 





- [ ] 2. Tudor Primary School (Hierarchy Issue)
Therefore, the expected result should be **School, Queens Road, Finchley**

> Regarding Tudor Primary School - OsmAnd currently shows `School, 14 Abingdon Road, Edgware` 
The school's address (on its official website) is listed as `Queens Road, Finchley, London N3 2AG` 
Nominatim shows `Tudor Primary School, Queen's Road, Finchley, London Borough of Barnet` 



[OSM](https://www.openstreetmap.org/way/41670358#map=18/51.600178/-0.176103)

<details><summary>Details - School = Queens Road, Finchley, London N3 2AG</summary>
<img width="900" alt="Screenshot 2023-01-31 at 11 19 41" src="https://github.com/user-attachments/assets/c039a858-b236-478c-9f40-121c2a9a9fcd">
</details> 


<details><summary>Details</summary>
<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/5701f1ab-ace6-41fa-ae76-29700c4c97b6"  width="300" height="auto"/> </th>
<th><img src="https://github.com/user-attachments/assets/66df20be-3c39-4d2f-b9a4-19e99f115526"  width="300" height="auto"/> </th>

<th><img src="https://github.com/user-attachments/assets/b244e702-1f03-40e6-8a7a-57e15b2cdc05"  width="300" height="auto"/> </th>
<th><img src="https://github.com/user-attachments/assets/32ea68ba-3e1f-4091-88c3-dd1fa097f74b"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/0932918d-4c2b-4bdb-8082-3609089e4070"  width="900" height="auto"/> </th>
  </tr>
</table>  
</details>

**Comment by daslondon** [comment]
I was reviewing the discussion regarding Westbourne Grove and its being a boundary between two London boroughs, the City of Westminster and the Royal Borough of Kensington and Chelsea (RBKC), for a small part  of it. This only between Ledbury Road (north side) and Chepstow Road, from W to E. The borough boundary is shown correctly on OpenStreetMap as of now.
(Am not sure why the borough boundary on Ledbury Rd is drawn on the west side of the street, rather than down the middle as shown correctly elsewhere.)

I should clarify a couple of things:
1. It is not correct to state that "Westminster is a city" and "Kensington is a suburb". They are two of 32 'regular' London boroughs, each administered in a similar way (I won't get into the details of a few of them having elected executive mayors rather than honorary ones...). In addition there is another, rather special, borough called The City of London (or The City), which is very small and run on different lines. It contains the Bank of England.
2. There is no legally defined area called Notting Hill, and it does not figure in any official addresses. To avoid confusion I would not use the term on a map.

**Comment by vshcherb** [comment]
Not sure if it's related for new geocoding or we can fix for old one as well
- [ ] It's preferred to show both suburbs and city or at least show suburb with most buildings
- [ ] For Abingdon Road and school (there is no housenumber so it's not present as building) - it should be display Finchley - suburb (not town). So both "city" and "suburb". 

Regarding "borough" vs "suburb". We don't index borough as part of the streets we can probably add borough information as it's now available in Address search as Boundary though we don't have geoindex of that and that will be a separate task to add it.

<img width="1245" height="490" alt="Image" src="https://github.com/user-attachments/assets/c5a5e8ea-1394-4694-8426-82e3b780b323" />

@daslondon we still address all streets to "City", so mostly they are represented as "Street (closestSuburb)" - "City or Town". Mostly streets are not duplicated by addressing a suburb however suburbs don't have exact boundaries, so borough or township is an extra information however the common address (website) doesn't use them and points with Suburb "Queen's Rd, London N3 2AG, United Kingdom". It looks like it will be an additional task
