### ISSUE TITLE
Regression: Track appearance now always defaults to width=1

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#11827]
This is a regression but has been around for some time now (ever since the redesign of the track display dialogs):

When you look at e.g. the Touring view renderer, its currentTrackWidth should default to 8 (https://github.com/osmandapp/OsmAnd-resources/blob/799e740e81fbf4ec11c626c4b28fc6198bc16834/rendering_styles/Touring-view_(more-contrast-and-details).render.xml#L173). But when I open a track I think I have never openend before, it displays with track width 1. (Unfortunately with the bright default color it is hardly visible and users think it does not display at all).

**EDIT: The issue does NOT occur for the "Currently recorded track", that one (while recording) is displayed perfectly fine. It does also NOT occur if that one is finished and saved, then later re-displayed. But it DOES occur also for that track once you have renamed it!**

I am not sure where to fix this. Imported tracks do not seem affected (correctly display with width Medium=8). But it seems all tracks are affected which I have in my tracks folder (e.g. transferred from another device after a fresh installation, or even newly recorded ones while "View currently recorded" was turned off) and have never previously been displayed in the new installation.

I notice that track width 1 seems the default in our OsmAnd renderer, so it probably has to do with not correctly capturing other renderers'  defaults.

**Comment by sonora** [comment]
I have now heard from several users who did not notice the track being displayed at all, making all track display functionality useless for them. Hence I suggest we should not delay fixing this to v4.1.

Since things work perfect for new recordings, the bug seems limited to our code opening tracks nnewly added to the file system or renamed tracks only.

**Comment by sonora** [comment]
Best way to reproduce is as follows:
1. Select a renderer which has a default track width >1, e.g. The Touring view has default 8.
2. Record a track with 'Show currently recorded' being set to true. The track will during recording show correctly in the defaults (color cyan, width 8).
3. Finish the recording. The track will still display correctly.
4. Now go to MyPlaces/Tracks and rename that track (in the rec folder), e.g. by adding a character to the end. The track is now still displayed in its default color, but **the width is reset to 1**. If the default color is bright or transparent enough, ever re-displaying that track in the future would also show it virtually invisible.

The issue is also present if you manually add tracks, e.g. commercial ones, to your track folder in the system, then later select them in OsmAnd's MyPlaces to display. But that may be harder to reproduce, and may be a rarer use case for many.

**Comment by cepprice** [comment]
@sonora I can't reproduce this bug, track width always stays 8. 

I have tried:

1. Manually moving new file to tracks folder
2. Renaming visible/invisible track via my places and GPX context menu
3. Saving recorded track without showing with and without renaming it via saving dialog and my places
4. All previous steps after fresh installation on emulator and physical device

Maybe I have missed something, or is there another way to reprodice this bug?

**Comment by sonora** [comment]
@cepprice  Thanks for looking into this! I've checked our code and simoly cannot find the flaw.

Best way to reproduce for me is like what you state in your method  '3.':

- I record a track, I have 'Show currently recorded' set enabled. Track will display fine while being recorded. 
- Now finish the recording via the widget by tapping the 'Finish' button. The displayed track on the map becomes 'thin' immediately after this, while the  'Track saved'  dialog is being displayed.
- If you now rename that track on the Track saved' dialog,  the track's thin appearance will become permanent.
- I just notice that if I instead leave that dialog by simply tapping 'Close' without renaming, the track appearance will be displayed thick again.ecome

**Please make sure you are using the 'Touring view' Map style for all this!** I suspect this has to do with in some cases not correctly handling `renderer.PROPS.getCustomRule(CURRENT_TRACK_WIDTH_ATTR)`

Please let ne know if you still cannot reproduce with Touring view. I have reproduced on different devices and fresh installs, so it is not an individual flaw in one device's gpx database.

**Comment by cepprice** [comment]
@sonora Still can't reproduce. I have tried to restart after switching to Touring view, but nothing changed. 

And it's strange that you even can see newly recorded track after tapping "Finish" button, while "Track saved" dialog displayed.
At this moment current track is cleared => can't be seen, and newly recorded track is invisible until user clicks "Open track" or closes dialog with turned on switch "Show on map".

**Comment by sonora** [comment]
I think you are right that the track is not thin but completely hidden while the "Track saved" dialog is displayed.

So please either rename the track on that "Track saved" screen,  or tap "Close" on it, then go to MyPlaces/Tracks, and rename that track there. In both cases the track then appears thin.

**Comment by sonora** [comment]
@vshcherb Closed in error? This is not fixed.

(The entire discussion above is just about how to reproduce it.  But this is a true issue, and it is deterministic, not sporadic.)

**Comment by cepprice** [comment]
@sonora It turned out that this issue and [this one](https://github.com/osmandapp/OsmAnd/issues/11879) have one source.

**Comment by sonora** [comment]
Right, I think so, too! ;)

**Comment by vshcherb** [comment]
Should be fixed soon, the cause was identified

**Comment by sonora** [comment]
Is there some reset or cleanup either the user or we in the code could perform to the GPX database?

Looks like https://github.com/osmandapp/OsmAnd/pull/12091 fixed it for the use cases of newly added, newly recorded, and renamed  tracks.

But the issue still remains active for me for all 3000 tracks I already had in my tracks folder before the fix. Temporarily emptying the folder did not seem to work, what needs to be done?

**Comment by vshcherb** [comment]
@sonora it's probably the database is already corrupted and there is no easy way to restore it. I'm afraid it would be too much investing time in non-release version. 

For you the easiest fix might be backup all tracks. Delete all tracks and import again to reset to default settings.

**Comment by sonora** [comment]
Right, thanks. I had already tried this, but had made one mistake:

So to everyone who has this issue: While you can perform the "restore" operation of the tracks folder simply by a copy/paste in a file manager app or via a PC, for the preceding "delete all tracks" you **have to make sure you do this in the OsmAnd app itself** (`Menus/MyPlaces/Tracks`).

It seems that if you simply empty OsmAnd's  track folder in the file system vis an app or the pc, OsmAnd does not reflect this deletion in its GPX database but keeps the old (faulty) records. Once you restore the files (with the same names), you are left with the former issue again.

@vshcherb I am wondering if we should consider this lack of syncing "_deletion in tracks folder -> GPX database_" as a bug which needs fixing?

**Comment by sonora** [comment]
Cool, Victor, thx! I guess we should maybe somehow include a check for orphaned GPX-database entries which do not exist as GPX-files any more... as they may accumulate over time.
