### ISSUE TITLE
White Button, lack of verifying box and other errors.

### ISSUE THREAD

**Issue by franco999** [osmandapp/Osmand#1184]
I have version nightly 2.1.0#11036M and a Sony ST21a phone.
More info: https://groups.google.com/forum/#!topic/osmand/EKxuFa4I3DQ
![botonblanco](https://cloud.githubusercontent.com/assets/12088580/7499070/b41e27bc-f3fb-11e4-9e71-756f19bf7f24.png)
![falta checkin](https://cloud.githubusercontent.com/assets/12088580/7499072/b43b530a-f3fb-11e4-9933-287b5202d8c4.png)
![malalineado](https://cloud.githubusercontent.com/assets/12088580/7499071/b42ab932-f3fb-11e4-944c-87ca26a8a282.png)
![malalineado2](https://cloud.githubusercontent.com/assets/12088580/7499075/b496a958-f3fb-11e4-9892-60ef44c3fcaa.png)
![modenightday](https://cloud.githubusercontent.com/assets/12088580/7499076/b4a5e59e-f3fb-11e4-9944-d6775314b303.png)
![navigation](https://cloud.githubusercontent.com/assets/12088580/7499074/b44e1da0-f3fb-11e4-8d66-cb91553a2740.png)

**Comment by vshcherb** [comment]
padding is fixed

**Comment by franco999** [comment]
The only correction I see in the #11051M is the photo 2 (the checkbox). Everything else remains the same.

**Comment by vshcherb** [comment]
Fixed other issues

**Comment by franco999** [comment]
Perfect. The only thing that still looks the same, it is the penultimate and last image.
Why the night mode button is more big or viceversa?

**Comment by franco999** [comment]
I found another mistake.
![11](https://cloud.githubusercontent.com/assets/12088580/7521926/0719d066-f4c8-11e4-9176-47fc4057de38.png)

**Comment by vshcherb** [comment]
This is duplicate to already existing

**Comment by franco999** [comment]
The last error remains in white button version # 11112M. Please, fixed.
