### ISSUE TITLE
Live Updates "Fixme" key 

### ISSUE THREAD

**Issue by duiveldoder** [osmandapp/OsmAnd#12960]
The live updates - which are most importantly for actual mappers, do not include the "fixme" key

Can you please include this key in the live updates?

And please ASAP - i.e. let me know what nightly it'll be included - it's kinda important for me to see what actually needs to be done :)

Thank you

**Comment by alisa911** [comment]
https://github.com/osmandapp/OsmAnd-resources/pull/757
https://github.com/osmandapp/OsmAnd-core-legacy/pull/59
before fix in core-legacy with remove pattern="split"
<img width="217" alt="Screenshot 2021-12-16 at 18 39 10" src="https://user-images.githubusercontent.com/38911173/146423331-a17cc2d0-fb9d-4422-a3d0-bff356a051fa.png">
after
<img width="352" alt="Screenshot 2021-12-16 at 18 31 44" src="https://user-images.githubusercontent.com/38911173/146423399-c2f94300-6803-454f-bd02-e05bba90e3c7.png">
polygons and polylines are fine too
<img width="325" alt="Screenshot 2021-12-16 at 18 33 19" src="https://user-images.githubusercontent.com/38911173/146423582-90c0d2c8-3077-4d22-a493-56e05a30f2a8.png">
<img width="563" alt="Screenshot 2021-12-16 at 17 48 20" src="https://user-images.githubusercontent.com/38911173/146423643-44a6b5cf-c1f5-4eb3-8e14-3b50841abc17.png">

**Comment by vshcherb** [comment]
We need to test it https://builder.osmand.net:8080/view/WebSite/job/OsmAndTestRendering/

**Comment by ivanPyrohivskyi** [comment]
- [ ] Rendering test, see comment above
- [ ] Fix iOS (core)
- [ ] Remove SPLIT from generation

**Comment by alisa911** [comment]
In the test results, a lot of things are missing or replaced
<img width="1908" alt="Screenshot 2021-12-27 at 18 21 15" src="https://user-images.githubusercontent.com/38911173/147490226-a544c5fc-5562-43e2-aaa3-2536e88c11ab.png">
<img width="1862" alt="Screenshot 2021-12-27 at 18 23 52" src="https://user-images.githubusercontent.com/38911173/147490252-fdc5f27e-6ca0-458a-8086-b4d534b339ff.png">
<img width="1906" alt="Screenshot 2021-12-27 at 18 22 14" src="https://user-images.githubusercontent.com/38911173/147490315-9c5920f3-5639-4ad0-8a4e-579b2e740651.png">

**Comment by alisa911** [comment]
Place for test http://www.openstreetmap.org/#map=18/50.50273/30.09813
Generated map:
- [Place.obf.zip](https://github.com/osmandapp/OsmAnd/files/7792262/Place.obf.zip)
- [place.osm.zip](https://github.com/osmandapp/OsmAnd/files/7792263/place.osm.zip)

**Comment by ivanPyrohivskyi** [comment]
I can not fast resolve this for Core at this moment.
Difficulty start here [MapPrimitiviser_P.cpp#L2525](https://github.com/osmandapp/OsmAnd-core/blob/953fb6d474aba8679923e54436d7697ed94dd6c0/src/Map/MapPrimitiviser_P.cpp#L2525).
Main issue here [MapStyleEvaluator_P.cpp#L270](https://github.com/osmandapp/OsmAnd-core/blob/953fb6d474aba8679923e54436d7697ed94dd6c0/src/Map/MapStyleEvaluator_P.cpp#L270).
ruleNode->getIsSwitch() == false - for ussual objects
ruleNode->getIsSwitch() == true - with "fixme" tag

**Comment by ivanPyrohivskyi** [comment]
[Place_fixed.obf.zip](https://github.com/osmandapp/OsmAnd/files/7972292/Place_fixed.obf.zip)

**Comment by alisa911** [comment]
https://github.com/osmandapp/OsmAnd-resources/pull/823

**Comment by alisa911** [comment]
https://github.com/osmandapp/OsmAnd-core-legacy/pull/88

**Comment by alisa911** [comment]
![Uploading Screenshot 2022-05-13 at 12.59.01.png…]()

**Comment by alisa911** [comment]
ios
<img width="378" alt="Screenshot 2022-05-13 at 12 59 01" src="https://user-images.githubusercontent.com/38911173/168263713-c141616f-62f9-46dd-b1d6-c2deef5985e2.png">

**Comment by alisa911** [comment]
https://github.com/osmandapp/OsmAnd-resources/pull/823

**Comment by aceman444** [comment]
Yeah, 'fixme' tags are not updated in OsmAnd live updates. Even when fixme is removed in OSM data, it is still shown in OsmAnd.
Thanks for fixing this.

**Comment by duiveldoder** [comment]
Yes I'm happy to see this is a work in progress - as mapper for me this is a critical issue with the live updates.

The live updates I have primarily to support me on my mapping/contributions and then I could really have the area "cleaned up" to see what I've been over or not.

Just out of curiosity, why does it take so long to fix this? Isn't it just a matter of:"check local fixme keys/tags vs online and add/remove accordingly?"

Just a question trying to understand why it's not a simple routine to verify the key/tag that exist locally on the device and update accordingly to the online OSM databse?

**Comment by vshcherb** [comment]
Previously we had a problem with rendering engine, so we processed tags in a special way which causes problem in OsmAnd Live. Now we fixed the rendering engine and it should work

**Comment by duiveldoder** [comment]
would 

> Previously we had a problem with rendering engine, so we processed tags in a special way which causes problem in OsmAnd Live. Now we fixed the rendering engine and it should work

would you be so kind to let me know how this is supposed to work?

I removed a fixme near me already about 2 weeks ago. And using the live update - to be sure just updated to the latest nightly build of June 2, it still shows the fixme..

maybe some other renderer?

**Comment by aceman444** [comment]
If it is a fix in the rendering engine I assume it can't be seen in stable OsmAnd releases like 4.1. Only in nightlies.

**Comment by duiveldoder** [comment]
Some more information on this.
![Screenshot_20220608_013753_net osmand plus](https://user-images.githubusercontent.com/15773876/172448007-7b3b8caa-3d92-406a-9a72-3b9c9a118996.jpg)

the very long fixme text I fixed/removed already several weeks ago and the ones east of it I fixed/removed last week.

In all my profiles I still see the fixme's
1) Browse Map profile uses Mapnik
2) Walking uses offroad
3) Public Transport uses Mapnik
4) Mapping uses offroad

Map Styles I then switched for my mapping profile to
OsmAnd (fixme still not being updated)
Desert (fixme not being updated)
lightRS (doesn't show any fixme)

I'm really sorry - but for me it doesn't work still.

No fixme is being updated..

And of course I'm using the nightly, I update once a week or so to the most recent nightly right now using the one from 5 June

**Comment by vshcherb** [comment]
Ok we will double check

**Comment by Zirochkabila** [comment]
We checked your case - it could not be recreated. Displaying points and deleting them works.

Check if you have a subscription to OsmAnd Live which allows you to see updates every hour. Or purchase OsmAnd Pro as shown on the screenshot.
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/173064598-7a65ed8c-af2d-418a-b52e-2b5662eaf61f.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>  

If you do not have a subscription to OsmAnd Live and OsmAnd Pro, updates from OSM will be visible for one month.


> Some more information on this.
> 
> <img alt="" width="300" height="auto" src="https://user-images.githubusercontent.com/15773876/172448007-7b3b8caa-3d92-406a-9a72-3b9c9a118996.jpg">
> the very long fixme text I fixed/removed already several weeks ago and the ones east of it I fixed/removed last week.
> 
> In all my profiles I still see the fixme's
> 
> 1. Browse Map profile uses Mapnik
> 2. Walking uses offroad
> 3. Public Transport uses Mapnik
> 4. Mapping uses offroad
> 
> Map Styles I then switched for my mapping profile to OsmAnd (fixme still not being updated) Desert (fixme not being updated) lightRS (doesn't show any fixme)
> 
> I'm really sorry - but for me it doesn't work still.
> 
> No fixme is being updated..
> 
> And of course I'm using the nightly, I update once a week or so to the most recent nightly right now using the one from 5 June

**Comment by vshcherb** [comment]
The issue is reproducible sometimes (rare and weird) on Android OpenGL version but it's enough to restart the app to get the map updated. We will keep an eye on this issue once we understand what's going on.

**Comment by duiveldoder** [comment]
> ye on this issue once we understand what's going on.

I understand on other systems it may not be the case what I experience. But on my android it's permanent.. Always like this.

And yes I have live updates - hourly..

**Comment by Zirochkabila** [comment]
Which Fixme tags are you not removing (please add a link from the OSM) or their location. So that we can check them

**Comment by vshcherb** [comment]
https://github.com/osmandapp/OsmAnd/issues/14784
