### ISSUE TITLE
Map is not rendered in new Pixel 6

### ISSUE THREAD

**Issue by zugspitze** [osmandapp/OsmAnd#14947]
### Description
Hi, I have been using OsmAnd for the last 6 years and I bought a new Pixel 6 where the map is not rendered at all. 

### How to reproduce?
Install the app, download your region and go to map. I expect the map but I see nothing

### Your Environment
OsmAnd Version: 4.2.7
Android/iOS version: 12
Device model: Pixel 6

**Maps used (online or offline):**   
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.

**Comment by zugspitze** [comment]
![Screenshot_20220727-161706](https://user-images.githubusercontent.com/12557673/181270639-614e2d08-1cc6-4a73-ba92-8cd2c91b8428.png)

**Comment by zugspitze** [comment]
![Screenshot_20220727-162209](https://user-images.githubusercontent.com/12557673/181271598-4c63cd76-11b7-4210-b077-4226ff40eb61.png)

**Comment by vshcherb** [comment]
It looks very weird. Did you try to reinstall? Did you enable/disable in Development plugin -> OpenGL rendering?

**Comment by zugspitze** [comment]
Yes, I tried to re-install and enable/disable OpenGL rendering. Looks like other people are having the same issue: https://www.reddit.com/r/OsmAnd/comments/w9g6w7/offline_vector_maps_not_working/

**Comment by zugspitze** [comment]
A phone restart did the trick

**Comment by dkniffin** [comment]
I'm still experiencing this issue, even after a phone restart. I'm also on a pixel 6

**Comment by dkniffin** [comment]
I think I just fixed it, by enabling the development plugin, then enabling opengl

**Comment by v4hn** [comment]
I don't think this issue should be closed until the default works.
I had to enable OpenGL and restart the phone to get it to work.

**Comment by tretum** [comment]
I also had this happen on a Fairphone 4 running Android 11. Tried to find a problem with configurations for an hour and nearly went mad until I found the reddit thread. Enabling the dev plugin and the OpenGL option in the settings of the plugin followed by a restart of the app helped. This is a serious problem. Screen looked comparable to the pictures from OP.

Device: Fairphone 4
Android version: 11
OsmAnd version: 4.2.7
Navigation profiles have been reset to factory default.

**Comment by franco999** [comment]
The same thing happens to me with versions later than OsmAnd~ 4.3.0#13697mqta, (2022-08-08).

I have tried even the latest nightly and it still happens.

On first startup, the maps load fine but when I close and reopen the application, they don't load anymore. I have to close the application to be able to see the maps and their data again.

My phone is Xiaomi Mi A2 Lite (Havoc 4.19, A11)

**Comment by vshcherb** [comment]
Exactly same on  Xiaomi 11T. 

**Important**: workaround to enable and use OpenGL rendering works!

**Comment by franco999** [comment]
I have tried with OpenGL on and off but it doesn't solve the map loading problem. I always have to revert to the 2022-08-08 version which works fine for me.

**Comment by sonora** [comment]
Think we should establish more clearly which versions are affected. Is a fallback to 2022-08-08 really a reliable fix? Because I see this being reported also for the 4.2.7 release, which was last built on 2022-07-13?

**Comment by vshcherb** [comment]
Yes 2022-08-08 is a first date ... We need to investigate when it starts happening. we also have rotation bug now, probably is related?

**Comment by franco999** [comment]
In case it helps, I put my problem more graphically in these videos.

- This version works fine for me.

https://user-images.githubusercontent.com/12088580/185606231-b34dac28-d08d-4aea-b7e6-d5e99805f53c.mp4

- All later OpenGL versions do this problem.

https://user-images.githubusercontent.com/12088580/185606266-8c112564-ab5f-4fe9-a771-417c3e4708f6.mp4

**Comment by pebogufi** [comment]
I had first problems with map display with
OsmAnd~  4.3.0#34434m.apk 2022-08-04
but NO problems with
OsmAnd~  4.3.0#34448m.apk 2022-08-06
and problems since 
OsmAnd~  4.3.0#34467m.apk 2022-08-10
on Device Samsung S7, Android 8.
Sounds irritating.

**Comment by sonora** [comment]
@pebogufi  Thanks!!

Looking at out code history, it sounds hard to believe that _OsmAnd~ 4.3.0#34448m.apk 2022-08-06_ would not exhibit the issue... Can you perhaps go back and verify that version?

**Comment by pebogufi** [comment]
Ok, is in progress

**Comment by vshcherb** [comment]
We suspect now should be fixed https://github.com/osmandapp/OsmAnd/commit/dadbd6e6fad5a01e49efe07c296d7fd06698dc53

**Comment by franco999** [comment]
Seems to have been fixed in OsmAnd~ 4.3.0#13723mqta, (2022-08-19)

**Comment by alewando** [comment]
When will 4.3.0 (with the fix) be available in the Play store? As of today (3 months after the fix was posted) the version available in the store is still 4.2.7.

**Comment by vshcherb** [comment]
4.3.0 is already in beta, public release this month probably
