### ISSUE TITLE
[Bug] Elevation Widget Looses Alignment After 10km

### ISSUE THREAD

**Issue by Dollarius** [osmandapp/OsmAnd#15984]
### Description
The elevation widget works well for the first 10km of navigation, updating the current position on the graph.
1. After navigating 10km, the alignment is good as long as the screen is kept ON.
2. When the screen is turned OFF and then back ON, the graph is reset to position 0km and the current position is not visible.
3. Moving the map and then pressing the recentre button...
4. The elevation widget gets realigned correctly.

![20221215_233728](https://user-images.githubusercontent.com/56419637/207890274-5a3d04af-f4c0-4644-b5bb-1be46d8a49cc.jpg)

This happens both with opengl (V2) and the older engine (v1), both with slope enabled (as in the screenshots) and disabled.
This is a problem when navigating as I always turn off the phone display to save battery.

### Your Environment
OsmAnd Version: OsmAnd~ 4.4.0#35115m, released: 2022-12-12
Android/iOS version: Android 12
Device model: Samsung Galaxy S20 FE

**Comment by scaidermern** [comment]
Sounds like #14700.

**Comment by sonora** [comment]
And perhaps the same root cause as #14331 (in which case it is claimed fixed now).

**Comment by Zirochkabila** [comment]
**Reproduced**
[logcat (33).log](https://github.com/osmandapp/OsmAnd/files/10253601/logcat.33.log)
[RF Altdorf SZ (1).gpx.zip](https://github.com/osmandapp/OsmAnd/files/10253602/RF.Altdorf.SZ.1.gpx.zip)

### Steps to reproduce
Navigation > Select RF Altdorf SZ gpx > Set start as gpx start position > Simulate location by gpx > Select RF Altdorf SZ gpx  (try to insert 5.0 simulate speed)> Wait to riding 12km > Locked screen > Unlocked

### Actual result

https://user-images.githubusercontent.com/104760013/208294030-cd9382ba-39d8-4ae9-b3bc-50b4e35646b0.mp4



### Expected result
The route in the altitude widget ( bottom panel ) remains at the same position as before the screen lock

### Your Environment
OsmAnd Version: OsmAnd~ 4.4.0#14031mqta, released: 2022-12-18
Android/iOS version: Android 12
Device model: Poco x3 nfc

**Comment by alex-osm** [comment]
https://github.com/osmandapp/OsmAnd/commit/49f50586811cfe3828c29290a2bae46c660441b3

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14050mqta, released: 2022-12-27
Still present
[logcat (39).log](https://github.com/osmandapp/OsmAnd/files/10307876/logcat.39.log)


https://user-images.githubusercontent.com/104760013/209660855-ee08b646-c439-4226-9f05-c3ad25515bf6.mp4

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14057mqta, released: 2022-12-28
Done
