### ISSUE TITLE
Hiking trail(s) get(s) split

### ISSUE THREAD

**Issue by mdykierek** [osmandapp/OsmAnd#16058]
Consider this point: https://www.openstreetmap.org/node/1741133570#map=19/50.09174/18.96211
On both left and right hand side there is a blue marked hiking trail Szlak Obrońców Polskiej Granicy.
However if you select on either side you get either 57 km section or 3 km sections while it is a single relation.
Please let me know why it happens so that I can fix it in OSM or fix it in OsmAnd.

### Your Environment
OsmAnd Version: OsmAnd+ 4.3.4
Android/iOS version: Android 11
Device model: Xiaomi Mi 9T Pro

**Maps used (online or offline):**   
December 2022 with Live updates.

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14064mqta, released: 2022-12-30

`50.09168, 18.96214`
Most likely, these are two segments of one route.
By the [link](https://www.openstreetmap.org/relation/1363303#map=11/50.1839/18.8841), you can see that the total length reaches 60.9 km, and the segments visible in the video are 57.4 and 3.16 respectively, together these segments form a complete route


https://user-images.githubusercontent.com/104760013/210045530-5ed0547a-6832-48a5-83d8-a6055adc204f.mp4

**Comment by mdykierek** [comment]
So how does one make it a single segment route?
The only difference between left and right is that on the left (West), the route has track type and on the right (East) doesn't. They also different in surface. As you noted this is a single relation I had recently fixed by adding a missing way.

**Comment by mdykierek** [comment]
So how does one make it a single segment route?
The only difference between East and West side of this point is that West has track type while East doesn't. They also differ in surface. As you noted, this is a single relation I had recently fixed by adding a missing way somewhere else.

**Comment by Dima-1** [comment]
The issue was due to this way consisting of one segment
![2023-01-25_11-49](https://user-images.githubusercontent.com/31807095/216564439-5341d9f1-308a-4310-a7a1-f1363375d62e.png)

Now the problem remains only with the shield on this segment
![2023-02-02_19-36](https://user-images.githubusercontent.com/31807095/216564459-2b046080-35fc-4b1a-b83a-bdb73e363cd3.png)

**Comment by vshcherb** [comment]
Move back with fix - https://github.com/osmandapp/OsmAnd/commit/1e8187831cc53e7940af44ca1a8cd07509ee79dc

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14189mqta, Released: 2023-02-20
Done
