### ISSUE TITLE
Android deep linking - app-to-app communication without the web experience

### ISSUE THREAD

**Issue by valeriik** [osmandapp/OsmAnd#16485]
I cannot find other deep link then this:
`https://osmand.net/go.html?lat=${latitude}&lon=${longitude}&z=17`
And when I try to open OsmAnd via this deep link Android OS offers me the choice to open the app through the installed application OR through a web browser.

For example Waze app has next deep link:
`waze://ul?ll=${latitude},${longitude}&navigate=yes`
and therefore Android OS opens Waze app without any additional questions from the user what he/she wants to open this link.

Explanation is here:
https://developers.google.com/waze/deeplinks/
"...If you're sure that the Waze app is installed, you can use the URL "waze://" for app-to-app communication **without the web experience**. ..."

So how to open OsmAnd app directly and without this choice to open with a web app?

**Comment by vshcherb** [comment]
Deep links are configured on website - https://osmand.net/.well-known/assetlinks.json

**Comment by vshcherb** [comment]
Fixed works with released version (doesn't work with OsmAnd~)

**Comment by Peter080202** [comment]
> OsmAnd

As @Zirochkabila mentioned in another issue:

If you open the link (the one that was shared, POI) when the application is active - OsmAnd opens at the POI location. If you open the link when the application is closed - OsmAnd opens at the location of the last map view (does not move the map to the POI).

This feature/bug is still not working as mentioned. Will this be implemented in the nearer future @vshcherb ? Because currently I use the link osmandmaps://navigate?lat=${latitude}&lon=${longitude}&z=8 as endpoint and users complain that the navigation is not starting if Osmand has a cold start...
