### ISSUE TITLE
Erroneous rendering of the polygon

### ISSUE THREAD

**Issue by Nine-Tailed** [osmandapp/OsmAnd#16491]
### Description
Osmand draws a polygon inside the ring road.
https://www.openstreetmap.org/way/733835734

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/12549744/219811399-2ea4ac52-d4a3-4b82-8f2b-9aceb9997498.jpg"  width="300" height="auto"/> </th>
 <th><img src="https://user-images.githubusercontent.com/12549744/219811400-e14ebef7-5071-46d6-b2d8-11f47ea0281a.jpg"  width="300" height="auto"/> </th>
  </tr>
</table>  

### Your Environment
OsmAnd Version: OsmAnd~ 4.4.0#14185mqta, Дата выпуска: 2023-02-17
Android version: 12
Device model: poco f3

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14188mqta, Released: 2023-02-19 
4.4.5.7 too

[Map](https://drive.google.com/file/d/18hN0mof51Ru8Zwf6_iXTZ2MRsB1XVcby/view?usp=sharing)

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/219942175-781c13d6-d025-4162-bd51-ef313be4e87f.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>  

https://user-images.githubusercontent.com/104760013/219942178-d30755f5-1297-4dc1-bb93-063fadf868cc.mp4

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14226mqta, Released: 2023-03-09
4.4.6.4
Done

**Comment by xmd5a2** [comment]
We have to revert this fix because polygonal bridges that are not relations was broken by this commit https://github.com/osmandapp/OsmAnd-resources/commit/f3989ea65bfbac43a138082196dec29da5cac6a2
Not clear how to distinguish such linear bridges like in this issue from regular polygonal bridges like this https://www.openstreetmap.org/way/1008159395

**Comment by xmd5a2** [comment]
Most of `highway=footway` + `man_made=bridge` objects have `area=yes` tag

**Comment by xmd5a2** [comment]
@Zirochkabila this footway should be rendered as way not polygon

**Comment by Nine-Tailed** [comment]
> @Zirochkabila this footway should be rendered as way not polygon

@xmd5a2, when will the result be seen?  At the moment, the bug is still present in the latest nightly builds.
