### ISSUE TITLE
OpenGL renderer suppresses street names

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#16543]
Compare these two screenshots:

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/845735/221369036-76725a01-bb17-4b1d-8afa-a31440c91ae6.jpg"  width="300" height="auto"/> </th>
 <th><img src="https://user-images.githubusercontent.com/845735/221369046-8ec0c07f-d6fd-447c-815b-c529c1b50671.jpg"  width="300" height="auto"/> </th>
  </tr>
</table>  

The first one taken with the V1 engine displays many street names of the major road grid (secondary and tertiary highways) like "East Warner Road", "East Knox Road", East Ray Road". Also 2 instances of the State Highway 87 road shield.

On the second screenshot using the V2 engine, almost all that is supressed. Instead there is a notable density of appartment block names etc., much less useful in practice.

**Comment by albansuser** [comment]
Yes, happening for me as well when using the V2 OpenGL engine. I think it has been that way for almost a week. 

My current test version inwhich this is happening is: OsmAnd~ 4.4.0#14204mqta, released: 2023-02-26

**Comment by vshcherb** [comment]
Another example
![telegram-cloud-photo-size-4-5996790058193108186-y_partial](https://user-images.githubusercontent.com/1042025/221589792-a251224c-d97a-4929-ad17-84b59599cfdb.jpg)

**Comment by albansuser** [comment]
The problem seems to be associated with the Height Map function rather the OpenGL v2 as such. 

The problem is resolved by turning Height Map off (with OpenGL v2 on).

**Comment by sonora** [comment]
If you are talking about `Development plugin > Settings > Heightmap`, then not in my case: It's off, and was off when writing up this issue.

**Comment by sonora** [comment]
I am speaking for the master build of when I wrote this up, should have been the Feb 24 build. But have not seen any noticeable change (let alone improvement) all the way through our current 4.4.0 betas up to Mar 6, really. Also had never enabled the Heightmap feature on that test device, nor ever downloaded one on it. So it's really weird ...

**Comment by sonora** [comment]
Here's the new status for comparison. At first sight much improved, but still not quite where V1 is?

![Screenshot_20230423-204821_OsmAnd~](https://user-images.githubusercontent.com/845735/233859247-548878d0-015c-4e0c-9f06-25778bfe2bce.jpg)

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.5.0#35859m, Released: 2023-04-27
4.4.8.2
Difference is still there

<table style="width:100%">
  <tr>
    <th>V1</th>
    <th>V1</th>
    <th>iOS</th>
  </tr>
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/235112595-9adc9a06-c0fe-47a3-82a2-e7158ab73117.jpeg"  width="300" height="auto"/> </th>
<th><img src="https://user-images.githubusercontent.com/104760013/235112598-34966a6f-405e-4d84-828f-90708d05b01a.jpeg"  width="300" height="auto"/> </th>
<th><img src="https://user-images.githubusercontent.com/104760013/235112992-232fa2ed-daf2-409b-ae0a-4816c4b3b82b.jpeg"  width="500" height="auto"/> </th>
  </tr>
</table>
