### ISSUE TITLE
Wikipedia articles keep getting listed under updates even after downloading them

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/OsmAnd#17243]
Recently the OsmAnd Wikipedia map files have been updated (2023-05-18). After downloading them, they still keep getting displayed at Download maps / Updates. Is there something wrong with the timestamps?

OsmAnd 4.5.0.

**Comment by pebogufi** [comment]
me too

**Comment by albansuser** [comment]
Same here.

**Comment by Rowin63** [comment]
The same happens with some maps (Andorra and Deutschland_Bayern_Schwaben for example)

**Comment by MrHappy** [comment]
This seems to have fixed it for all but one map for me.
Even after removing and reinstalling the map for The Netherlands - Zuid-Holland it is still listed under updates...

**Comment by Rowin63** [comment]
Two maps here (removing did not help here too): Andorra and Deutschland_Bayern_Schwaben

**Comment by vshcherb** [comment]
Will be retested

**Comment by MrHappy** [comment]
Tested and for me it is fixed!
Thanks!

**Comment by vshcherb** [comment]
Please try in 15 min

**Comment by mikehgentry** [comment]
No change I'm afraid.

**Comment by Rowin63** [comment]
Same here in 4.5.0
Mini Map is "grey", after downloading it changes to "green" but the date remains the same (17.5.).
After closing and restarting the app, it's "grey" again

**Comment by Rowin63** [comment]
Not here. Still the same like before (download disappears at a restart).
In fact I don't mind about this, just wanted to mention it 😉

**Comment by prallo** [comment]
Still not fixed
Thailand Map

**Comment by prallo** [comment]
https://github.com/osmandapp/OsmAnd/assets/20041525/13e70ab5-5ec6-4d10-863c-7f475f2fcc94

**Comment by albansuser** [comment]
... also with New Zealand and New York city maps.

**Comment by sm4rk0** [comment]
I've got 9 country maps and all of them are orange (outdated) with their date being June 1, while the "newer updates" show June 3. I think the issue is within the server metadata showing the wrong "last modified date" for maps from June 1 as June 3.
There's no issue with World overview maps (standard and mini) because they are from May.

**Comment by prallo** [comment]
In updates, osmand puts June 3 and in local June 1. That's why he thinks there's an update again. But it must just be a server date error.

**Comment by scaidermern** [comment]
Same for me. OsmAnd 4.5.1.

**Comment by vshcherb** [comment]
> Still not fixed

That's another issue unrelated to this one, I will take a look. Hopefully should be resolved it will be in 2-3 hours
