### ISSUE TITLE
Buoys not shown or off position with OpenGL render engine

### ISSUE THREAD

**Issue by quantenschaum** [osmandapp/OsmAnd#17413]
### Description

Seamarks like buoys are not shown or are drawn off position when using render engine 2 (OpenGL).

### Steps to reproduce

- enable render engine 2
- zoom in on some seamarks
- use `https://tiles.openseamap.org/seamark/{0}/{1}/{2}.png` as semi transparent raster overlay for comparison or switch between renderers, make screenshots and compare

### Actual result

Some buoys are missing, many are drawn out of position.

### Expected result

All buoys are shown (according to zoom level) and they are draw in their correct position.

### Your Environment
OsmAnd Version: 4.4.7
Android version: 13
Device model: Nokia X20

**Comment by quantenschaum** [comment]
![osmand12](https://github.com/osmandapp/OsmAnd/assets/3985599/29b19ceb-205b-4bd3-944c-bdf84a711b42)

renderer 1 vs renderer 2

![renderer-1-vs-2](https://github.com/osmandapp/OsmAnd/assets/3985599/3963812c-b66b-4e17-bf92-444d2b06358e)

renderer 2 with OpenSeaMarks overlay

**Comment by quantenschaum** [comment]
Some buoys are out of position compared to the OSM raster overlay due to recently updated OSM data, that is not yet present in OsmAnd (blue cross), but others are just missing or out of position (red circles).

You can also see that the positions are wrong, when you look at the placement of the buoys relative to fairway (bright green).

![engine-1-vs-2](https://github.com/osmandapp/OsmAnd/assets/3985599/79a60a69-0597-44c7-b092-551fd0983ae5)

**Comment by Zirochkabila** [comment]
[Maps here](https://drive.google.com/file/d/1mjsSdwLl5BBnAxzLgB8fZpN2l1Bduec8/view?usp=sharing)

**Comment by zipav** [comment]
### Coordinates: 
53.34378 5.20543

### Steps to reproduce: 
Choose OpenGL map rendering engine → Open Netherlands Frisia map  → choose Boat profile  → overlay OpenSeaMap: https://tiles.openseamap.org/seamark/{0}/{1}/{2}.png  → find coordinates  

![image](https://github.com/osmandapp/OsmAnd/assets/123936521/0a1e84e5-334a-44d8-ba0b-70b079599dcf)
![image](https://github.com/osmandapp/OsmAnd/assets/123936521/d8584fe8-ba15-416f-b484-96d3c4f32de6)


OsmAnd Nightly 4.5.0#196m, released: 2023-06-13

**Comment by xmd5a2** [comment]
"Buoys not shown" is fixed.
Displaced icons requires some efforts in OpenGL engine. When `shield` added to icon then whole icon becomes displaced vertically. This can be tested if [this](https://github.com/osmandapp/OsmAnd-resources/blob/master/rendering_styles/nautical.render.xml#L2307) `apply` is commented out. [Place to test](http://www.openstreetmap.org/#map=19/45.682117/36.50398) (new synthetic_test_rendering map required).
```xml
				<apply>
					<case additional="seamark:light:colour=white" shield="light_white_shield"/>
					<case additional="seamark:light:colour=red" shield="light_red_shield"/>
					<case additional="seamark:light:colour=green" shield="light_green_shield"/>
					<case additional="seamark:light:colour=yellow" shield="light_yellow_shield"/>
					<case additional="seamark:light:colour=blue" shield="light_blue_shield"/>
					<case additional="seamark:light:colour=orange" shield="light_orange_shield"/>
					<case additional="seamark:light:colour=white;green" shield="light_whitegreen_shield"/>
					<case additional="seamark:light:colour=red;green" shield="light_redgreen_shield"/>
					<case additional="seamark:light:colour=white;red" shield="light_whitered_shield"/>
					<case additional="seamark:light:colour=violet" shield="light_violet_shield"/>
					<case additional="seamark:light:2:colour" shield="light_violet_shield"/>
				</apply>
```
Engine v1:
![Screenshot_2023-06-23_10-43-27](https://github.com/osmandapp/OsmAnd/assets/5829014/b1575f04-b73f-4fb4-9e38-2535b6f74f63)
OpenGL engine:
![Screenshot_2023-06-23_10-43-38](https://github.com/osmandapp/OsmAnd/assets/5829014/a4114f99-bcc5-4679-bdf9-152e65cf970d)

**Comment by quantenschaum** [comment]
Nice! What is this "shield"? The drop shaped light indicator? When I remove the `apply` section, then indicators disappear and the buoys are displayed in correct position. It is interesting that the light indicator is still shown for beacons and light houses, but there it does not change their position.

Something I noticed is then when zooming in, the background (blue water) disappears and reappears when zoomed in further.
