### ISSUE TITLE
Footway preferred over cycling way

### ISSUE THREAD

**Issue by Discostu36** [osmandapp/OsmAnd#17532]
## Description

I have the "avoid unpaved ways" and "avoid footways" options activated in bicycle routing. This leads to [this footway](https://www.openstreetmap.org/way/26675353) being preferred over [this designated cycling path](https://www.openstreetmap.org/way/27142979) in bicycle routing. 

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/30999326/357d69b5-a6ad-416e-b811-a50a5b6a5963"  width="300" height="auto"/> </th>
  </tr>
</table>

If I turn off the "avoid unpaved ways" rule, the correct route is chosen.

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/30999326/556f5166-0b04-41e4-8112-ff303dd3316a"  width="300" height="auto"/> </th>
  </tr>
</table>

Both ways have `surface=paving_stones`.

### How to reproduce

Bicycle routing from 54.31530° N, 10.12210° E to 54.31456° N, 10.12231° E with these settings:

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/30999326/4339b42d-724c-467a-8ead-3307a7f62f42"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/30999326/9787ab5a-d426-49b9-9e69-3989bf4800fa"  width="300" height="auto"/> </th>
  </tr>
</table>

Map data: Schleswig-Holstein 2023-06-01 with Osmand Live. 

### Actual result

Footway is preferred over path with bicycle=designated with same surface.

### Expected result

Cycling path should be preferred.

**Environment**
OsmAnd Version: 4.3.12
Android/iOS version: Android 12
Device model: Fairphone 4

**Comment by scaidermern** [comment]
> Both ways have `surface=paving_stones`.

Not exactly. The [avoided way](https://www.openstreetmap.org/way/27142979) has `cycleway:surface=paving_stones` and `footway:surface=paving_stones`. So maybe this is because OsmAnd doesn't support these tags and thus has no knowledge about the surface?

**Comment by Discostu36** [comment]
Thanks for the hint. I've changed that and will have a look in a few hours if the routing is fixed. If yes, I'll add a new issue as a feature request that, for bicycle routing, `cycleway:surface` should be considered.

**Comment by Discostu36** [comment]
It was a good idea, but not the source of the problem. The avoided way now as `surface=paving_stones`, but the routing is still via the footway.

**Comment by Discostu36** [comment]
The problem is a different one:

https://github.com/osmandapp/OsmAnd-resources/blob/master/routing/routing.xml#L1675-L1678

````xml
            <if param="avoid_unpaved">
                <select value="0.3" t="highway" v="track"/>
                <select value="0.2" t="highway" v="path"/>
            </if>
````

The parameter doesn't do what it says on the cover. It doesn't check for surfaces, but it does only penalize tracks and paths. The behaviour should be changed, or the option should be renamed to "avoid paths and tracks".

**Comment by scaidermern** [comment]
> The problem is a different one:
> 
> https://github.com/osmandapp/OsmAnd-resources/blob/master/routing/routing.xml#L1675-L1678
> 
> ```
> <if param="avoid_unpaved">
>     <select value="0.3" t="highway" v="track"/>
>     <select value="0.2" t="highway" v="path"/>
> </if>
> ```

This is indeed strange and misleading - and wrong. Any way can be unpaved. In contrast, tracks and path can be paved. So the current implementation is just plain wrong.

**Comment by vshcherb** [comment]
This is mostly true for tracks / paths allowed for vehicles. Anyway will be open for suggestions especially if we can test the idea somehow in general

**Comment by scaidermern** [comment]
> Anyway will be open for suggestions especially if we can test the idea somehow in general

Which kind of suggestions?

This option should check the surface tags. A paved road has surface asphalt, concrete, concrete:plates, concrete:lanes, paving_stones, sett, cobblestone, unhewn_cobblestone, metal, wood, tartan, ...

See https://taginfo.openstreetmap.org/keys/surface#values

**Comment by yuriiurshuliak** [comment]
In an attempt to reproduce this error, I entered the same settings as the user and navigated from point to point according to their coordinates. Currently, this bug is no longer reproduced. You can view it in our web version:
https://test.osmand.net/map/?start=54.315300%2C10.122100&end=54.314560%2C10.122310&mode=bicycle#18/54.31495/10.12264


<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/77f2e53f-ffbf-43a9-8918-5a50c0a4d90f"  width="700" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/ec3ba13b-ed79-4a06-bc6a-369661953b3f"  width="700" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/fd6f8370-caf0-46d0-b533-f0e15f7c244b"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/a6d587a1-af2c-4ce4-aee1-536e9bce7e04"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/d0bf9236-3387-4d54-9bd7-faa58c25e2bd"  width="1000" height="auto"/> </th>
  </tr>
</table>

**Comment by Discostu36** [comment]
The web version doesn't work for me, route calculation doesn't finish. But you have chosen a different driving style than I did.

**Comment by vshcherb** [comment]
Indeed cycling route has same cost - setting Use elevation data

- https://osmand.net/map/?start=54.315157,10.122319&end=54.314560,10.122310&type=osmand&profile=bicycle#20/54.31497/10.12281 (37 seconds)
- https://osmand.net/map/? start=54.315103,10.122343&end=54.314560,10.122310&type=osmand&profile=bicycle#20/54.31497/10.12281 (33 seconds)


It's strange cause cycling should have higher priority than footway, elevation data unlikely to influence that much

**Comment by yuriiurshuliak** [comment]
The bug has been resolved. After selecting the bicycle profile with all the specified settings, the navigation now correctly prefers the bike path when traveling from the starting point at coordinates 54.31528, 10.12205 to the destination point at coordinates 54.31456, 10.12230. You can access the preferred bike path using this link:: [OpenStreetMap Bike Path](https://www.openstreetmap.org/way/27142979).

For a web version of the navigation, you can visit the following link, which includes the specified start and finish coordinates, as well as the bicycle profile settings: [Web Version Navigation](https://test.osmand.net/map/?start=54.315280,10.122050&finish=54.314565,10.122295&type=osmand&profile=bicycle&params=bicycle,short_way,driving_style_safety,driving_style_balance:false,avoid_unpaved,avoid_stairs,avoid_borders,avoid_footways,avoid_cobblestone,height_obstacles#18/54.31498/10.12090).

OsmAnd~ 4.6.0#881m, released: 2023-10-17

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/5d932986-f666-45d1-ad57-f084fa0d417e"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/1b3551e7-642a-4021-beac-a39f80ffad5f"  width="700" height="auto"/> </th>
  </tr>
</table>

**Comment by Discostu36** [comment]
Thanks!

**Comment by xmd5a2** [comment]
Looks like this is no longer reproducible ever with [reverted commit](https://github.com/osmandapp/OsmAnd-resources/commit/941821739b28c94ab1d99fb3a17e9b8b66a5db24)
![изображение](https://github.com/osmandapp/OsmAnd/assets/5829014/88438330-72a9-4858-b2f6-4ac125188d34)

**Comment by yuriiurshuliak** [comment]
Currently, routes using the specified parameters are calculated identically.  It is only worth noting that when the "avoid unpaved roads" option is enabled, it is calculated correctly in iOS, but in Android the road is calculated via footway.
However, if you turn off this option, the route will be calculated correctly.

OsmAnd~ 4.6.0#1160m, released: 2023-12-05

<table style="width:100%">
  </tr>
  <tr>
    <th>Android</th>
    <th>iOS</th>
    <th>Web</th>
  </tr>
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/ebaced80-330f-4664-94bd-9b604bb88e51"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/26ba3701-79ca-4730-ad3f-4c184cd01a2e"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/5e21047f-f481-433e-acbc-fbbd70046adb"  width="700" height="auto"/> </th>
  </tr>
</table>

**Comment by Discostu36** [comment]
Ok, so the original bug still exists as reported in the original post. @xmd5a2 could you reopen?

**Comment by DmitryAlexei** [comment]
Can confirm, that with *Avoid unpaved roads* enabled, the route is calculated in a wrong way.

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/2bccf695-45f9-4112-94cb-f73e6070f593"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by xmd5a2** [comment]
I think it is fixed finally

**Comment by RZR-UA** [comment]
I can not reproduce the bug with nightly version of OsmAnd Android:

![Image](https://github.com/osmandapp/OsmAnd/assets/90444451/b4f22bdb-0d45-4bd8-b7f1-e62797b5b1bb) ![Image](https://github.com/osmandapp/OsmAnd/assets/90444451/394b862f-17c1-4024-95c9-f432a2702f8e)

![Image](https://github.com/osmandapp/OsmAnd/assets/90444451/dc35a59d-84b5-4eef-8f4d-148acb527436)

**Comment by yuriiurshuliak** [comment]
The bug has now been fixed. On the last nightly build, the road builds correctly regardless of the "avoid unpaved roads" option enabled.

OsmAnd~ 4.7.0#1233m, released: 2023-12-18
