### ISSUE TITLE
Inconsistent rendering of cycleway/cycleway:both=lane/track

### ISSUE THREAD

**Issue by matthijskooijman** [osmandapp/OsmAnd#17690]
## Description
It seems that the cycleway property is not rendered consistently, or at all in the bicycle view of OsmAnd and Topo renderer.

### How to reproduce

[This way](https://www.openstreetmap.org/way/466719770) has `cycleway=lane` and renders as expected with cycleways on both sides of the road (except that the cycleways are a bit close to the road, and are hard to see):

![image](https://github.com/osmandapp/OsmAnd/assets/194491/3d5f5e17-dee3-414f-8ee0-c6103028dbeb)

However, `cycleway:both=lane/track` and `cycleway=track` are all rendered as a single centered line instead of lines at both sides of the road.

[This way](https://www.openstreetmap.org/way/273115790) has `cycleway=track`:

![image](https://github.com/osmandapp/OsmAnd/assets/194491/a6d4d05d-ad5b-49b6-b9e7-3686b1b02967)

[This way](https://www.openstreetmap.org/way/634201191) has `cycleway:both=track`:

![image](https://github.com/osmandapp/OsmAnd/assets/194491/93b7d95c-97b6-4d36-88a2-3f6d3aad379e)

[This way](https://www.openstreetmap.org/way/243053274) has `cycleway:both=lane`:

![image](https://github.com/osmandapp/OsmAnd/assets/194491/121000b2-5db9-434f-8e45-55d6c89a46ae)

![image](https://github.com/osmandapp/OsmAnd/assets/194491/31cf57e6-7387-490b-b132-fa40e5c0cc9c)

With the Topo rendering style, the same problems exist, except that `cycleway=lane` is *also* rendered as a single center line instead of lines at the sides (but maybe two-line rendering was not implemented yet there).

### Actual result

See above.

### Expected result

Render as one blue line on each side of the road.

### Responsible code
At first glance, [this bit of rendering XML](https://github.com/osmandapp/OsmAnd-resources/blob/197d46ff0f330de64f2235e41293536936991ba6/rendering_styles/default.render.xml#L10576-L10689) or the OsmAnd renderer seems relevant. It looks like all cases described above are handled, but this uses custom osmand tags like `osmand_cycleway` and `osmand_cycleway_trunk_left`. This makes me suspect that drawing two lines needs some additional processing in when generating the OBF file?

I tried to have a look in the OBF file, but couldn't get the tooling to work (AFAIU OsmAndMapCreator should be able to create and inspect (small) OBF files, and maybe even preview rendering, but I could not get that to work...).

### Additional considerations

It might be worth considering to, in cycling mode, render bicycle paths more clearly, and maybe distinguish cycle lanes from cycle tracks. For example, using the dark blue color used by Topo, or the same color, thicker line and solid/dashed lines to distinguish track/lane used by the [CyclOSM layer](https://www.openstreetmap.org/#map=15/50.6347/6.0284&layers=Y):

![image](https://github.com/osmandapp/OsmAnd/assets/194491/5387a701-0289-4630-beec-be1a0a24b498)

**Environment**
OsmAnd Version: Nightly 4.5.0#455m, 2023-07-22
Android/iOS version: 9
Device model: Galaxy Tab A 8" 2019 SM-T295

**Comment by xmd5a2** [comment]
`cycleway:both=lane/track` and `cycleway=track` rendering was fixed but it can be improved through. New maps required.
`cologne-government-region` will be regenerated after couple of hours.

**Comment by DmitryAlexei** [comment]
OsmAnd~ 4.6.0#634m, released: 2023-08-18
Downloaded cologne-government-region map

1. Cycleway=lane, lanes=2  is good to see now, it is displayed not close to road https://www.openstreetmap.org/way/466719770
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/aee9f837-9ca1-4f42-bbdb-058a0210c7f2"  width="300" height="auto"/> </td>
  </tr>
</table>

2. cycleway:both=lanes https://www.openstreetmap.org/way/243053274 (50.7968830, 6.4634477) is rendered as a single centered line
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/a366b74d-0b01-46e6-8e35-62fe3f227a47"  width="300" height="auto"/> </td>
  </tr>
</table>

3. cycleway:both=track https://www.openstreetmap.org/way/634201191 (50.8079840, 6.4922561) is also rendered as a single centered line
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/ce432f48-e28b-44b7-8db0-7a4a9b191324"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by DmitryAlexei** [comment]
https://github.com/osmandapp/OsmAnd/issues/18052 follow up of this issue

**Comment by matthijskooijman** [comment]
Actually, #18051 and #18052 are followups for the "Additional considerations" section of this issue. The main point of this issue is still unfixed, so I think this issue should be re-opened.

**Comment by vshcherb** [comment]
Todo @xmd5a2 

OsmAnd~ 4.6.0#698m, released: 2023-08-30
- Downloaded cologne-government-region map
- Bicycle profile enabled

1. Cycle lanes (cycleway:both=lanes) https://www.openstreetmap.org/way/243053274 (50.7968830, 6.4634477) are rendered as a single centered line
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/a366b74d-0b01-46e6-8e35-62fe3f227a47"  width="300" height="auto"/> </td>
  </tr>
</table>

2. Cycle tracks (cycleway:both=track) https://www.openstreetmap.org/way/634201191 (50.8079840, 6.4922561) are rendered as a single centered line
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/ce432f48-e28b-44b7-8db0-7a4a9b191324"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by xmd5a2** [comment]
@vshcherb I don't see any issue at all. What maps do you use?
![Screenshot_2023-09-04_10-29-01](https://github.com/osmandapp/OsmAnd/assets/5829014/1e12ed5b-e213-4d67-a3d5-c39177d140c9)
![Screenshot_2023-09-04_10-29-59](https://github.com/osmandapp/OsmAnd/assets/5829014/c87af8c9-7108-41bf-8ca0-ef3e933a1f1c)

**Comment by vshcherb** [comment]
Fixed in new maps

**Comment by matthijskooijman** [comment]
Hm, I had redownloaded the maps five days ago and it did not seem fixed then, but I now noticed I was still running 4.4.7 (somehow F-droid did not show newer versions as available), so maybe it was that. I just upgraded to 4.5.8 and downloaded the maps again, and now it looks good for me too. Thanks for following up, sorry for the noise :-)
