### ISSUE TITLE
Let osmand announce directions

### ISSUE THREAD

**Issue by bonanza123** [osmandapp/Osmand#1786]
I've seen that there is an option to enable the announcement of which street names to take when approaching a crossing. However, in most cases the street signs only show the direction (e.g. City) the street points to. It would be nice to have also an announcement for this.

**Comment by maraf24** [comment]
destination=* keys are already used in announcement, at least for ttsconfig with "version(103)."

**Comment by bonanza123** [comment]
To which osmand version does this config correspond? I'm using the latest build from fdroid and haven't seen any direction announcement for a couple of months.

**Comment by maraf24** [comment]
The support for version 103 of ttsconfig has been added to osmand quite long ago and your latest build surely can handle it. 
The current ttsconfig for English language can be viewed here: https://github.com/osmandapp/OsmAnd-resources/tree/master/voice/en 
'destination' is used there for tts text generation provided the road has no name.

**Comment by bonanza123** [comment]
Ahh, so the destination (city) is not announced when the road name is known? Then it would be nice to have an option to also enable the destination announcement even if the road name is known :-)

**Comment by maraf24** [comment]
You can edit config file and thus change its behaviour. It's text file located in /osmand/voice/en-tts/_ttsconfig.p
You need to find these lines (first and third are commented out):
```
% cut_part_street(voice([Ref, Name, Dest], [_CurrentRef, _CurrentName, _CurrentDest]), _).
cut_part_street(voice([Ref, '', Dest], _), Concat) :- atom_concat(Ref, ' ', C1), atom_concat(C1, Dest, Concat).
% cut_part_street(voice(['', Name, _], _), Name). % not necessary
cut_part_street(voice([Ref, Name, _], _), Concat) :- atom_concat(Ref, ' ', C1), atom_concat(C1, Name, Concat).
```
Replace with these:
```
cut_part_street(voice([Ref, Name, ''], _), Concat) :- atom_concat(Ref, ' ', C1), atom_concat(C1, Name, Concat).
cut_part_street(voice([Ref, _, Dest], _), Concat) :- atom_concat(Ref, ' ', C1), atom_concat(C1, Dest, Concat).
```
This way 'destination' will have precedence over 'name'.

**Comment by bonanza123** [comment]
Thanks, but I guess that some kind of in-app configuration of this would be really nice. I guess that on motorways one would maybe prefer to hear the destination city together with the name (e.g. something like "turn right in X meters on Axx towards Berlin" ) while on normal streets only the name would be useful.

**Comment by vshcherb** [comment]
Will assign to our main maintainer of it :)

**Comment by Barrocas** [comment]
Agreed, at least in my country, the Highway exits display the Destination, not the street names.
Street names are really usefull for searching adresses and POI, but although interesting to hear while navigating (and sometimes quite long), they are not really usefull in navigation voice announcements for the direction to take on an intersection.
I can only see the street name if I search for a small sign placed on that street (or if I know that street before), but the indication signs on the roads are generally named with the Destination sign.

**Comment by sonora** [comment]
Tricky question. From my personal experience the following is true:
- While in Europe specifying a destination is much more common, in the US the use of highway names is sometimes more prevalent (as the US highway numbering system is also more systematic)
- In most countries smaller roads (residential to county roads) tend to use a destination-based direction system, while more important highway types (state routes, motorways) tend to increasingly use highway references.

marat24 has above pointed out the correct lines in my code, and made the correct suggestions we can try. I will commit a version for the English tts and then we can test that vs. what I had so far.

Let us try to work out an optimized solution without an additional setting, as it would only complicate the app configuration without much hope of improving these very situation-specific issues.

**Comment by bonanza123** [comment]
@sonora thanks for your feedback and willingness to implement this. Maybe also some experiences from my side:
* When I've been to Portugal some time ago for vacations, I had to use many highways and osmand was just announcing the name of the highway like "route 123" which wasn't very helpful because I only knew roughly which cities where connected by that highway but was totally unaware about the highway numbering
* In Germany I have faced often the situation that  there is fork or drive-up where the same highway is split and going into opposite directions and knowing the city in which it directs would be helpful 

In general I also agree that announcing the direction / cities is most likely only helpful for highways

**Comment by Barrocas** [comment]
It seems that Osmand reads the tags in this order of importance:

1) 'ref'
2) 'name'
3) 'destination'

if it has tag 1, it doesn't read 2, if it has tag 2, it doesn't read
3? (I may have mixed 2 and 3 order here... not sure)

The 'destination' tag is often not read by TTS, but I do see that info
displayed in the top center screen for direccions.

-- 
Cumprimentos,
D.er Hugo Barrocas

**Comment by sonora** [comment]
Let's try latest nightly. Current setup now as discussed: Ref is always used (when available), but regardless (and in addition) Dest is now preferred over Name, and Name only used if no Dest available.

**Comment by Barrocas** [comment]
Do I have to use the English TTS? 
At least in Portuguese I heard no changes, it reads ref and displays destination.

**Comment by bonanza123** [comment]
@Barrocas I guess german and english TTS ( see https://github.com/osmandapp/OsmAnd-resources/commit/fec3b6f668914ab3582ce768cbb0c58ad06e04dd )

**Comment by Barrocas** [comment]
Tested it.

With English TTS, osmand shows and reads ref and destination, works great!

With Portuguese TTS (not modified), it shows both, but only reads out the
ref, not as good.


-- 
Cumprimentos,
D.er Hugo Barrocas

**Comment by sonora** [comment]
I have now upgraded all or version 103 tts files with the fix, because I think it works ok.

Unfortunately, pt is still version 102 and does not support this. Could you maybe test pt-br. If that one is ok, I could more easily create a version 103 pt file from that.

Overall: I think the original issue raised is solved in principle (pending the implementation in pt.) The major shortfall we still have is to maybe mask the Ref announcements by highway type, maybe according to a pattern like this:
- motorway, trunk, primary: ANNOUNCE Ref 
- secondary (debatable, depends on country), tertiary, road, residential, etc.: IGNORE Ref
- hiking/biking paths/networks etc.: ANNOUNCE Ref

We currently have no mechanism in place to support this, but it seems the only way forward I can imagine we improve from here.

Best, Hardy

**Comment by Barrocas** [comment]
At least in my country, I see no problem with the ref being always
announced.

I'll test the PT-BR tts to see how it goes.


-- 
Cumprimentos,
D.er Hugo Barrocas

**Comment by Barrocas** [comment]
I noticed that the PT tts was updated to version 103, thanks.
I'm testing it, and I believe there are some higways with 'destination' that are not being read by tts or displayed in the screen, but I have to test some more to clear that out...

**Comment by Barrocas** [comment]
Other user asking questions about this topic:
https://groups.google.com/forum/m/#!topic/osmand/6syoCkYvQAA

I'm now using the latest build, with PT-TTS, it's working better, but I
noticed some roads are still not working as expected (only 'ref' displayed
and announced, not 'destination'),  while other nearby roads with similar
tags get announced as expected.


-- 
Cumprimentos,
D.er Hugo Barrocas

**Comment by Barrocas** [comment]
Working as expected on today build, displays and announces 'ref' followed by 'destination'.

**Comment by dan980** [comment]
In Europe most link roads are tagged this way:

```
highway=trunk_link (or motorway_link)  
oneway=yes  
maxspeed=40  
destination=Cagliari  
```

Osmand 2.4.7 (with Italian TTS 1.03) does **not** announce the destination at all.  You can test on the main road in Sardinia (SS131).
