### ISSUE TITLE
Osmand crashes when try to store settings/favourites to file

### ISSUE THREAD

**Issue by bp4willi** [osmandapp/OsmAnd#18456]
https://github.com/osmandapp/OsmAnd/assets/149273357/9fbe8a06-e713-493e-bbc7-82cb3c50430f

### Description

Osmand crashes when try to store settings/favourites to file.
App 4.5.10 on android 8.1
I sent many crash reports after app restarts. Should be available on your servers.

### Steps to reproduce

General settings/ backup to file
Screen freezes 
App crashes after minutes

Screen recording available.
How to attach in github ??

Ps. Same behaviour when try to save ro cloud.

### Actual result

Screen freezes
App crashes

Crash report sent via email after app restart

### Expected result

Selection mask for settings or favourites items
File folder selection

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: 4.5.10
Android/iOS version: 8.1
Device model: gigaset 280
Crash-Logs: sent to osmand support in email
```

**Comment by DmitryAlexei** [comment]
Cannot reproduce on OsmAnd~ 4.6.0#934m, released: 2023-10-29 and OsmAnd 4.5.10, 
Samsung note 20, Android 13

@bp4willi how many favorites / tracks do you have active on map? OsmAnd still crashes when you disable all tracks / favorites?

**Comment by bp4willi** [comment]
Hi Dmitry,Thanks for checking.Even if I disable display for all favourites and tracks, the file backup process crashes.Pls note, I have about 900 tracks and probably more than 2000 favourites in the App.What i discovered.....when i start the backup to file process, screen freezes, but..sometimes, when I toggle between Osmand and other app, and return to Osmand, it displays next screen for settings/favourites/maps selection.....and then ,sometimes, its possible to select items, or screen freezes again.....and finally app crashes.....bug report sending triggered at next restart of app.This "hidden" next screen is bit weird, and possibly gives you indication whats going wrong.Is their any extended app internal logging, which i could switch on, to help find the bug?Regards bp4willi --Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 30.10.23, 00:10 schrieb DmitryAlexei ***@***.***>:

   
  Cannot reproduce on OsmAnd~ 4.6.0#934m, released: 2023-10-29 and OsmAnd 4.5.10, Samsung note 20, Android 13 
  @bp4willi how many favorites / tracks do you have active on map? OsmAnd still crashes when you disable all tracks / favorites?

**Comment by DmitryAlexei** [comment]
@bp4willi Could you please try beta version from Google play? 
This can be OOM crashes. Some of them have already been fixed in 4.6 beta

**Comment by bp4willi** [comment]
Hi Dmitry, 
I tried beta version 4.6.3 - regret, no change.
Osmand crashes when try to backup settings in file.
Also the change of routing memory in the developer settings doesnt change anything.
I do attach screenshots from the memory settings section.
I also attach screenshot of that bit scrambled view of selection page for backup, when i toggle between apps and return to Osmand.
Settings plus favourites are about 76MB. Too much for Osmand ??
![Screenshot_20231031-151706](https://github.com/osmandapp/OsmAnd/assets/149273357/80713ddd-d6ae-419a-9e38-52af47cac3c5)
![Screenshot_20231031-150656](https://github.com/osmandapp/OsmAnd/assets/149273357/e13aecd5-8a68-4e4f-a7ce-db23b996c7c9)
![Screenshot_20231031-151620](https://github.com/osmandapp/OsmAnd/assets/149273357/eea0775a-7469-4ad8-ba1c-1c724f48330d)
![Screenshot_20231031-150726](https://github.com/osmandapp/OsmAnd/assets/149273357/e1d86778-9ca0-4792-951b-294f10dea42f)

**Comment by DmitryAlexei** [comment]
Still cannot reproduce this issue on Samsung SM-A510f device (Android 7, OsmAnd 4.5.10 and OsmAnd~ 4.6.0#997m, released: 2023-11-08 installed in internal memory): Successfully managed to create 510mb export file

@bp4willi does your OsmAnd installed in internal memory?

**Comment by bp4willi** [comment]
@DmitryAlexei yes, the OSMand app is installed in internal memory ; but the favourites and maps are installed on the SD card !  
Both have sufficient space for the 75MB backup volume of settings + favourites.

**Comment by DmitryAlexei** [comment]
Tried to reproduce this issue using Samsung A5 (2016) device running on Android 8 with external SD card. 
1. Every time *Data storage folder* was changed to *External storage 2*, OsmAnd 4.5.10 crashed.
2. So we transferred the crash logs to developers, and this issue was successfully resolved in the latest nightly builds (see https://osmand.net/docs/versions/nightly_versions#nightly-builds).
3. On OsmAnd~ 4.6.0#1094m, released: 2023-11-26 I managed to change *Data storage folder* to *External storage 2* and export all my data into file (see screen capture). 
4. Thus we can conclude, that issue is no longer reproducible. The fix will be available in the next release (hopefully by the end of this year). You can also try nightly build and see, if it is working for you.

https://github.com/osmandapp/OsmAnd/assets/116079541/5bea58dd-9240-4fbf-9f6b-ebc8d92a875a

**Comment by bp4willi** [comment]
@DmitryAlexei thanks for this promising positive news.
I just wonder why release 4.6.0#1094 was released 26.11. , on which you successfully testet the export.
While i have version 4.6.6 released 15.11. and the error still exists.
I'll then wait for next , corrected main line release, and hope the correction gets included.

**Comment by DmitryAlexei** [comment]
@bp4willi thank you for your question. You are right about OsmAnd version, it was OsmAnd~ 4.6.0#1108m, released: 2023-11-28.
Issue was fixed by this commit https://github.com/osmandapp/OsmAnd/commit/e3c2c8b700bbca6ccddbcfd32db22e01580d85d9
