### ISSUE TITLE
Live updates extremely slow down the app

### ISSUE THREAD

**Issue by Sesivany** [osmandapp/OsmAnd#20120]
### Description

It started appearing at the weekend. First live updates made the app crash, next day it improved, the Android app no longer crashes, but is extremely slow, to the point that it's impossible to use, rendering of new tiles when you move in the map basically stops. I have to go to the settings, disable live updates, delete them, and restart the app to fix it.
It's interesting that it seems to only occur with the maps of the Czech Republic. When I do live updates on the maps of Slovakia, it works.

### Steps to reproduce

1. Download offline maps of the Czech Republic.
2. Enable and download live updates.

### Actual result

The app gets extremely slow, the map basically doesn't redraw when you move around.

### Expected result

Live updates shouldn't impact performance and stability of the app.

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version:
Android/iOS version:
Device model:
Crash-Logs: ?
```
[logcat.log](https://github.com/user-attachments/files/15883412/logcat.log)
[exception.log](https://github.com/user-attachments/files/15883413/exception.log)

**Comment by yuriiurshuliak** [comment]
Yes, you're absolutely correct. There have been instances of vandalism on OSM. We are in the process of resolving this issue and recommend that you clear the live updates and reload them.

**Comment by thuryn** [comment]
I have the same problem, I can see unususal unreal road - see the pictures. I need to switch the updates off.
![photo_2024-06-19_22-03-50](https://github.com/osmandapp/OsmAnd/assets/11028346/c89a100b-ad88-4274-8b3b-6c0c041631b9)
![photo_2024-06-19_22-04-05](https://github.com/osmandapp/OsmAnd/assets/11028346/3f6de913-e211-4872-85c6-1f2fb138b6af)

**Comment by vshcherb** [comment]
The issue has been fixed yesterday please redownload live updates

**Comment by thuryn** [comment]
I'm not sure. I delete the map, switch na updates on again and the same result

**Comment by thuryn** [comment]
I removed the maps screenshots for safety reasons

**Comment by Sesivany** [comment]
@vshcherb, it's definitely not fixed for me. It somewhat improved. Now it's not extremely slow and impossible to use, but "only" very slow and very hard to use.

**Comment by UnlacedFountain** [comment]
Not fixed here either and still not getting the last ~4 days of changes from OSM. Some issue with CDN caching?

**Comment by shadow-identity** [comment]
> The issue has been fixed yesterday please redownload live updates

Was it the fix on the live updates back end side (so the osmand app update is not needed), or we have to update the app to have it fixed?
