### ISSUE TITLE
Night build - 'light' & 'dark' app theme issue

### ISSUE THREAD

**Issue by Barrocas** [osmandapp/Osmand#2064]
On current and latest builds, after the changes in the position colouring, the app theme is not working properly.

I have always had the 'dark' theme selected, but now during daytime, the menu, navigation menu, poi info, etc have the 'light' white theme, and some only turn to the 'dark' theme at night, when colors change.

**Comment by crimean** [comment]
As it was designed: theme of the map controls like: drawer, context menu, route preparation screen, waypoints screen, etc... depends on map's theme, but not app's theme.

**Comment by Barrocas** [comment]
So if I still prefer a 'dark' theme everywere, I have to use the 'light'
theme anyway, at least during the daytime? Not nice.
What happened to the usual user's choice?

Now some app backgrounds are dark (dashboard, settings, etc), and the
others are white... That's not consistent, unless you only use the white
theme.

Besides, while preparing navigation, all menus are now white, but if I
press the bottom bar 'gear' button for route settings,  that pop-up menu is
dark, and it also overlaps with the 'black flag' menu alongside it
(white)...


-- 
Cumprimentos,
D.er Hugo Barrocas

**Comment by crimean** [comment]
You are right, we will fix it. Sorry for the issue.
Regarding settings ('gear' button) - it is in progress and will be fixed as well.

**Comment by Barrocas** [comment]
The 'theme' settings are working as expected until at least build
2.3.0#14896M, from 14-12-2015.
From day 15-12-2015 until now, it's mixed black & white.

Thank you, keep up the good work! :)


-- 
Cumprimentos,
D.er Hugo Barrocas

**Comment by Barrocas** [comment]
Correction:
The build from day 14 already has the navigation setup menu in white.


-- 
Cumprimentos,
D.er Hugo Barrocas

**Comment by crimean** [comment]
Fixed

**Comment by sonora** [comment]
I think we are mixing 2 things here, and we should not:
App theme is something conceptionally different from "night view"!  While we may add an option to make the App theme "auto-depend" on day/night map view, we should still continue to provide the static options to always have the light or dark app theme, as they may be preferably under certain circumstances. (I personally use dark theme, always. and many other outdoor people do, too.)

**Comment by Barrocas** [comment]
I believe it has been fixed, the theme is now only Dark, if that's the
user choice.
I also always use the Dark side :)

But if the user chooses the Light theme, it does change to the Dark at
night (understandable), at least in last week, some builds ago..



-- 
Cumprimentos,
D.er Hugo Barrocas

**Comment by sonora** [comment]
Great, good news, thanks! I have been on a very flaky internet line the
last days, so could not download any new builds. My suggestions stands: We
could have the  App theme setting with 3 options , Dark / Light / According
to day-night-view.
