### ISSUE TITLE
Cloud Sync Error

### ISSUE THREAD

**Issue by Rowin63** [osmandapp/OsmAnd#20836]
### Description

Cloud sync does not work.
After tapping "sync now" or "upload all" this happens.
![Screenshot_20240914_080524_OsmAnd+](https://github.com/user-attachments/assets/edfb47e0-9a2a-453f-8fd5-af0889fdf099)

### Steps to reproduce

see the attached screenshot, process is cancelled by an error ("closed").

### Actual result

...

### Expected result

...

### Your Environment (required)

Osmand +4.9.0
Android 13

**Comment by yuriiurshuliak** [comment]
The bug has been reproduced. To reproduce it, update the app and navigate to Menu → Settings → OsmAnd Cloud → Sync Now.

You'll encounter the error message "Error closed" as a result.

OsmAnd~ 4.9.0#3193m, released: 2024-09-16

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/6c5b218e-8912-4fd2-8cde-5b540c9c247c"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by Rowin63** [comment]
No, it´s not. Still the same.
(but I´m still running the +4.9.0, no update by now?)

**Comment by Rowin63** [comment]
![Screenshot_20241007_234750_OsmAnd+](https://github.com/user-attachments/assets/94d27f74-f403-45e8-b380-dfd04d1f10ea)

**Comment by Rowin63** [comment]
But anyway I dont trust this "cloud sync" because I never know what will be going on with my data.
I´m syncing my devices´ data with an external app ("folder sync") via NAS (syncing "device 1" _to_ the NAS and after this syncing "device 2" _from_ the NAS, getting all new data). 

So all my devices do have _absolutely the same content_ (tracks), but when starting Osmands sync I see this:

device 1 (+4.9.0 - sync anyway still doesn´t work):
![Screenshot_20241008_075445_OsmAnd+](https://github.com/user-attachments/assets/84f3a8e6-715e-4f43-b611-1588028ee6bb)

device 2 (~4.9.0#3363 - perhaps would work):
![Screenshot_20241008_075450_OsmAnd~](https://github.com/user-attachments/assets/f22660c3-bb94-442d-b8f5-ddd3c2c00e40)

See the differences though data is absolutely the same on both devices.
I will beware of hitting "sync now" in this situation and having all my data messed up.
This is the reason why I never use (and don´t trust) your syncing option for syncing two devices.

**Comment by DmitryAlexei** [comment]
Thank you for your feedback.
The problem should have been resolved in the latest nightly build.

**Comment by Rowin63** [comment]
I don't sync the device with the nightly, but only the device with the playstore release.

Thank you!

**Comment by RZR-UA** [comment]
GPX files dated 1 Oct - 14 Oct were re-validated. No more broken files were found.

**Comment by Rowin63** [comment]
> GPX files dated 1 Oct - 14 Oct were re-validated. No more broken files were found.

What does that mean?
Sync still does not work, still the same error (Android +4.9.0)

**Comment by RZR-UA** [comment]
> What does that mean? Sync still does not work, still the same error (Android +4.9.0)

@Rowin63, that message was about validating files in the Cloud to check for freshly broken GPX files. No new broken files were found.

Considering your report for the same error, could you please make a screen record and attach logs (Settings -> Help -> Send logcat log) from the device that is affected by the error?

**Comment by RZR-UA** [comment]
@Rowin63, the build date of OsmAnd 4.9.0 should be at least 2024/09/28 to be free of the Cloud bugs.

**Comment by Rowin63** [comment]
Ah, ok.
But there is no update from the playstore available, latest release still is +4.9.0 from 2024-09-04

**Comment by Rowin63** [comment]
After a fresh install and a step back to the +4.8.6 cloud sync does work again.
(don´t know about the +4.9.0, will not try it)

**Comment by vshcherb** [comment]
OsmAnd+ beta was not published there are issues with review
