### ISSUE TITLE
Can't update POI data

### ISSUE THREAD

**Issue by luigifab** [osmandapp/OsmAnd#20846]
### Description

I'm displaying swimming pools POI on the map. I would like to add opening hours  but I can't edit it, I can only add a new POI.

### Steps to reproduce

Go to 55.52213 25.08419 and display swimming pools POI. Then try to edit it.

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/5086f23b-0b1e-424b-8299-1be3fe673e1b"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/d2c6d83e-0946-4fbd-a0ea-b2aaf0a2877f"  width="300" height="auto"/> </th>
  </tr>
</table>

### Actual result

Can't edit POI details.

### Expected result

Allow to edit the POI.

### Your Environment (required)

```
OsmAnd Version: 4.8.6
Android/iOS version: 11
Device model: Wiko
```

**Comment by yuriiurshuliak** [comment]
I was unable to reproduce the issue. To try reproducing it, go to the coordinates 55.52213, 25.08419, click on the POI of the pool, select "Actions," then choose "Modify POI" and "Add Opening hours."

Please ensure that the OpenStreetMap editing plugin is enabled.

OsmAnd~ 4.9.0#3193m, released: 2024-09-16

https://github.com/user-attachments/assets/f15ae662-dafd-4a22-81d3-586ca26816ed

**Comment by luigifab** [comment]
yes plugin is enabled, and I tried again and I still can't edit this POI, for example next to the swimming pool there are bus stops, and I can edit them

**Comment by vshcherb** [comment]
Bug reproduced; https://www.openstreetmap.org/way/322243903.
Context menu displays correct url to way. 
To fix: all nodes and ways with correct url should be editable in OSM.

**Comment by nazar-kutz** [comment]
@vshcherb The problem seems to be caused by the "no_edit=true" attribute on the poi type of this point. Maybe we should fix it in xml.

Line in XML:
<poi_type name="swimming_pool" tag="leisure" value="swimming_pool" no_edit="true" poi_additional_category="nudism,fee,access_general"/>
https://github.com/osmandapp/OsmAnd-resources/blob/master/poi/poi_types.xml#L4196

Line in code that filtering this point:
isEditable = !amenity.getType().isWiki() && poiType != null && !poiType.isNotEditableOsm();
https://github.com/osmandapp/Osmand/blob/380a20fc064c6c10f830ffa3fb34b2aeee6791d4/OsmAnd/src/net/osmand/plus/plugins/osmedit/OsmEditingPlugin.java#L347

**Comment by vshcherb** [comment]
If internet is available we can allow edit without "predefined type" but all the tags will be loaded

**Comment by luigifab** [comment]
ok with 4.9.7, but swimming pool poi type is now... unknown! #21430 (example with the swimming pool at the coordinates 44.49715 12.14886)

![Capture d'écrans_20241124-205708](https://github.com/user-attachments/assets/9ea5b0f3-ddf6-43c2-af7e-0211221d818f)

**Comment by luigifab** [comment]
Is someone can reopen? I still can't update swimming pool POI.

**Comment by DmitryAlexei** [comment]
@luigifab do you test on OsmAnd 4.9.10?

**Comment by Zirochkabila** [comment]
@luigifab tested the ability to edit POIs on both 4.9.10 and OsmAnd~ 5.0.0#4655m, Released: 2025-03-13, the result is the same - POIs can be edited, and changes are sent to OSM and reflected in the POI data

I can assume that there is a local error that cannot be repeated yet

Please send us a video where we can see the steps you are performing and the result of the actions

**Comment by Zirochkabila** [comment]
@luigifab At the moment, this will not be possible - it is impossible to give polygonal objects, and Рiscine is always a polygonal object in OSM.

**Comment by luigifab** [comment]
lol, I see
