### ISSUE TITLE
Regression: My Places > Tracks screen again very slow to open (20 sec)

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#20844]
Again, the time it takes to open the "My Places > Tracks screen" on my setup (~3000 Tracks in 70 folders) has increased to ~20 sec of watching the spinner. And also similarly long every time I enter the "Visible Tracks" screen. See log here: [logcat.log.txt](https://github.com/user-attachments/files/17004912/logcat.log.txt).

On previous occasions, this had been due to excessive individual File I/O, sometimes in obsolete operations (like here https://github.com/osmandapp/OsmAnd/commit/24ff4cbda4174d77541195e83d9de6ebbbee98d5) or sometimes in repetitive loops not bundling things as a stream. I had fixed on some occasions which had brought the opening time for the dialog down to about 3 sec. Now it's back to 20 sec.

Needs investigating. Perhaps a result of porting some code to a shared library?

**Comment by alex-osm** [comment]
Yes, when reading gpx files, the shared library is currently used. But recently there were changes to speed up reading the file list using platform method - https://github.com/osmandapp/OsmAnd/commit/41f30f176c6329c16f6ea8156a5cfd9788862643

Did you try latest nightly version of OsmAnd?

**Comment by Rowin63** [comment]
Hm. Does not happen here running the ~4.9.0#3190 (1350 tracks in 75 folders), but all track folders are switched back to "last edited" again...

**Comment by alex-osm** [comment]
There was also fix of bug which cause mess with folders in DB - https://github.com/osmandapp/OsmAnd/commit/18e91d162071a1146e40644d0285c00fe92bdd67
It was introduced on 31.07.2024

**Comment by sonora** [comment]
I had not built an apk in a while. My build of our master branch 2024-09-07 still is fast. Build of 2024-09-14 (late evening) exhibits the issue.

**Comment by alex-osm** [comment]
@sonora I see. Can you may be send logs similar to those from first message, but from master branch 2024-09-07?
As you can see in TrackFolderLoaderTask we moved from File to KFile and PROGRESS_BATCH_SIZE was increased from 7 to 70. 
BTW - TrackFolderLoaderTask is moving to shared lib as well. It will be there next week.

**Comment by sonora** [comment]
Sure, @alex-osm !

- I have meanwhile tested a little optimization, see this PR https://github.com/osmandapp/OsmAnd/pull/20845, and it results in about **10 sec** (instead of the now 20 sec) GPX tracks loading time: [logcat_09-15_parallel.log.txt](https://github.com/user-attachments/files/17005562/logcat_09-15_parallel.log.txt) . So it does not address the root cause we have somehow introduced, it is only a secondary optimization (probably worth having).

- I also reinstalled the Sept. 7 build, and this is the respective log section [logcat_09-07.log.txt](https://github.com/user-attachments/files/17005554/logcat_09-07.log.txt), and it shows **~4 sec** as the GPX tracks loading time.

**Comment by sonora** [comment]
I believe the problem are the countless I/O operations going on. We should probably cache the file tree, along these lines:

```
actual class NativeFile actual constructor(actual val file: KFile) {

    private var jFile = file.jFile()

    // Cache for file properties
    private val fileLength: Long by lazy { jFile.length() }
    private val lastModifiedTime: Long by lazy { jFile.lastModified() }
    private var cachedFiles: List<KFile>? = null

    actual fun length(): Long = fileLength

    actual fun lastModified(): Long = lastModifiedTime

    actual fun listFiles(): List<KFile>? {
        if (cachedFiles == null) {
            cachedFiles = jFile.listFiles()?.map { it.kFile() }
        }
        return cachedFiles
    }
}

```

**Comment by alex-osm** [comment]
NativeFile was introduced to eliminate slow kotlin calls when calling expensive methods like listFiles(). In other words, it shouldn't be a problem and should work as fast as before.
From the other hand we could cache the file tree, but it is not clear how and when it should be refreshed.

**Comment by sonora** [comment]
Yes, I have to admit I am still not sure which change exactly caused the current regressiion.

I think this https://github.com/osmandapp/OsmAnd/commit/1410005c77437213c56d5c58228700a3736c9dc0 was a big performance gain last time I had looked into this. Essentially this had eliminated the expensive single `file.exists()` IOs.

**Comment by alex-osm** [comment]
@sonora Just [merged](https://github.com/osmandapp/OsmAnd/pull/20874) new stage of shared library files with optimization fix of reading gpx db and root gpx folder. Also root folder cache was introduced. Please test.

**Comment by sonora** [comment]
Amazing, good work! I experience ~1 sec loading time, best ever since we left the foldout setup of the tracks screen behind many months ago!

What does not yet work is entering the 'Visible on map' screen, both via the MyPlaces>Tracks screen and via Configure map. The screen is empty and non-functional.

**Comment by alex-osm** [comment]
Great news! There was side effect about broken screens. [Fixed](https://github.com/osmandapp/OsmAnd/commit/7b8a69efdea47b4c93a33ad38555cbc2d6e983f6).

About read errors - could you may be attach the file to reproduce the error?

**Comment by sonora** [comment]
Perfect! Works flawless now, from what I see!

I have checked the handful of my ~3500 tracks which cause an 'Error reading GPX' logcat entry (the track referenced in my log snippet above was a test-edited version of the user-provided one in #19995), and find they indeed have small issues. Like a missing `</trkseg>` or `</wpt>` tag, which apparently was tolerated when displaying a track but it is of course a syntax issue, so I think no actionable problem here.

And I guess my PR https://github.com/osmandapp/OsmAnd/pull/20845 has become obsolete, or is there any value still? (It would now need conflict resolving.)

**Comment by sonora** [comment]
PS: I just notice tbe following glitch still: Sometimes when first opening the MyPlaces tracks screen, or on rare occasions also upon a pull-down refresh there, the bottom stats seem incomplete, they show only 90% or so of all tracks. As if there are occasions where a final screen refresh is missing in the end to update the screen with the completed stats?

**Comment by alex-osm** [comment]
@sonora Next iteration of [fixes](https://github.com/osmandapp/OsmAnd/commit/e2adc0a9b55f121dc6c11b09928eea10a6504eda) :) Now statistics should be fixed and analysing of new tracks should be faster.
Please test.

**Comment by sonora** [comment]
Fantastic! I find no flaw so far!

**Comment by sonora** [comment]
Well done, @alex-osm , thank you!!! This has enormously increased the value of using OsmAnd with a large gpx dataset!

**Comment by sonora** [comment]
PS:Still have a few occurrences where the root folder stats seem incomplete at fthe irst opening of the screen. They would e.g. say "3439 Tracks", and only upon pull-down refreshing would update to the full 3492. Sometimes even taking several refreshs to get to the full number. But perhaps this is a sign of the db updating in the background?

**Comment by alex-osm** [comment]
@sonora Now progress circle on "My places" screen should work while all data including background work is refreshing.
Could you send me log? I added some new lines recently.
Also you may try to clean gpx db (clear OsmAnd cache I guess)

**Comment by sonora** [comment]
[logcat.log.txt](https://github.com/user-attachments/files/17090444/logcat.log.txt). Total flat tracks counted from root currently 3492.

**Comment by alex-osm** [comment]
Thank you! Next [fix](https://github.com/osmandapp/OsmAnd/commit/f01edd806e766afb5c4fe169104a25f252e59788). 
I noticed that your bulk item reading improvement was lost and have restored it.
Also removed redundant progress call that could result in incomplete statistics values.
Please test.

**Comment by sonora** [comment]
Thanks! No decisive change any more, from what I see. Folders stats refresh is still not solved. [logcat.log.txt](https://github.com/user-attachments/files/17094209/logcat.log.txt)

- I had introduced `fileExistenceMap` because previous code had single I/O calls to `file.exists()`. Not sure your porting had still suffered from that in the first place, but probably still a good idea to have this cache.

- Similarly, need to finally look if https://github.com/osmandapp/OsmAnd/pull/20845 is obsolete now.

@vshcherb  One thought about folders stats is more for Victor/Product Management: Should they be expensive and cost many CPU cycles/battery, I would, when in the field, i.e. during normal working with Osmand, not be interested to see these every time I enter the Tracks management screen. Folder stats are a special function, there could be a button '**Display stats**' or '**Details**' rather that calculating and displaying these permanently in everyday business.

**Comment by pebogufi** [comment]
> Should they be expensive and cost many CPU cycles/battery, I would, when in the field, i.e. during normal working with Osmand, not be interested to see these every time I enter the Tracks management screen. Folder stats are a special function, there could be a button '**Display stats**' or '**Details**' rather than calculating and displaying these permanently in everyday business.

Fully suppoort this idea. 
In 99% of use i never look at this stats.

**Comment by alex-osm** [comment]
Currently we have [cached root gpx folder data](https://github.com/osmandapp/OsmAnd/blob/f01edd806e766afb5c4fe169104a25f252e59788/OsmAnd-shared/src/commonMain/kotlin/net/osmand/shared/gpx/TrackFolderLoaderTask.kt#L32) including statistics. The root folder and subfolders updated when tracks fragment is first opened, or on pull-to-refresh, or when files are moved/renamed/created. The statistics itself are calculated very fast - with one [cycle](https://github.com/osmandapp/OsmAnd/blob/f01edd806e766afb5c4fe169104a25f252e59788/OsmAnd-shared/src/commonMain/kotlin/net/osmand/shared/gpx/filters/TrackFolderAnalysis.kt#L34) for gpx items retrieved after the root folder has been updated.

**Comment by sonora** [comment]
Yes, in my mind, these detailed track/folder stats are purely informational and should on a management screen be on demand. But that's probably Victor to judge.

Still it looks like either we are missing a final screen refresh, or we somehow terminate the stats calculation early on many occasions, where I see only between 90 and 95% of tracks contained also reflected, and only (sometimes repetead) pull-down corrects this.

See here (true tracks count is 3492): 
![Untitled](https://github.com/user-attachments/assets/780a9a1b-bd29-4fd2-ad89-532ca5f2ed8c)

**Comment by alex-osm** [comment]
Looks like duration is broken. Is it same after pull-down?

**Comment by sonora** [comment]
No, not reliably. Sometimes it's even worse after pull-down. may then show e.g. only 3100 tracks. Eventually, after repeated pull-downs, it may show the full 3492.

**Comment by alex-osm** [comment]
I hope final [fix](https://github.com/osmandapp/OsmAnd/commit/694680eccb27891624c34b90affb6f1acf2750c8) is ready :)
Sorry for bothering you with testing ...

**Comment by sonora** [comment]
Yeah, that fixed it now, it seems! 😉

Never mind about using me for testing. I have been with the project for so long and use the app so intensively that I seem to almost "smelll" any regresseion we seem to produce... 😉 😉 😉

Let me thank you for your good work here.

**Comment by sonora** [comment]
Latest phenomenon: To reset the db, I had tried this procedure:
- remove my 'tracks' data folder
- restart OsmAnd, enter the empty MyPlaces/Tracks screen
- kill the app again
- re-add the 'tracks' folder
- restart the app, go to the MyPlaces/Tracks screen: There, all tracks are displayed again pretty fast, root folder stats are also ok. But the 'busy' spinner never stops spinning any more. Also not when repeatedly entering the screen...

**Comment by alex-osm** [comment]
Yesterday there was [commit](https://github.com/osmandapp/OsmAnd/commit/295460a78d46878a92d16b3e77467482fe4c679c) about fix outdated progress and db cleanup on app startup (drop records with non-existed files). Also KFile was slightly changed.
Please try it.

**Comment by sonora** [comment]
Yes, my test included that commit. Worth noting:
- During the spinnner shown, the track stats showed the full track number from the start, but all others remained at 0
- The others, except downhill, were updated one time upon re-entering the screen, that's how I knew something was happening and it is not an artifact
- Downhill remained at 0 throughout the process. Now somehow it shows 0, sometimes the plausible value.

**Comment by alex-osm** [comment]
Could you send logs please?

**Comment by sonora** [comment]
I have repeated the process, and this is the log of the first app re-start after the tracks folder was added again, and after in OsmAnd sitting about one minute on the MyPlaces/Tracks root screen with the spinner on, i.e. presumably while the stats data is repopulated to the db: [logcat.log.txt](https://github.com/user-attachments/files/17144512/logcat.log.txt)

**Comment by alex-osm** [comment]
I see, thank you! Please send log after all data was calculated and you entered my places again.

**Comment by sonora** [comment]
[logcat.log.txt](https://github.com/user-attachments/files/17145559/logcat.log.txt)

![Untitled](https://github.com/user-attachments/assets/36fd059e-aebc-4453-8a24-564160b4232b)
