### ISSUE TITLE
Rendering sometimes stops in Nautical view with Depth contours

### ISSUE THREAD

**Issue by Guylby** [osmandapp/OsmAnd#20857]
### Description

Hi,

I've noticed that in the nautical view once you enable depth contours the rendering becomes very slow and sometimes just stops rendering tiles alltogether. This has been going on for a few updates now (I've seen the same behaviour on 4.7 and 4.8)
This seems strange as my device has no trouble rendering much more complex contour lines for standard elevation.

While looking at the logcat data, there was around 3000 errors like so:

> 09-16 11:14:17.385 10054 10054 W System.err: Rendering attribute route is not found !
09-16 11:14:17.494 10054 10258 W net.osmand.core:native: Path effect (1) with 1 intervals is invalid
09-16 11:14:17.494 10054 10258 W net.osmand.core:native: Path effect (1) with 1 intervals is invalid
09-16 11:14:17.494 10054 10258 W net.osmand.core:native: Path effect (1) with 1 intervals is invalid
09-16 11:14:17.494 10054 10258 W net.osmand.core:native: Path effect (1) with 1 intervals is invalid
09-16 11:14:17.494 10054 10258 W net.osmand.core:native: Path effect (1) with 1 intervals is invalid
09-16 11:14:17.494 10054 10258 W net.osmand.core:native: Path effect (1) with 1 intervals is invalid
09-16 11:14:17.494 10054 10258 W net.osmand.core:native: Path effect (1) with 1 intervals is invalid
09-16 11:14:17.494 10054 10258 W net.osmand.core:native: Path effect (1) with 1 intervals is invalid
09-16 11:14:17.494 10054 10258 W net.osmand.core:native: Path effect (1) with 1 intervals is invalid
09-16 11:14:17.494 10054 10258 W net.osmand.core:native: Path effect (1) with 1 intervals is invalid
09-16 11:14:17.495 10054 10258 W net.osmand.core:native: Path effect (1) with 1 intervals is invalid
09-16 11:14:17.495 10054 10258 W net.osmand.core:native: Path effect (1) with 1 intervals is invalid
09-16 11:14:17.495 10054 10258 W net.osmand.core:native: Path effect (1) with 1 intervals is invalid
09-16 11:14:17.495 10054 10258 W net.osmand.core:native: Path effect (1) with 1 intervals is invalid
09-16 11:14:17.495 10054 10258 W net.osmand.core:native: Path effect (1) with 1 intervals is invalid
09-16 11:14:17.495 10054 10258 W net.osmand.core:native: Path effect (1) with 1 intervals is invalid
09-16 11:14:17.495 10054 10258 W net.osmand.core:native: Path effect (1) with 1 intervals is invalid
09-16 11:14:17.495 10054 10258 W net.osmand.core:native: Path effect (1) with 1 intervals is invalid
09-16 11:14:17.495 10054 10258 W net.osmand.core:native: Path effect (1) with 1 intervals is invalid
09-16 11:14:17.495 10054 10258 W net.osmand.core:native: Path effect (1) with 1 intervals is invalid
09-16 11:14:17.495 10054 10258 W net.osmand.core:native: Path effect (1) with 1 intervals is invalid
09-16 11:14:17.495 10054 10258 W net.osmand.core:native: Path effect (1) with 1 intervals is invalid
09-16 11:14:17.495 10054 10258 W net.osmand.core:native: Path effect (1) with 1 intervals is invalid
09-16 11:14:17.495 10054 10258 W net.osmand.core:native: Path effect (1) with 1 intervals is invalid
09-16 11:14:17.496 10054 10258 W net.osmand.core:native: Path effect (1) with 1 intervals is invalid
09-16 11:14:17.496 10054 10258 W net.osmand.core:native: Path effect (1) with 1 intervals is invalid
09-16 11:14:17.496 10054 10258 W net.osmand.core:native: Path effect (1) with 1 intervals is invalid
09-16 11:14:17.496 10054 10258 W net.osmand.core:native: Path effect (1) with 1 intervals is invalid
09-16 11:14:17.496 10054 10258 W net.osmand.core:native: Path effect (1) with 1 intervals is invalid
09-16 11:14:17.496 10054 10258 W net.osmand.core:native: Path effect (1) with 1 intervals is invalid

### Steps to reproduce

go the the Nautical view profile (boat profile), download and enable the Depths contours in the settings, span, zoom and roam around the map, notice the slowdowns and errors in displaying the tiles.

### Actual result

Rendering in general is much slower than other profiles, and notice at the end that osmand stops rendering tiles alltogether (and required a restart to start functioning again). The screen was responsive, you could span around and interact with the UI but no map was loading

https://github.com/user-attachments/assets/bfd650dd-10ac-477e-8148-d4918a5010b6

### Expected result

Rendering is smooth and doesn't stop loading tiles.

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: 4.9.0
Android/iOS version: 13
Device model: Sony Xperia 10 III
Crash-Logs: ?
```

**Comment by vshcherb** [comment]
Extra task: fix ``` net.osmand.core:native: Path effect (1) with 1 intervals is invalid``` it's likely not related to rendering issue

**Comment by vshcherb** [comment]
@RZR-UA please reproduce as long line issue is fixed now

**Comment by RZR-UA** [comment]
It is easily reproduced in the Android Studio Emulator:

Just load maps, enable Nautical style and Nautical depths (contours) and play with Zoom in/zoom out at the location near Lisbon. The Map of Portugal is not required for reproduction. Location to zoom in/out: 38.91718° N, 10.56903° W

![maps](https://github.com/user-attachments/assets/ee31117a-2e2d-4b3c-835e-1969587bfde0)

https://github.com/user-attachments/assets/969cde49-f8a8-4d24-917c-5ac4acd1cdaf

**Comment by Andrewschenko** [comment]
The simplest way to reproduce this issue is to zoom in to level 15 at the ocean near Lisboa and keep Nautical depths enabled (Europe Contours + World Contours maps). The problem is that contour lines in binary map objects are bloated (long and highly detailed at the same time).

**Comment by Zirochkabila** [comment]
# Testing 1
`4.9.3.4941` - Rendering is smooth and fast

`OsmAnd~ 5.0.0#4136m, Released: 2025-01-15` 
It takes about 20 seconds to display (much faster than the user's video), but sometimes the app crashes (you need to leave the screen for a few minutes without interacting - it plays about once every five attempts)

[Archive 7.zip](https://github.com/user-attachments/files/18426373/Archive.7.zip)

**Comment by Guylby** [comment]
In Osmand 5.0.5 I still see the same slowdowns as before. When at a large zoom level, rendering is smooth, however after zooming in, rendering gets slower and slower making the application really slow. Even after dezooming for awhile rendering is still very stuttery. The catlog file indicates numerous OOM errors

https://github.com/user-attachments/assets/247b707e-282e-4338-8a49-7fecac5b377f

**Comment by Zirochkabila** [comment]
`OsmAnd~ 5.1.0#5190m, Released: 2025-05-15` has been tested - as you can see in the video, the difference in rendering **speed is 8-7 seconds** (with Depth contours enabled, it is slower)


<details><summary>Details V2 - delay is present</summary>
<table style="width:100%">
  <tr>
    <th>Without Depth contours - 1s</th>
    <th>With Depth contours - about 8s</th>
  </tr>
  <tr>
    <td><video source src="https://github.com/user-attachments/assets/fd771c03-20e9-4427-8ef5-f56f38644405"  width="300" height="auto"/></td>
    <td><video source src="https://github.com/user-attachments/assets/f749a01c-657c-4b42-8bfc-01829f0de952"  width="300" height="auto"/></td>
  </tr>
</table> 
</details> 


<details><summary>Details V1 - no delay in rendering</summary>
<table style="width:100%">
  <tr>
    <th>Without Depth contours - about 2s</th>
    <th>With Depth contours - about 2s too</th>
  </tr>
  <tr>
    <td><video source src="https://github.com/user-attachments/assets/e7fd10ea-369d-4b74-b3da-7b6d4e1c6ecf"  width="300" height="auto"/></td>
    <td><video source src="https://github.com/user-attachments/assets/1ed31a83-0308-4491-b514-c846f168694f"  width="300" height="auto"/></td>
  </tr>
</table> 
</details>

**Comment by Zirochkabila** [comment]
### Note

- [x] Waiting for new maps to be downloaded

**Comment by Zirochkabila** [comment]
# Testing 2
`OsmAnd~ 5.1.0#5323m, Released: 2025-06-04`

Checked rendering speed on new maps of sea depth contours - **Fixed, rendering without delays** (as in V1)


<details><summary>Details</summary>
<table style="width:100%">
  <tr>
    <th>Without Depth contours - 1s</th>
    <th>With Depth contours - about 8s</th>
  </tr>
  <tr>
    <td><video source src="https://github.com/user-attachments/assets/5d4a9daf-8e55-4887-bca1-017300ce25b6"  width="300" height="auto"/></td>
    <td><video source src="https://github.com/user-attachments/assets/4d9219b7-ee6f-4b1c-9b06-681502646560"  width="300" height="auto"/></td>
  </tr>
</table> 
</details>
