### ISSUE TITLE
Add text above boundary line = protected_area

### ISSUE THREAD

**Issue by BikeRoad** [osmandapp/OsmAnd#22736]
Currently only the keys boundary= national park, aboriginal land, border zone and leisure= nature_reserve show text on the line.

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/21e4874b-8f0e-488b-b8a7-452df51caca9"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by yuriiurshuliak** [comment]
**`boundary=protected_area` does not display a name label along the boundary line, unlike other similar tags such as `boundary=national_park` or `leisure=nature_reserve`.**

**QA Reproduction Status:**  Confirmed

**Steps to Reproduce:**

1. Open **OsmAnd**.

2. Navigate to the following coordinates:

   * `49.823457, 24.094132` → `boundary=protected_area`
   * `49.825243, 24.526226` → `boundary=national_park`
   * `49.854420, 23.921050` → `leisure=nature_reserve`

3. Zoom to a level where boundary lines and text labels are usually visible.

4. Observe that:

   * **Protected Area** shows the name *inside* the shape, not on the boundary line.
   * **National Park** and **Nature Reserve** display their names *on the boundary lines* as expected.

**Expected Result:**
Text labels should also appear along the boundary lines for `boundary=protected_area`, consistent with the rendering behavior of similar boundary types.

**Actual Result:**
Text is shown only inside the area, not along the boundary line.



OsmAnd~ 5.1.0#5344m, released: 2025-06-09


<table style="width:100%">
  </tr>
  <tr>
    <th>boundary=protected_area</th>
    <th>boundary=national_park</th>
    <th>leisure=nature_reserve</th>
  </tr>
  <tr>
<th><img src="https://github.com/user-attachments/assets/a55ae6cc-6aef-4b0e-8f4b-e771d9ee27ac"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/7fcfa8dd-75ec-4fec-901f-006172ab6e40"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/bcfcbf93-b68b-46ff-bc07-b025fe7411d8"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by BikeRoad** [comment]
@yuriiurshuliak thanks for detailing it.

**Comment by josail** [comment]
May I forward to you info on the nautical standard for marine reserves and environmentally sensitive sea areas. It happens that I have just developed the symbology and icons for the OpenNauticalChart, OpenSeaMap and have already offerd this to Quantenschaum, who has suggested the marine style gor OSMAND.

Here is the latest set of symbols/icons. Please feel invite to make good use in OSMAND:

https://github.com/OpenNauticalChart/josm/pull/27

See few previously already existing icons here: 
https://github.com/OpenNauticalChart/josm/tree/master/icons/svg/N

This is following International Hydrological Organisation Standard INT-1 Section N  (see https://www.hydro.navy.mi.th/standard/INT1_EN_Ed8.pdf and https://docs.iho.int/mtg_docs/com_wg/DIPWG/CSMWG15/CSMWG15-09F_CSPCWG_CL07-04_ESSA.pdf) and recent proposals for their meaningful amendment by additional symbology and icons discussed (see https://www.researchgate.net/publication/367477888_Marine_protected_areas_and_electronic_navigational_charts_legal_foundation_mapping_methods_IHO_S-122_portrayal_and_advanced_navigation_services/fulltext/63d404cf64fc860638f11456/Marine-protected-areas-and-electronic-navigational-charts-legal-foundation-mapping-methods-IHO-S-122-portrayal-and-advanced-navigation-services.pdf)

**Comment by xmd5a2** [comment]
Fixed. How to test: see [post](https://github.com/osmandapp/OsmAnd/issues/22736#issuecomment-2955425302) above (ukraine_lviv_europe will be updated in a couple of days).

**Comment by Zirochkabila** [comment]
# Testing 1

`OsmAnd~ 5.2.0#5677m, Released: 2025-07-23`
`5.1.3.5134`

[Test map: boundary=protected\_area\_Lviv.obf.zip](https://github.com/user-attachments/files/21384917/boundary.protected_area_Lviv.obf.zip)

* [x] iOS - Protected Area still shows the name inside the shape (may need migration) - **Waiting 5.2 for double check** `5.2.0.5206`

> ✅ Fixed on Android — verified on generated map (still no update)

<details><summary>Details</summary>
<table style="width:100%">
  <tr>
    <th><img src="https://github.com/user-attachments/assets/96bc4a08-6f36-4d17-bdaf-d0b918d3523f"  width="300" height="auto"/></th>
    <th><img src="https://github.com/user-attachments/assets/683f16ac-bec9-4228-afd0-54cc342c144a"  width="700" height="auto"/></th>
  </tr>
</table>  
</details>

**Comment by dmpr0** [comment]
To test enable More details > Nature reserve
