### ISSUE TITLE
The app freezes, lags, and occasionally crashes when opening a track point in Istanbul.

### ISSUE THREAD

**Issue by vankos** [osmandapp/OsmAnd#23732]
### Description

The exact cause—location, track, or something else—is unclear; see the steps below.

### Steps to reproduce

0. Download the Istanbul area.
1. Import the attached track: [Need photo Bereketzade Mahallesi 2025-10-26T12-47-24.903159.gpx.txt](https://github.com/user-attachments/files/23151127/Need.photo.Bereketzade.Mahallesi.2025-10-26T12-47-24.903159.gpx.txt)
2. Open the descriptions for a few points of the track on the map.

### Actual result

Freezes, lags and occasional crashes

### Expected result

App continue to work as before - relatively smooth

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: 5.3.0#6338m
Android version: 16
Device model: Pixel 9 Pro
Crash-Logs: [exception.log](https://github.com/user-attachments/files/23151124/exception.log)

```

**Comment by Zirochkabila** [comment]
> OsmAnd~ 5.3.0#6340m, Released: 2025-10-27

Similar behavior to https://github.com/osmandapp/OsmAnd/issues/23691

**Comment by vankos** [comment]
I’d like to note that, unlike https://github.com/osmandapp/OsmAnd/issues/23691 , this issue reproduces in both v1 and v2.

**Comment by Zirochkabila** [comment]
@vankos Freezes and crashes are not reproduced on the test device with V1 - please share a video (with steps and result) of how it works on your device.

**Comment by vankos** [comment]
Recorded a  video: [video_2025-10-29_11-27-47.mp4](https://github.com/user-attachments/files/23205441/video_2025-10-29_11-27-47.mp4.txt)
Steps are the same:

0. Download the Istanbul area.
1. Import the attached track: [Need photo Bereketzade Mahallesi 2025-10-26T12-47-24.903159.gpx.txt](https://github.com/user-attachments/files/23151127/Need.photo.Bereketzade.Mahallesi.2025-10-26T12-47-24.903159.gpx.txt)
2. Open the descriptions for a few points of the track on the map.

Bonus crash at the end of the video:
[exception.log](https://github.com/user-attachments/files/23205449/exception.log)

**Comment by Zirochkabila** [comment]
> OsmAnd~ 5.3.0#6367m, Released: 2025-10-30

Freezing and crashes occur with both V2 and V1 (more time is needed to reproduce the crash).

<details><summary>Details</summary>
<video src="https://github.com/user-attachments/assets/deb69652-7764-464d-8d1e-5d1c7abd5640"></video>
</details>

**Comment by Zirochkabila** [comment]
Crash should be fixed here https://github.com/osmandapp/OsmAnd/issues/23701#issuecomment-3450029947

**Comment by Zirochkabila** [comment]
# Testing 1

> OsmAnd~ 5.3.0#6394m, Released: 2025-11-03

## **Severity**: 🔴 Critical

> **Priority**: 🔴 High / **Frequency**: Medium

* [ ] 1. Freezes, lags, and crash — **Still present**

[exception (34).log.zip](https://github.com/user-attachments/files/23302763/exception.34.log.zip)

<details><summary>Details</summary>
<table style="width:100%">
  <tr>
    <th>V2</th>
    <th>V1</th>
  </tr>
  <tr>
    <td><video source src="https://github.com/user-attachments/assets/2259147e-4a63-4be1-b091-269c13c059d7"  width="300" height="auto"/></td>
    <td><video source src="https://github.com/user-attachments/assets/b5031353-2138-4224-a2b9-b9a887595e2b"  width="300" height="auto"/> </td>
  </tr>

**Comment by vankos** [comment]
Hi, I also observe freezes when opening any POI in Istanbul, so I think may be the problem isn’t tracks but the POI/track point menu itself. I have a feeling this is related to the 'Looking up address' step, which executes for quite a long time in Istanbul.

**Comment by vankos** [comment]
The problem is still reproducible in 5.3.0#6483m; it just takes a little longer and is slightly less intense. After about a minute of opening POIs and track points, I still get freezes and an 'OsmAnd is not responding' dialog.

**Comment by Zirochkabila** [comment]
# Testing 2

> OsmAnd~ 5.3.0#6483m, Released: 2025-11-12

I checked it again on the nightly version (both V1 and V2) — there are occasional minor lags, but I don't see any freezes or crashes like before.

@vankos Please try installing [the nightly version](https://download.osmand.net/latest-night-build/OsmAnd-default.apk) and send us a video showing the behavior and results (if you can reproduce it).

**Comment by vankos** [comment]
It starts at ~1:10 (about a minute in, as I mentioned). At the end of the video, an “OsmAnd is not responding” dialog appears. It’s definitely better now, but the issue reappears after about a minute.

[video_2025-11-12_19-07-39.mp4](https://github.com/user-attachments/files/23504459/video_2025-11-12_19-07-39.mp4.txt)

**Comment by Chumva** [comment]
@vankos, could you provide logcat logs after the “OsmAnd is not responding” dialogue appears?

**Comment by vankos** [comment]
Reproduced at 20:13

[logcat.log](https://github.com/user-attachments/files/23505868/logcat.log)

```
Device : caiman
Brand : google
Manufacturer : Google
Model : Pixel 9 Pro
Product : caiman
Build : BP3A.251005.004.B3
Version : 16
App Version : OsmAnd Nightly
Apk Version : 5.3.0#6492m 5399
```

**Comment by Zirochkabila** [comment]
> OsmAnd~ 5.3.0#6496m, Released: 2025-11-13
> OsmAnd 5.2.10, released: 2025-11-13 - **Same**

@vankos @Chumva On the test device ( much weaker), the freeze and crash were reproduced after 7 minutes of interaction with the track points - the last seconds are shown in the video (accelerated x2).

Crash happened in this area `41.02234° N, 29.01779° E`

[logcat (16).log](https://github.com/user-attachments/files/23519539/logcat.16.log)

[logcat 5.2.1.5210 (17).log.zip](https://github.com/user-attachments/files/23543583/logcat.17.log.zip)

<details><summary>Details</summary>
<table style="width:100%">
  <tr>
    <th>5.2.10</th>
    <th>5.3.0#6496m</th>
  </tr>
  <tr>
    <td><video source src="https://github.com/user-attachments/assets/308c888c-81dc-47de-990f-87e127e14505"  width="300" height="auto"/></td>
    <td><video source src="https://github.com/user-attachments/assets/79d3c75a-4d41-4dad-98fb-cfeef76916a7"  width="300" height="auto"/> </td>
  </tr>
</table> 
</details>

**Comment by Chumva** [comment]
@vankos Could you try new nightly build?

**Comment by Zirochkabila** [comment]
> 5.2.12
> OsmAnd~ 5.3.0#6592m, Released: 2025-11-28

[logcat (18).log.zip](https://github.com/user-attachments/files/23826473/logcat.18.log.zip)

Freezing and crashing in the first seconds of interaction with Waypoints



<details><summary>Details</summary>
<video src="https://github.com/user-attachments/assets/4255278b-5c66-4211-8f7a-dc71643116f5"></video>
</details>

**Comment by dmpr0** [comment]
Can't reproduce.

**Comment by zakutin** [comment]
Please reopen the issue. It is still present on version 5.2.13.

**Comment by tudos4** [comment]
I can still reproduce intermittent freezes when opening waypoint descriptions from the GPX on OsmAnd 5.3.10 from Google Play.

Device/app context:

* Device: realme RMX3370 / Realme GT Neo2
* Android: 13, SDK 33
* ROM/build: aospa_bitra-user 13 TKQ1.230915.002
* Security patch: 2023-10-05
* Platform: qcom/kona, Adreno EGL/Vulkan
* ABI: arm64-v8a
* RAM: 11.8 GB total
* OsmAnd: 5.3.10 (5310), Google Play Store

Repro path:

* Import/open the GPX around Istanbul
* Tap a red waypoint marker
* If multiple nearby points are shown, choose one waypoint from the “What’s here” list
* Wait for the waypoint context/description sheet to open

It does not happen on every waypoint. In my run it happened only a couple of times,[]() most other waypoint openings loaded normally. When it did happen, the UI froze for a few seconds before the waypoint sheet appeared.

The freeze is visible in logcat. One example from the recording:

```text
05-23 15:42:41.202 10633 10633 I Choreographer: Skipped 202 frames!  The application may be doing too much work on its main thread.
05-23 15:42:41.208 10633 10641 I net.osmand: Background young concurrent copying GC freed 2684792(86MB) AllocSpace objects, 71(3372KB) LOS objects, 0% free, 157MB/157MB, paused 2.787ms,42us total 4.391s
```

There was another similar stall earlier:

```text
05-23 15:42:23.740 10633 10633 I Choreographer: Skipped 217 frames!  The application may be doing too much work on its main thread.
```

The same capture also shows repeated amenity searches on background threads after the stall:

```text
05-23 15:42:41.288 10633 12559 D net.osmand: AmenityIndexRepositoryBinary Search for 41.00443473292014 28.953374605625868 done in 59 ms found 0. {AsyncTask #7}
```

and repeated reverse-geocoding exceptions after waypoint clicks:

```text
05-23 15:42:42.580 10633 12400 E net.osmand: CurrentPositionHelper Exception happened during reverse geocoding {pool-11-thread-1}
05-23 15:42:42.580 10633 12400 E net.osmand: com.google.protobuf.InvalidProtocolBufferException: While parsing a protocol message, the input ended unexpectedly in the middle of a field.
05-23 15:42:42.581 10633 12400 E net.osmand: 	at net.osmand.binary.BinaryMapIndexReader.searchAddressDataByName(BinaryMapIndexReader.java:1425)
```

So this still looks reproducible on a newer release than 5.2.13, though intermittently. 

Separately, from reading the current context-menu code, it looks like #23872 mainly covers cleanup on full menu close. There may still be a hide/replace path where an old menu builder is marked hidden but its async work is not cancelled, because `MenuController.onAcquireNewController(...)` is empty and `MenuBuilder.onHide()` does not stop the tracked amenity tasks. I cannot prove that from this stock build log alone, but it seems like a plausible path worth checking with temporary lifecycle logs around `MenuBuilder.onHide/onClose`, `SearchAmenitiesTask`, and `MenuController.onAcquireNewController`.

**Comment by tudos4** [comment]
Filtered excerpt from the logcat capture.

Summary counts from the filtered log:

* click_events: 26
* osmand_choreographer_skipped: 2
* invalid_protocol_buffer: 199
* reverse_geocoding_exception: 198
* amenity_search: 201

Key events by second:

```text
15:42:00: {'click': 1}
15:42:02: {'amenity_search': 9}
15:42:18: {'click': 1, 'amenity_search': 9}
15:42:20: {'click': 1}
15:42:23: {'skipped': 1, 'amenity_search': 6}
15:42:24: {'amenity_search': 3}
15:42:33: {'click': 1}
15:42:34: {'amenity_search': 6}
15:42:36: {'click': 1, 'amenity_search': 9}
15:42:38: {'click': 1, 'rev_geo_exc': 1, 'proto_exc': 2}
15:42:41: {'skipped': 1, 'amenity_search': 9}
15:42:42: {'click': 1, 'rev_geo_exc': 4, 'proto_exc': 4, 'amenity_search': 12}
15:42:48: {'click': 1, 'rev_geo_exc': 20, 'proto_exc': 20, 'amenity_search': 21}
15:42:52: {'click': 1, 'rev_geo_exc': 20, 'proto_exc': 20, 'amenity_search': 21}
15:42:57: {'click': 1, 'rev_geo_exc': 52, 'proto_exc': 52}
15:43:04: {'click': 1, 'rev_geo_exc': 19, 'proto_exc': 19, 'amenity_search': 3}
15:43:16: {'rev_geo_exc': 25, 'proto_exc': 25}
15:43:18: {'click': 1, 'rev_geo_exc': 12, 'proto_exc': 12, 'amenity_search': 15}
15:43:28: {'click': 1, 'rev_geo_exc': 45, 'proto_exc': 45}
```

Selected chronological lines:

```text
05-23 15:42:00.405 10633 10633 D net.osmand: OsmandMapTileView On click event 613.625 1225.375 {main}
05-23 15:42:18.546 10633 10633 D net.osmand: OsmandMapTileView On click event 442.375 1451.0 {main}
05-23 15:42:20.510 10633 10633 D net.osmand: OsmandMapTileView On click event 503.625 1116.375 {main}

05-23 15:42:23.740 10633 10633 I Choreographer: Skipped 217 frames!  The application may be doing too much work on its main thread.
05-23 15:42:23.746 10633 10641 I net.osmand: Background young concurrent copying GC freed 2267523(75MB) AllocSpace objects, 81(3600KB) LOS objects, 0% free, 238MB/238MB, paused 50us,24us total 3.942s
05-23 15:42:23.844 10633 12401 D net.osmand: AmenityIndexRepositoryBinary Search for 41.02363810636375 28.95645210519433 done in 73 ms found 1. {pool-9-thread-1}
05-23 15:42:23.850 10633 12401 D net.osmand: AmenityIndexRepositoryBinary Search for 41.02363810636375 28.95645210519433 done in 5 ms found 0. {pool-9-thread-1}
05-23 15:42:23.913 10633 12399 D net.osmand: AmenityIndexRepositoryBinary Search for 41.020123716575455 28.95009795203805 done in 69 ms found 0. {AsyncTask #4}
05-23 15:42:23.983 10633 10641 I net.osmand: Background concurrent copying GC freed 6309482(184MB) AllocSpace objects, 53(5728KB) LOS objects, 62% free, 57MB/153MB, paused 86us,20us total 236.647ms

05-23 15:42:33.570 10633 10633 D net.osmand: OsmandMapTileView On click event 441.625 1197.625 {main}
05-23 15:42:36.310 10633 10633 D net.osmand: OsmandMapTileView On click event 559.625 1313.25 {main}
05-23 15:42:38.200 10633 10633 D net.osmand: OsmandMapTileView On click event 691.75 1265.75 {main}
05-23 15:42:38.220 10633 12400 E net.osmand: CurrentPositionHelper Exception happened during reverse geocoding {pool-11-thread-1}
05-23 15:42:38.220 10633 12400 E net.osmand: com.google.protobuf.InvalidProtocolBufferException: While parsing a protocol message, the input ended unexpectedly in the middle of a field.  This could mean either than the input has been truncated or that an embedded message misreported its own length.

05-23 15:42:41.202 10633 10633 I Choreographer: Skipped 202 frames!  The application may be doing too much work on its main thread.
05-23 15:42:41.208 10633 10641 I net.osmand: Background young concurrent copying GC freed 2684792(86MB) AllocSpace objects, 71(3372KB) LOS objects, 0% free, 157MB/157MB, paused 2.787ms,42us total 4.391s
05-23 15:42:41.221 10633 10646 I OpenGLRenderer: Davey! duration=1688ms; Flags=0, FrameTimelineVsyncId=142298572, IntendedVsync=175936878268333, Vsync=175938561601599, InputEventId=0, HandleInputStart=175938563228360, AnimationStart=175938563230912, PerformTraversalsStart=175938563351225, DrawStart=175938563414767, FrameDeadline=175936891934999, FrameInterval=175938563135183, FrameStartTime=8350457, SyncQueued=175938563486069, SyncStart=175938563551902, IssueDrawCommandsStart=175938563730913, SwapBuffers=175938564543986, FrameCompleted=175938566433152, DequeueBufferDuration=16198, QueueBufferDuration=1077084, GpuCompleted=175938566324142, SwapBuffersCompleted=175938566433152, DisplayPresentTime=175937586894930, CommandSubmissionCompleted=175938564543986,
05-23 15:42:41.288 10633 12559 D net.osmand: AmenityIndexRepositoryBinary Search for 41.00443473292014 28.953374605625868 done in 59 ms found 0. {AsyncTask #7}
05-23 15:42:41.295 10633 12559 D net.osmand: AmenityIndexRepositoryBinary Search for 41.00443473292014 28.953374605625868 done in 7 ms found 0. {AsyncTask #7}
05-23 15:42:41.345 10633 12559 D net.osmand: AmenityIndexRepositoryBinary Search for 41.00668226307249 28.950396347790956 done in 50 ms found 0. {AsyncTask #7}
05-23 15:42:41.418 10633 12559 D net.osmand: AmenityIndexRepositoryBinary Search for 41.01117709341216 28.944439832121134 done in 65 ms found 0. {AsyncTask #7}

05-23 15:42:42.550 10633 10633 D net.osmand: OsmandMapTileView On click event 662.75 1409.75 {main}
05-23 15:42:42.580 10633 12400 E net.osmand: CurrentPositionHelper Exception happened during reverse geocoding {pool-11-thread-1}
05-23 15:42:42.580 10633 12400 E net.osmand: com.google.protobuf.InvalidProtocolBufferException: While parsing a protocol message, the input ended unexpectedly in the middle of a field.  This could mean either than the input has been truncated or that an embedded message misreported its own length.
05-23 15:42:42.724 10633 12581 D net.osmand: AmenityIndexRepositoryBinary Search for 41.00100712083282 28.94570667296648 done in 36 ms found 0. {AsyncTask #9}
05-23 15:42:42.755 10633 12581 D net.osmand: AmenityIndexRepositoryBinary Search for 41.00325464136956 28.942728582769632 done in 25 ms found 0. {AsyncTask #9}
05-23 15:42:42.805 10633 12581 D net.osmand: AmenityIndexRepositoryBinary Search for 41.00774957901092 28.936772234737873 done in 44 ms found 0. {AsyncTask #9}

05-23 15:42:48.119 10633 10633 D net.osmand: OsmandMapTileView On click event 579.0 1391.875 {main}
05-23 15:42:48.156 10633 12400 E net.osmand: CurrentPositionHelper Exception happened during reverse geocoding {pool-11-thread-1}
05-23 15:42:48.156 10633 12400 E net.osmand: com.google.protobuf.InvalidProtocolBufferException: While parsing a protocol message, the input ended unexpectedly in the middle of a field.  This could mean either than the input has been truncated or that an embedded message misreported its own length.
05-23 15:42:48.269 10633 12604 D net.osmand: AmenityIndexRepositoryBinary Search for 41.002922040995145 28.933046646416187 done in 52 ms found 0. {AsyncTask #11}
05-23 15:42:48.306 10633 12581 D net.osmand: AmenityIndexRepositoryBinary Search for 41.002922040995145 28.933046646416187 done in 37 ms found 1. {AsyncTask #9}
05-23 15:42:48.391 10633 12581 D net.osmand: AmenityIndexRepositoryBinary Search for 41.00516962273773 28.930068388581276 done in 40 ms found 5. {AsyncTask #9}
05-23 15:42:48.486 10633 12581 D net.osmand: AmenityIndexRepositoryBinary Search for 41.009664556259594 28.924111872911453 done in 53 ms found 20. {AsyncTask #9}

05-23 15:42:52.453 10633 10633 D net.osmand: OsmandMapTileView On click event 575.375 1438.625 {main}
05-23 15:42:52.471 10633 12400 E net.osmand: CurrentPositionHelper Exception happened during reverse geocoding {pool-11-thread-1}
05-23 15:42:52.471 10633 12400 E net.osmand: com.google.protobuf.InvalidProtocolBufferException: While parsing a protocol message, the input ended unexpectedly in the middle of a field.  This could mean either than the input has been truncated or that an embedded message misreported its own length.
05-23 15:42:52.563 10633 12581 D net.osmand: AmenityIndexRepositoryBinary Search for 41.002922040995145 28.933046646416187 done in 29 ms found 1. {AsyncTask #9}
05-23 15:42:52.604 10633 12615 D net.osmand: AmenityIndexRepositoryBinary Search for 41.002922040995145 28.933046646416187 done in 41 ms found 0. {AsyncTask #12}
05-23 15:42:52.656 10633 12581 D net.osmand: AmenityIndexRepositoryBinary Search for 41.00516962273773 28.930068388581276 done in 52 ms found 5. {AsyncTask #9}
05-23 15:42:52.706 10633 12615 D net.osmand: AmenityIndexRepositoryBinary Search for 41.00516962273773 28.930068388581276 done in 49 ms found 0. {AsyncTask #12}
05-23 15:42:52.778 10633 12581 D net.osmand: AmenityIndexRepositoryBinary Search for 41.009664556259594 28.924111872911453 done in 72 ms found 20. {AsyncTask #9}
05-23 15:42:52.840 10633 12615 D net.osmand: AmenityIndexRepositoryBinary Search for 41.009664556259594 28.924111872911453 done in 61 ms found 0. {AsyncTask #12}

05-23 15:42:57.852 10633 10633 D net.osmand: OsmandMapTileView On click event 533.375 1279.0 {main}
05-23 15:42:57.876 10633 12400 E net.osmand: CurrentPositionHelper Exception happened during reverse geocoding {pool-11-thread-1}
05-23 15:42:57.876 10633 12400 E net.osmand: com.google.protobuf.InvalidProtocolBufferException: While parsing a protocol message, the input ended unexpectedly in the middle of a field.  This could mean either than the input has been truncated or that an embedded message misreported its own length.

05-23 15:43:04.337 10633 10633 D net.osmand: OsmandMapTileView On click event 434.625 947.875 {main}
05-23 15:43:04.376 10633 12400 E net.osmand: CurrentPositionHelper Exception happened during reverse geocoding {pool-11-thread-1}
05-23 15:43:04.376 10633 12400 E net.osmand: com.google.protobuf.InvalidProtocolBufferException: While parsing a protocol message, the input ended unexpectedly in the middle of a field.  This could mean either than the input has been truncated or that an embedded message misreported its own length.

05-23 15:43:16.016 10633 12400 E net.osmand: CurrentPositionHelper Exception happened during reverse geocoding {pool-11-thread-1}
05-23 15:43:16.016 10633 12400 E net.osmand: com.google.protobuf.InvalidProtocolBufferException: While parsing a protocol message, the input ended unexpectedly in the middle of a field.  This could mean either than the input has been truncated or that an embedded message misreported its own length.

05-23 15:43:18.179 10633 10633 D net.osmand: OsmandMapTileView On click event 621.375 1310.0 {main}
05-23 15:43:18.196 10633 12400 E net.osmand: CurrentPositionHelper Exception happened during reverse geocoding {pool-11-thread-1}
05-23 15:43:18.196 10633 12400 E net.osmand: com.google.protobuf.InvalidProtocolBufferException: While parsing a protocol message, the input ended unexpectedly in the middle of a field.  This could mean either than the input has been truncated or that an embedded message misreported its own length.

05-23 15:43:28.233 10633 10633 D net.osmand: OsmandMapTileView On click event 660.375 1401.5 {main}
05-23 15:43:28.260 10633 12400 E net.osmand: CurrentPositionHelper Exception happened during reverse geocoding {pool-11-thread-1}
05-23 15:43:28.260 10633 12400 E net.osmand: com.google.protobuf.InvalidProtocolBufferException: While parsing a protocol message, the input ended unexpectedly in the middle of a field.  This could mean either than the input has been truncated or that an embedded message misreported its own length.
```

**Comment by Zirochkabila** [comment]
@tudos4 A separate issue has been created based on your comment https://github.com/osmandapp/OsmAnd/issues/25137
