### ISSUE TITLE
Show elevation of a location different from current location

### ISSUE THREAD

**Issue by littlehelper** [osmandapp/OsmAnd#2487]
If I am right, currently, it is only possible to determine the elevation of a location which is different from the current location by "reading" the contour lines.
It would be great if Osmand would be able to look up and display the elevation of a location e.g. selected with a long tap on the map. This would allow a kind of straight line bearing to a destination point in the 3rd dimension in addition to #2447.

**Comment by sonora** [comment]
This is implemented now for taps on POIs which are tagged with `ele`.

For any arbitrary point, there is no immediate data available to perform this, it would have to be done by e.g. interpolating data we have in the contour line plugin. This is not immediately straightforward, though.

**Comment by littlehelper** [comment]
Could the elevation data used for alculated routes (thanks for this impressive new feature!) be reused for determining the altitude of arbitrary locations (e.g. marker's altitude, #3183)? Or at least to determine the altitude of a point along/near a highway/path?

**Comment by rogersride** [comment]
Locus Maps has option to show current elevation at the cursor.

**Comment by wolfwehl** [comment]
An altitude specification by linear interpolation of neighboring contour lines would of course be the perfect solution. However, it would be helpful to specify the neighboring contour lines, for example "altitude between 340 and 350 m".

**Comment by vshcherb** [comment]
Fixed with new widget added for heightmap (new map should be downloaded)

**Comment by gauffke** [comment]
Apologies, I’m not finding the feature in the last version of OSMAnd on iOS. At least not when I select a random point. Can you please help me locate the feature, if it isn’t deed available? Thanks!

**Comment by DmitryAlexei** [comment]
@gauffke 
see https://osmand.net/docs/user/widgets/info-widgets#-elevation-map-center

**Comment by gauffke** [comment]
Thanks so much @DmitryAlexei , I could enable development info, enable height maps, I can for example see the FPS info, but the altitude at map center is still not part of the options. Did I miss something?
Thank you again

**Comment by koenigpa** [comment]
Hi, I am wondering why the elevation in the map center is not available specifically in the documented "Elevation Map center widget".

1. Even though I followed all comment previous the Elevation Map center Widget looks not like to be available in the IOS-Osmand 4.6.6.1 distribution or is it still not available? It would be consistent to provide this feature along with the Elevation local position widget since the related widgets regarding current position coordinates and map center coordinates are available to be used in the screen configuration features.
2. Since when you are enabled to record and to use tracks where altitude/slope details are provided, I guess that the calculation of the elevation map center value can be derived from the contour lines even though it may carry some precision lacks.
Would there be a way to correct this ?
Thanks

**Comment by koenigpa** [comment]
Hi,I surely would like to configure It but It is NOT offered in the screen configuration menu "add widget/ajouter un gadget" command with the Topography Extension enabled as you can see it in the attaches screen-copies where you have 2 choices for the Coordinates widgets (Local position, Center map) and only one for the Altitude/Elevation widget (local position)BRPascal KOENIG0687247809Le 13 mai 2024 à 15:00, DmitryAlexei ***@***.***> a écrit :﻿
@koenigpa The elevation map center widget can be enabled after the Topography plugin is turned on.
OsmAnd 4.7 is also available in the Apps Store.

**Comment by scaidermern** [comment]
> Hi,I surely would like to configure It but It is NOT offered in the screen configuration menu "add widget/ajouter un gadget" command with the Topography Extension enabled

Check if you have Rendering Engine v2 (OpenGL) enabled in the OsmAnd settings. With v1 this widget is not available (I don't know why, though).

**Comment by koenigpa** [comment]
I do not have any mean to check this graphical rendering feature but I am on my Iphone12 mini with the latest updates.But looking at the logs It looks like to me that there are none resolved issues in the Application Build (here 4.7.5.5 now) where there are some strange records in the log mentionning phrase.xml missing for fr-FR and also this one:2024-05-13 15:51:51.457 OsmAnd Maps[30145:8818295] Could not load the "widget_coordinates_latitude_north_day.png" image referenced from a nib in the bundle with identifier "net.osmand.maps"Some duplicate Fields messages for icon,groug_name,… in point, track tablePascal KOENIG0687247809Le 13 mai 2024 à 15:27, Alexander Heinlein ***@***.***> a écrit :﻿

Hi,I surely would like to configure It but It is NOT offered in the screen configuration menu "add widget/ajouter un gadget" command with the Topography Extension enabled

Check if you have Rendering Engine v2 (OpenGL) enabled in the OsmAnd settings. With v1 this widget is not available (I don't know why, though).

**Comment by DmitryAlexei** [comment]
Cannot reproduce with OsmAnd TestFlight 4.7.6.1
- changed app language to French
- Topography plugin turned on
Probably you need to "reset to default" (Go to menu > settings > your profile > reset to default) your profile or try to export my profile (it has 2 Elevation: map center widgets added to both right and left panels). Simply delete .txt extension and import profile settings to OsmAnd.
[Browse map1.osf.txt](https://github.com/osmandapp/OsmAnd/files/15299397/Browse.map1.osf.txt)

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/eebf1f89-5997-4df3-aa4f-5f1c366b0b5c"  width="300" height="auto"/> </td>
  </tr>
</table>
