### ISSUE TITLE
On turn left: Coming Streetname not displayed on intersection with divided ways.

### ISSUE THREAD

**Issue by CJTmmr** [osmandapp/Osmand#2725]
Using nigthly; OsmAnd offline routing.

On a simple intersection, taking a left turn the coming streetname (or destination) is correctly displayed the last 500m (or so) in the topbar; together with a small left-turn-icon.

At intersections with divided ways the new (coming) streetname (or destination) with left-arrow-icon  is not (always) shown in the topbar.
The current streetname is displayed instead. 
Only on the last few meters the new streetname/destination is shown.
The voice-announcement is always correct, like "in 500m meter turn left to **new streetname**"

Example; [this route](http://www.openstreetmap.org/directions?engine=osrm_car&route=52.12089%2C4.67498%3B52.12135%2C4.67721#map=18/52.12085/4.67610)
![image](https://cloud.githubusercontent.com/assets/15076257/16179534/01ece1b2-3669-11e6-9f46-298db23788e7.png)
(screenshot is somewhat older; turn:lanes-issue is fixed already; streetname-behavior is still the same)
Topbar shows "Oranje Nassausingel"
It should show: small left-turn icon "Oostkanaalweg"
The voice announcement is like : "In 50 meters turn left to Oostkanaalweg"

BTW: I tried to make screenshots with "simulate position", but no topbar with streetname is shown at all in simulation; also all turn-lanes are displayed gray all the time.

**Comment by vshcherb** [comment]
It looks old cause the same issue was fixed 2 weeks ago. Please check with latest nightly or you will get it in the next release.

**Comment by CJTmmr** [comment]
This morning I could make some fresh screenshots on several locations.
Using nightly from today 20-06-2016 00.58u.

The next turn (to the left)  and next streetname are not in the topbar.
I think the next streetname is very usefull.

Note: also a tiny turn:lanes issue remains, when left-turn and through are one lane.

Location 1 - taking [this turn](http://www.openstreetmap.org/directions?engine=osrm_car&route=52.02707%2C4.71832%3B52.02615%2C4.71980#map=18/52.02666/4.71880)
![2016-06-20 06 15 25](https://cloud.githubusercontent.com/assets/15076257/16206760/1c75456c-372a-11e6-999f-0e2a4219fabc.png)


Location 2 - taking [this turn](http://www.openstreetmap.org/directions?engine=osrm_car&route=52.01665%2C4.70939%3B52.01529%2C4.71102#map=18/52.01599/4.71026)
![2016-06-20 06 23 21](https://cloud.githubusercontent.com/assets/15076257/16206846/9b3bb44e-372a-11e6-8ea6-e520373d7f60.png)

Location 3 - taking [this turn](http://www.openstreetmap.org/directions?engine=osrm_car&route=52.01748%2C4.70940%3B52.01843%2C4.70759#map=18/52.01788/4.70875)
![2016-06-20 06 38 59](https://cloud.githubusercontent.com/assets/15076257/16206881/d0e6ac20-372a-11e6-81c0-1a099742a6ec.png)

Location 4 - making [this turn](http://www.openstreetmap.org/directions?engine=osrm_car&route=52.33066%2C4.64933%3B52.32841%2C4.64993#map=18/52.32963/4.64892)
![2016-06-20 08 47 32](https://cloud.githubusercontent.com/assets/15076257/16206928/fa8d27e8-372a-11e6-8d04-08a632220043.png)

**Comment by vshcherb** [comment]
Next street name should be in top bar, but I think street name is again issues for these complex intersections. Where we display not the last streets after all intersections but the street name after first intersection and it changes once you pass each intersection practically every 10 meters.] So it is worth to open separate issue for turn lanes.
Looking into turn lanes...

**Comment by vshcherb** [comment]
@xmd5a2 could you please create a test for Location 4 (actually all the locations represent the same issue) and because we didn't had test for it, I think it was working properly but after some iterations this become broken.

**Comment by xmd5a2** [comment]
@vshcherb test added
