### ISSUE TITLE
Wrong localization of highway names in offline maps: often default not chosen, random language instead

### ISSUE THREAD

**Issue by Piskvor** [osmandapp/Osmand#2864]
What version of OsmAnd are you using, on what device and Android/iOS version?
OsmAnd 2.3.5, on stock Android 4.4.4 and stock Android 6.0.1; same behavior in both.

Do you use the offline maps offered within the OsmAnd app for download, or online (tile / raster) maps?
Yes - manifests in app's offline maps only. Does not manifest in online OsmAnd tiles.

If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs, and its edition date.
Czech Republic Prague (1.7.2016)
Czech Republic Prague - Roads only (1.7.2016)
Czech Republic (1.6.2016)
- Set app language to English (either from device language or explicitly) and/or map rendering language is set to English (either from app language or explicitly)
- go to a viewport that contains multilanguage highway names (e.g. these streets, but seems to be general)
  -The streets do not have `name:en` tag, so the default `name` is used. This is correct behavior:
  ![osmand_en_jecna](https://cloud.githubusercontent.com/assets/917239/17104321/b04dd966-5282-11e6-931d-533a2fead38c.png)
- Set app language to Czech (either from device language or explicitly) and/or map rendering language is set to Czech (either from app language or explicitly)
- go to a viewport that contains multilanguage highway names (e.g. these streets, but seems to be general)
- the renderer picks an apparently random (first?) language tag for rendering the name, even though there is a `name` tag. **This is the bug.**
  ![osmand_cs_jecna](https://cloud.githubusercontent.com/assets/917239/17104290/855d76ee-5282-11e6-9524-7c11bce10e05.png)

See these streets for an example (both are in the viewport here)
- https://www.openstreetmap.org/way/335024354
  name=Lipová
  name:ru=    Липовая улица
- https://www.openstreetmap.org/way/27299132
  name=Ke Karlovu
  name:de=Karlshof

Why is this wrong?
The Czech name is not similar to the German or Russian names, so the rendered map is highly confusing.

What should have happened?
The renderer should "fall back to `name`" (like when set to English), not "randomly pick one from `name:*`, even though there isn't the right language".
Compare the "Ke Karlovu" x "Karlshof" and "Lipová" x "(something in Cyrillic)" in screenshots.

This bug also does not appear in online tiles - the default `name` is used everywhere:
![osmand_online_jecna](https://cloud.githubusercontent.com/assets/917239/17104394/07c5b484-5283-11e6-95c3-5d02f40b6ea6.png)

Perhaps interesting: scrolling/zooming the map forces a re-render, which _sometimes_ gets the names right, sometimes not. Note the top+bottom "Karlovo náměstí"/"SФMЗTHIИG SФMЗTHIИG", even though both highways are named the same:
![sidesync_capture_20160725164449_1](https://cloud.githubusercontent.com/assets/917239/17105361/37855fd6-5287-11e6-8fbd-5c62234ca8b7.jpg)

**Comment by Piskvor** [comment]
Interesting. Deleting all maps and redownloading, I can no longer reproduce this. (I have installed the app a while ago, and went through at least two upgrades and one map update.) That seems to resolve it.

**Comment by vshcherb** [comment]
There was a problem with road only maps which was fixed recently.

**Comment by Piskvor** [comment]
And it's back :(

Steps to reproduce:
1. Install OsmAnd to a new device from Google Play (Android 6.0.1, stock Samsung Galaxy S5, never rooted), do not make any changes to settings
2. Download map: Czech Republic
3. Search "Katerinska 9, Praha"
4. Click the found location "Kateřinská 1528/9, Praha"

Expected behavior:
5. Street names are **displayed in chosen language** where tagging is available (in this case: automatically determined from device: (cs)) - OSM tag `name:cs`; **if that is not available, displayed in default language** - OSM tag `name`. As `cs` is the local language, the default name is in almost all cases synonymous with the Czech name and there is mostly no `name:cs` (which would duplicate the content of the `name`). In other words, the display logic should not assume that the user wants to see *n* additional languages, and only decide based on the currently selected one.

Expected decision tree (with `xy` as a placeholder for user's selected language):
5a.: tag `name:xy` is present: show content of tag `name:xy`; break
5b.: tag `name:xy` is not present, but tag `name` is present: show content of tag `name`; break
5c.: **iff** none of these tags are present: only now can the renderer start guessing, as it does currently (this is an edge case - where `name:*` tags are present, `name` is very likely to exist as well; this would manifest only in multilingual places where no single language has official precedence; **not** on any street that happens to have a `name` and `name:*`)

Actual behavior:
5. Even though the **default (`name`) is available**, street names are displayed in *any* language whatsoever (`name:ru`,`name:de`,`name`, apparently at random). The content of `name` is only shown when *no* other language is available. This is a bug - language namespaces in OSM exist to *augment* the default features by providing alternate-language where it is requested, not to confuse map readers by presenting a Babylonian jumble of randomly chosen languages: there is no reason for showing them unless the user has `de` or `ru` locale selected.

Attached is a screenshot from OsmAnd:
![screenshot_2017-05-19-13-42-10](https://cloud.githubusercontent.com/assets/917239/26247348/c5cb061e-3c9d-11e7-83f3-00e4d64e2bfc.png)

- _Na Rybníčku_ http://www.openstreetmap.org/way/4929898 has `name` and `name:de`, which leads to German name being rendered.
- _Lípová_ http://www.openstreetmap.org/way/335024354 has `name` and `name:ru`, leading to Russian rendering.
- In contrast, the main east-west road _Ječná_ http://www.openstreetmap.org/way/335024357 has `name` and `name:ru`, but renders using the default name
-  And most interestingly, _V Tůních_ http://www.openstreetmap.org/way/16787271 renders using *both* `name` and `name:de`.

The rendering does vary a bit with zoom and pan - with a bit of zooming, I managed to get a segment of Ječná to render in Russian, while another segment (just going off the eastern edge) renders the default:
![screenshot_2017-05-19-14-22-02](https://cloud.githubusercontent.com/assets/917239/26247611/038fc204-3c9f-11e7-9d32-1badfdda7329.png)

To contrast, a screenshot from OsmAnd Map Creator, apparently using only `name`:
![screenshot_20170519_134419](https://cloud.githubusercontent.com/assets/917239/26247309/9fa9b494-3c9d-11e7-88f6-23f414481d1d.png)

**Comment by Piskvor** [comment]
Perhaps another interesting test case is the Charles Bridge (appx. east-west, `name=Karlův most`; http://www.openstreetmap.org/way/132415117 and http://www.openstreetmap.org/way/4053134 ), which has *many* language tags - at different zoom levels, OsmAnd renders it in English, German, Hungarian, Czech (or 
default?), and what I think is Chinese.
![screenshot_20170519_144438](https://cloud.githubusercontent.com/assets/917239/26248387/771d7100-3ca2-11e7-9664-5dcbdbdfe899.png)

![screenshot_2017-05-19-14-42-14](https://cloud.githubusercontent.com/assets/917239/26248410/8f353aac-3ca2-11e7-88ef-7b855d490db6.png)

**Comment by Piskvor** [comment]
Choosing [map icon]-[map language]-[Czech] doesn't seem to solve the issue: names are rendered the same way in whatever alternate language is available, just like when [local names] is selected.
Choosing [map icon]-[map language]-[Czech+override if missing] doesn't solve this either - default names are not rendered, but a *different* set of alternate names is chosen; in some places the renderer chooses an even weirder algorithm: takes `name:ru` and transliterates it to Latin characters (all the way to ASCII, apparently replacing any diacritics); yet keeps avoiding the easy and obvious choice of `name` if there's any alternate language at all.
![screenshot_2017-05-19-15-04-02](https://cloud.githubusercontent.com/assets/917239/26248925/78a21d94-3ca4-11e7-8fe6-28259ff26c50.png)

**Comment by Piskvor** [comment]
Issue only manifests if Prague:road map or Czech Republic:road map is activated. If I backup those, and activate the full Czech Republic or Prague map, the issue does not appear.

**Comment by Piskvor** [comment]
Also, all maps work correctly in Safe mode (but I have trouble keeping it on - after restart, the Safe Mode box is always unchecked).

**Comment by vshcherb** [comment]
Fixed
