### ISSUE TITLE
OsmAnd+ 2.4: Sometimes changed marker position cannot be confirmed

### ISSUE THREAD

**Issue by Norbert80** [osmandapp/Osmand#2929]
There is a new feature introduced with OsmAnd 2.4 that shall allow to change the position of markers. Sometimes (sporadically) AFTER PRESSING OK, the windows does not close. A windows with only CANCEL option stays open. After pressing CANCEL the marker jumps back to the old position.

Found with OsmAnd+ 2.4.2.
![screenshot_2016-08-09-21-47-53](https://cloud.githubusercontent.com/assets/6921696/17531535/921b6124-5e7c-11e6-940c-756828877a68.png)
![screenshot_2016-08-09-21-47-58](https://cloud.githubusercontent.com/assets/6921696/17531534/9214e2d6-5e7c-11e6-88da-bc1d63c0a201.png)

**Comment by Norbert80** [comment]
@vshcherb Are there aby raleted Patches in OsmAnd+ 2.4.3? I can't reproduce this bug anymore.

**Comment by vshcherb** [comment]
It was fixed in 2.4.3

**Comment by Norbert80** [comment]
@vshcherb
Now I see this bug again with OsmAnd+ 2.4.3. Please re-open.

**Comment by vshcherb** [comment]
I can not reproduce it any more, though by the time it was opened I was able to see it. I think it is my mistake and it didn't make to 2.4.3, so I expect it will be 2.4.4. Please test nightly build.

**Comment by Norbert80** [comment]
I can confirm that this one is fixed since build 2.4.4.

**Comment by Norbert80** [comment]
@vshcherb This issue is back in OsmAnd + 2.5. Please re-open it.

**Comment by Norbert80** [comment]
At least the big orange marker is affected.

**Comment by vshcherb** [comment]
Can't reproduce please share screenshots

**Comment by Norbert80** [comment]
Hi Victor,

attached you find the requested screenshots.
(I cannot log in to GitHub during my holidays, sorry.)


Regards
Norbert

Am 30. Oktober 2016 15:21:20 GMT+00:00, schrieb vshcherb <notifications@github.com>:
>Can't reproduce please share screenshots
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/osmandapp/Osmand/issues/2929#issuecomment-257157372

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by sonora** [comment]
I have tried hard, but cannot reproduce either. Must depend on some rather special circumstances or configuration.

**Comment by Norbert80** [comment]
@vshcherb attached you find the requested screenshots that I already have sent you by mail. Sorry for the late response
![screenshot_2016-10-28-15-56-22](https://cloud.githubusercontent.com/assets/6921696/20056156/183074ee-a4e5-11e6-8a3f-4388ba2c997c.png)
![screenshot_2016-10-30-17-12-36](https://cloud.githubusercontent.com/assets/6921696/20056157/1830cebc-a4e5-11e6-8cac-45aad56eb02a.png)
![screenshot_2016-10-30-17-12-52](https://cloud.githubusercontent.com/assets/6921696/20056158/1830f054-a4e5-11e6-8462-a80abab8decd.png)


. I have been on vacation.

**Comment by sonora** [comment]
So your are saying the "Apply" button is missing. I assume this is exactly in cases where the Lat + Lon display above it is stretched out over 2 lines?

**Comment by Norbert80** [comment]
@sonora not really.

But I found another related problem that may trigger that faulty behavior. On the canary islands map I see this problem regularly.

If I click for example the "Holiday Worlds" in the search results (or if I click the icon of the "Holiday World" which is a new feature of OsmAnd 2.5) to set the marker I found that the marker is miss-positioned. From now on during the same OsmAnd session (no app re-start) if I set the marker to any ('non-snapped')  position, I experience the bug with the missing "Apply" button.
![screenshot_2016-11-07-20-57-49](https://cloud.githubusercontent.com/assets/6921696/20074738/d41b5fce-a531-11e6-9fd9-fecb2c21c903.png)

**Comment by sonora** [comment]
Norbert, I think the marker when tapping a feature associated with an area is placed in the center of the enclosing area (this is a theme park), which is not necessarily where the icon of related points is shown.

I have just tried to reproduce with my September 1 Spain map, but still cannot ...

**Comment by Norbert80** [comment]
@sonora I use the canary islands map. Did you also try with that

**Comment by sonora** [comment]
Yes. It's not a map issue, I think. Could be specific to certain hardwares' screen resolution, not sure.

**Comment by sonora** [comment]
PS: Is it the same in landscape mode?

**Comment by Norbert80** [comment]
@sonora I see experience this bug also in landscape mode.

**Comment by Norbert80** [comment]
It seem to be really related with the new feature to select POI icons. I experienced that the screen orientation change back to portrait mode has reset (removed) the bug.

The bug occurred again after selection such a POI with a difference in marker position. POI with correct marker positions seem not to trigger the bug.

**Comment by Norbert80** [comment]
@sonora please note that the Apply button vanishes **after** clicking on it. Could tis be the reason why you cannot reproduce it?

**Comment by Norbert80** [comment]
@crimean thanks for working on these problems. Does your fix cover the vanishing Apply button or does it only cover the line break?

**Comment by crimean** [comment]
@Norbert80 Sorry, it was not complete fix. The Apply button should work ok now.

**Comment by Norbert80** [comment]
@crimea thanks!

**Comment by Norbert80** [comment]
@sonora I think found the out why you couldn't reproduce the bug.

I had spain map an canary islands map installed at the same time while when I experienced this bug on the canary islands. So this are was covered with two maps.

Since I have deleted the canary islands map I do.no more experience the bug.

So it looks like this bug happens on areas with overlapping maps.

**Comment by Norbert80** [comment]
@vshcherb @sonora
Now you should have alle information to reproduce the bug and re-open it. Please let me know if you can reproduce it know or if you need a step-by-step instructions.

**Comment by sonora** [comment]
@Norbert80  I have just tried with both Spain and Canary Island maps active, and find no problem ...

Are you sure you can still reproduce it?

**Comment by Norbert80** [comment]
@sonora I installed Canary Islands map again in addition to the Spain on OsmAnd+ 2.5.4. I haven't been able to reproduce the bug anymore. So we can keep this issue closed.

I will update this issue if I experience the bug again in future.

**Comment by sonora** [comment]
Ok, thanks!
Best, Hardy
