### ISSUE TITLE
Creation/deletion of favourites takes too long

### ISSUE THREAD

**Issue by Zahnstocher** [osmandapp/Osmand#2999]
I am a OSM mapper and I use OsmAnd also very often for OSM mapping.
Especially because of the live map updates, FIXME layer and the background tile layer it is a very good tool for OSM mappers.
But there have been some changes, which make the creation/deletion of favourites much too slow.

There are three reasons, why creation/deletion of favourites is that slow:
1. Forced reverse geocoding.
2. Every time a favourite is created or deleted, a new packed bz2 backup is created, this takes very long.
If I remember correctly, favourites are already stored in a database and exported as GPX.
The database alone and a delayed GPX export should be robust enough.
3. If a duplicate favourite is created, an annoying message appears, that the favourite has been renamed, which I have to close every time.
This is often the case, if I capture house numbers (many duplicates).

I really hope the experience for OSM mappers could be improved.
Especially high speed house number capturing, for example if I am in a bus, tram or car, is simply not possible anymore.
Maybe make it possible to turn off this feature, which I usually don't need (reverse geocoding, favourites backup, duplicates message)?

**Comment by vshcherb** [comment]
Yes it could. Though we don't plan to improve it in the context of favorites but rather with Map Markers. We plan to provide more functionality to map markers and make them much faster to create and export as GPX. So each approach have pros and cons, so it is an opened discussion

**Comment by Friptick** [comment]
This is now a **completely showstopping regression** for me, after I upgraded to Osmand 3.6.3 (Android 8, mid-range 2017 Samsung).

**14 seconds for a creation or deletion operation!** (Before it was ~3, already a bit painful). Unusable.

I have a large but not astronomical number of favorites (~800).

I will now have to revert permanently to a legacy version of Osmand. Favorites are the reason I have used Osmand continuously for 8 years, but they do not seem to be a priority for the Osmand team.

Very disappointing. :(

**Comment by scaidermern** [comment]
>     3. If a duplicate favourite is created, an annoying message appears, that the favourite has been renamed, which I have to close every time.
>        This is often the case, if I capture house numbers (many duplicates).

Just a suggestion: Try to use the track recording plugin for mapping. Then instead of adding favorites you add GPX points. You can place them at any point you like, not just the current position. This will then lead to a GPX file which can be loaded in JOSM or any other OSM editor. Should be easier than dealing with favorites.

**Comment by Friptick** [comment]
@vshcherb Any idea why this problem got exponentially worse with 3.6.3?

I can't find any clues in the release notes, which seem to be mostly about navigation features as usual (which I do not use). Maybe something to do with:

- "Support of custom icons for GPX + Home / Work icons for favorites"?
- "Align with cm-precision POI icons and display text to fit the borders on the map"?

Something has been changed which is caused a huge (400%) increase in the drawing time for favorites. Can't see other bug reports (yet), so I guess the problem is a factor of the number of favorites (I have quite a lot).

Ideas for other culprits, or a workaround?

Sorry to be a pest. Only, I have used this app for nearly a decade constantly, including Osmand Live and to edit OSM, and this is the first time I have had to roll back a version because it has become unusable.

**Comment by sonora** [comment]
I have to say I have long been frustrated with our dual concept and maintenance of both "Favorites" and "Map markers". Over the years, I have seen many users not understanding the difference, and/or using just one system and missing features they would have found in the other.

I wish we came to a conclusion to unify both features into just 'Favorites' by combing the pros of each (Map markers essentially just being "temporary favorites"), and then optimize that to performance and perfection?

**Comment by Friptick** [comment]
Agreed, @sonora. Over the years I have tried everything to make Osmand do what I want it to do (my use case has never changed). In the end resorting to pestering the devs (#7473, #8044).

One fundamental issue is that Osmand has different user constituencies. Profiles are a great idea for addressing that fact. But still, the priority is definitely going to drivers and outdoor sportspeople, rather than pedestrians and tourists and transit users, who might just want better static POI features.

But whatever, I guess choices had to be made. This issue was the final straw unfortunately.

**Comment by vshcherb** [comment]
There are  substantial differences between Markers and Favorites, there is a guess that 1 person may be use only one of them Markers (I prefer markers) or Favorites but it only proves that both Markers / Favorites will stay for **a long time**.
 One of the key features of markers to be able to add it in 1 click and remove as well. Which is not a feature for favorites cause you need to enter the name unless some quick actions are used.

Over last 3 years the focus has been shifted to move Favorites close to GPX files (Trips). In the future Favorites will be accessible as just another GPX-file (like favorites.gpx). 

Anyway markers functionality that is related to linking Favorites or GPX will be simplified.

**Comment by sonora** [comment]
Well, as I said,we can collect the advantages of all systems and combine into one system / UI, this is definitely feasible, and we save maintaining two systems in the long run (UI, icons, database, performance e.g.).

Two illustrations:
- If "Not having to enter a name" is a valid use case, it can easily be solved by e.g. assigning a default name under some circumstances.
- if "handling via GPX-file" with all associated import/export/compatibility/sharing and management features is a pro of our current favorites, why not make this available to Markers as well by combining?

I tend to insist that a bold strategic decision now can bring all parties more benefit than "_both Markers / Favorites will stay for a long time._"

**Comment by vshcherb** [comment]
Markers supposed to transform as "Directions" on iOS, so basically it will be a temporarily list of points to display directions on the map. It is **ordered** in contrast to favorites / gpx how it is going to be visited. Once trip is over all points will be moved to history. 
Directions could be assigned to any point i.e. random point on the map, favorite, ...


BTW:
@sonora do you see any degradation working with big number of Favorites? I couldn't see it on my phone :(

**Comment by sonora** [comment]
Yes, back to the original issue:

Looks like it reproduces well on old devices only. Here are some benchmark figures, using last yesterday's nightly:

With 650 favorites already existing on my phone, adding a new one (I used the context menu on the map), 
- takes about 2 secs on a Samsung XCover 4s,
- and about 13 secs on a dated Samsung S4mini.

I am not sure if the latter was much faster in older app versions, but assume yes, at least at some point.

BTW: I had seen issues like the one reported here before on some installations (had reported issues for some, see e.g. #8087), and mostly they did not reproduce well across devices. I hence think we may perhaps look at corrupt databases, or maybe at databases not properly updated between versions across the years (or maybe in the process of just being updated?). Maybe deleting all favorites and re-importing from favorites.gpx would help, or resetting all of OsmAnds app data (rename the map folder before that). 

What hardware/Android is this being reported for?

**Comment by vshcherb** [comment]
Ok, we will address that issue with 3.7 release. Markers / favorites discussion is not on the roadmap for Q2 and Q3 though it is planned to change once we have more elaborate plugin structure cause some functionality from Markers is planned to be moved to plugins first.

**Comment by Friptick** [comment]
Thanks for looking into this.

>     * about 13 secs on a dated Samsung S4mini. (deletion 6 secs)

Yes, exactly the same for a 2017 Samsung J7 Prime (mid-range, ~300 USD, <3 years, still getting official OS updates, other apps run well etc, for me this is not yet obsolete hardware).

**Comment by vshcherb** [comment]
We've tested 1000 points on new phones and it looks like the biggest problem is to load / backup and save points i.e. parsing, saving file cause it becomes big. 
We also cleaned up file by removing unnecessary tags but the speed is related to the file size. So it should be the same with older versions since backup of favorites was introduced. 

So obviously we can improve it by saving into Database only but saving Favorites.gpx with backups was always our feature and I would like to keep it until it becomes extremely critical. For others I would suggest to change Favorites / with Add to GPX and then they would be managed by separate GPX files. As of today you can control UI as well.

**Comment by Friptick** [comment]
Problem completely resolved with 3.7.3.

**Comment by sonora** [comment]
Yes, completely resolved. Good job!
