### ISSUE TITLE
Weird road rendering when 'safe mode' is off

### ISSUE THREAD

**Issue by jej** [osmandapp/Osmand#3770]
Hi,
I use Osmand (2.6.3 but older 2.5 versions affected too) on Moto G4 Plus (2016). When 'safe mode' is _off_ I see a rendering problem (only at 1 or 2 zoom levels). If I turn 'safe mode' _on_ the rendering is ok (but slow...).
I attach screenshots to show the problem. It shows a portion of the Auvergne map (full map) but the problem occurs also on the France roads map (same for other countries or regions)
Thanks anyway for this wonderful app.
J.

Here the main roads are like double lanes:
![screenshot_20170512-205931](https://cloud.githubusercontent.com/assets/33821/26013140/617ef698-3757-11e7-8af7-f0419ee88530.png)

When zooming in or out it's ok:
![screenshot_20170512-205944](https://cloud.githubusercontent.com/assets/33821/26013149/6751df72-3757-11e7-8521-20a8da31bfe8.png)

**Comment by sonora** [comment]
Looks like the effect comes from different overlapping maps for the same region.
 - Are all your maps up to date, including the world overview map?
 - I think that at some time the segmentation of OSM maps for France has changed, so if you find some older maps of French regions on your device which are not from say this calender year, disabling or deleting them should solve the issue.

In general, check what maps you have activated which would cover this region, then you can temporarily disable one or more in our 'Download maps / Local tab' interface to find out which one causes this.

**Comment by jej** [comment]
Thanks for this good diagnostic.
My maps were up to date. I deleted all and downloaded it again. The problem still occurs when two (or more) maps exist for the same area, including the world map. When safe mode is off.
It means the problem occurs everywhere whatever the maps used if world map is enable. But it's not equally visible depending of the overlapping that occurs, and the level of roads' curvature.
If I enable only one single map of the area, or enable safe mode, the problem disappear.
I thought Osmand would choose and use only the best map for an area, and not a combination of all available maps data for the rendering. Quite a lot of information if 3 maps overlap?
I guess that the safe mode is involved in this problem. Or "safe mode" is more an "approximation parameter" rather than something related to "native code" performance. Because enabled or disabled the result is different.

Do you think I should uninstall completely Osmand and start again with a clean install?

Here is an example. The right circle shows two roads, there is one only.
![screenshot_20170513-232922](https://cloud.githubusercontent.com/assets/33821/26036459/726f4632-38de-11e7-9070-4c42041ffc54.png)


J.

**Comment by vshcherb** [comment]
Looks like OSM Live issue.

**Comment by vshcherb** [comment]
Duplicate to #2603

**Comment by jej** [comment]
I don't think it's exactly a duplicate. I cannot see the screenshot so not possible to tell if the visual problem is the same.
I tested on a fresh install without Osm live and the problem is the same. But it's sure that the problem disappears when safe mode is enable.

**Comment by vshcherb** [comment]
Yep my reference that problem appears at 13-14 zoom (not 15-...) it is a very common problem. Until we fix it all other problems are not that much visible
