### ISSUE TITLE
motorcar=no seems to block bicycles as well

### ISSUE THREAD

**Issue by Posteinwurf** [osmandapp/Osmand#3882]
An mysterious issue in bicycle routing: A way that is tagged "motorcar=no" is also blocked for bicycles.

![grafik](https://cloud.githubusercontent.com/assets/17393264/26790251/5cc77232-4a13-11e7-9877-987130e22a91.png)

There are also two tags barrier=bollard - it might be that these are causing the block. It even happens when I explicitly allow these tags for bicycle routing
In routing.xml:
<select value="1" t="motorcar" v="no"/>
<select value="1" t="barrier" v="bollard"/> 

I do not see any other tags that might block this way to bicycles. 

Any idea?

**Comment by aceman444** [comment]
It seems again some of your comment is missing. Did you use the xml tag codes with brackets? Please use [ ] brackets so that the codes are not lost.

Nether motorcar=* nor barrier=bollard should affect the bicycle routing mode.

**Comment by Posteinwurf** [comment]
sorry for that! The code is now displayed.

Maybe there is another explanation, but Osmand refuses to route over this way: https://www.openstreetmap.org/way/4613301. In any bicycle mode (even in "fast"). 

motorcar and bollard are the only unusual features here, so I thought that they might be the problem. But maybe it is something totally different?

**Comment by xmd5a2** [comment]
It is because of restriction https://www.openstreetmap.org/relation/3336092#map=19/52.52823/13.40931
There is a tag except=bicycle but it seems that routing does not support it.

**Comment by utack** [comment]
fwiw BRouter supports except=bicycle if it is a real issue

**Comment by Posteinwurf** [comment]
Is there an easy way to support that in Osmand routing as well?

**Comment by PaulStets** [comment]
Could not reproduce on the September maps.
![21981950_1918181581761980_1809004463_o](https://user-images.githubusercontent.com/20681525/30773099-7901c17c-a072-11e7-9614-e502bcd5a25d.png)

**Comment by Posteinwurf** [comment]
Thank you for checking! Great – maybe it is solved. I will check right away on my Osmand and come back to you.

**Comment by Posteinwurf** [comment]
I have checked now: Unfortunately, the problem still exists. It has only disappeared HERE, because the turn restriction has been deleted in the maps. https://www.openstreetmap.org/relation/3336092#map=19/52.52823/13.40931

But we still have to solve the problem in Osmand: If there is a turn restriction, with an exception for bicycles, Osmand will not recognise the exception for bicycles. Example:

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/17393264/30782054-a851075e-a12a-11e7-842e-c5cf0581ad34.png"  width="300" height="auto"/> </td>
  </tr>
</table>

Only motor vehicles are not allowed to turn left here. Bicycles are allowed to do so. But Osmand will make the crazy U-turn around the churchyard, because it cannot recognise the exception for bicycles: https://www.openstreetmap.org/relation/6479664

Best wishes

Malte

**Comment by vshcherb** [comment]
The current data format doesn't allow us to fix that issue cause we don't store restrictions with other tags so during routing we can't understand whether to use restrictions or not. They could be completely disabled but that doesn't solve the issue.

**Comment by Discostu36** [comment]
This issue really has to get a higher priority. Bike routing is useless in a city that uses this kind of restriction. 


<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/30999326/94647203-42241680-02f0-11eb-8f57-4e4240358185.jpg"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by SLMapper** [comment]
Missing handling of turn restriction exception leads to enormous detour at https://www.openstreetmap.org/relation/13818637:
(3km instead of 400m)

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104768113/234022192-ca70e00a-80e1-4e25-9a8b-817a69dd46c3.png"  width="300" height="auto"/> </td>
  </tr>
</table>

Instead it **correctly works** with online bicycle routing in OsmAnd:
- [osm de](https://routing.openstreetmap.de)
- [zlzk.biz](https://zlzk.biz)

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104768113/234022253-257628e9-76aa-463c-8b67-b2304f469937.png"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by hholzgra** [comment]
So nine years later: where are we with this? Bicycle roads with turn restrictions for motor vehicles only are becoming more common these days, there are currently almost 2000 restriction relations with an exception for bicycles in Germany: https://overpass-turbo.eu/s/2rdf

The number of actual crossings / intersections with such exception are probably a bit less than half of this, as in most cases there will be two, or even for, turn restrictions for different directions at a single intersection; but still. (E.g. here in Bielefeld we have five such locations so far, and the overpass search above returns 10 relations).

Such non-bicycle turning restrictions are supposed to prioritize and speed up bike traffic on the roads they are on, but this routing error causes the opposite effect.

All three routers on the OSM website (Graphhopper, OSRM, Valhalla) handle these restriction exceptions correctly, which also makes OsmAnd look badly here; and there has been at least one case that I know of, probably much more, where an OSM note was opened about a problem with routing restrictions, only to turn out to be an OsmAnd-only problem while the actual OSM data was perfectly correct: https://www.openstreetmap.org/note/5328349

**Comment by Posteinwurf** [comment]
@hholzgra 
Thank you for bringing this subject up again. I checked from my side, and it seems that this problem indeed hasn't been fixed.

@vshcherb 
could you prioritize this? As @hholzgra has described, this is a major bug for bicycle routing.

All the best to you
Malte

**Comment by wilfriedh** [comment]
I also noticed this bug yesterday, and I vote for fixing it!
