### ISSUE TITLE
Routing problem on roundabout

### ISSUE THREAD

**Issue by gjedeer** [osmandapp/Osmand#4345]
![osmandrouting](https://user-images.githubusercontent.com/315648/29748414-cd83310c-8b16-11e7-8d06-2a01ff84695b.jpg)

I expected the navigation to turn right roughly where the red line goes. Instead it made me take a triple left turn.

LineageOS 14.1, OsmAnd~ 2.7.5.
Map: offline Poland Aug 1, 2017, also tested Aug 27 11:06 from OSM Live
Router: offline
Profile: car
Route start: geo:53.905468,14.235191?z=18 https://osmand.net/go?lat=53.905468&lon=14.235191&z=18
Route end: geo:53.908527,14.236188?z=18 https://osmand.net/go?lat=53.908527&lon=14.236188&z=18

I also checked other engines: YOURS in osmand handles it better (right turn 90° instead of taking the shortcut). Mapzen and GraphHopper from openstreetmap.org both handled it correctly:

![selection_082](https://user-images.githubusercontent.com/315648/29748444-607cd3f0-8b17-11e7-92d5-5a8dba92732a.png)

Link to the shortcut that's not taken https://www.openstreetmap.org/way/205622572

**Comment by naoliv** [comment]
osmand could be improved for this, indeed.

But maybe that there could be some more turn restrictions in OSM too.
For exaple, is it allowed to turn from https://www.openstreetmap.org/way/207247958 to https://www.openstreetmap.org/way/233634809?

If not then it needs a turn restriction. Likewise for the other 3 cases at that crossing.

**Comment by gjedeer** [comment]
It's not prohibited to turn left there: https://www.google.de/maps/@53.9074775,14.2339408,3a,75y,334.17h,82.31t/data=!3m7!1e1!3m5!1s9tEdE4f0ZP_sWWZQeQH9hg!2e0!6s%2F%2Fgeo1.ggpht.com%2Fcbk%3Fpanoid%3D9tEdE4f0ZP_sWWZQeQH9hg%26output%3Dthumbnail%26cb_client%3Dmaps_sv.tactile.gps%26thumb%3D2%26w%3D203%26h%3D100%26yaw%3D331.89444%26pitch%3D0%26thumbfov%3D100!7i13312!8i6656

**Comment by gjedeer** [comment]
@naoliv if you have suggestions how osm can be improved here, i'll happily learn and fix the map.

**Comment by scaidermern** [comment]
Doesn't look like a bug in the data to me.

**Comment by PaulStets** [comment]
The issue happens only with 'Fastest route' option enabled. The route calculated in Fuel efficient mode is correct.
The issue is not reproducible in MapCreator either in native or Java mode:
![screenshot from 2017-09-20 18-23-18](https://user-images.githubusercontent.com/20681525/30652386-edfe9bc4-9e30-11e7-96b1-e04be6c78fa7.png)

**Comment by PaulStets** [comment]
Fixed with a43513a

**Comment by PaulStets** [comment]
Fixed https://github.com/osmandapp/OsmAnd-resources/pull/448

**Comment by gjedeer** [comment]
Thanks. @PaulStets  Send me your paypal or bitcoin address to gdr@gdr.name if you'd like a beer on me.

**Comment by PaulStets** [comment]
@gjedeer Sadly, I don't have any of those. Appreciate the offer though:)

**Comment by scaidermern** [comment]
Just curious: According to your fix this was a "simple" weighting issue of highway classes. However I guess this kind of issue can still occur at other places.

Are there currently any turn penalties considered during route calculation? The wrong route had three very sharp turns whereas the correct route has only one very smooth turn. Looks like (higher) turn penalties could avoid such situations, too.

**Comment by PaulStets** [comment]
Yes, the turn penalties are defined here: leftTurn="5" rightTurn="5". We will experiment changing those values.
