### ISSUE TITLE
Some regional cycling network node numbers not displayed

### ISSUE THREAD

**Issue by UAb5eSMn** [osmandapp/Osmand#5686]
When enabling the map configuration option 'Routes' / 'Show cycle routes', some of the regional cycling network node numbers (fietsknooppunten) aren't displayed. This is a screenshot with some missing cycling node numbers:
![cycling-network-1](https://user-images.githubusercontent.com/5942222/42843399-82ce4dc0-89ff-11e8-9ebc-3619f520e8f5.png)
The same area in OSM:
https://www.openstreetmap.org/#map=14/52.4349/6.6564&layers=C
![cycling-network-2](https://user-images.githubusercontent.com/5942222/42843405-89d840ee-89ff-11e8-8970-3e35c741584c.png)

They probably aren't displayed because something else is at the same location (street label, bench, information, picnic table, ...). Sometimes they show up when switching to a different zoom level (because street labels move), but sometimes the don't show up at all.
In my opinion, the cycling node numbers are the most important feature of the cycling routes. Could you force them to be displayed on top? If forced on top, they could obscure other items at the same location, but maybe that can be solved with a quick action to toggle all text (street labels, cycling node numbers) on/off?

Note that the hidden node numbers can still be found tapping on the map, or by searching for them:
![cycling-network-3](https://user-images.githubusercontent.com/5942222/42843425-9e1a057e-89ff-11e8-8561-ecfb61fb895e.png)
![cycling-network-4](https://user-images.githubusercontent.com/5942222/42843434-a1f51738-89ff-11e8-84b5-7e8b35ed8d2d.png)

**Comment by vshcherb** [comment]
The tags overlap with city labels mostly and city labels have higher priority

**Comment by matthijskooijman** [comment]
I've ran into the same issue as well. I would argue that, if the user enabled cycling routes explicitly, it would be appropriate to give them high priority. In the case of the Dutch regional cycling routes, this is additionally so, since signs on the road only show the node number, so the map becomes pretty pointless for use with the regional cycling network if not all node numbers are shown. Ideally, this would be fixed by, when possible, moving the city name out of the way, rather than hiding it (since the exact positioning does not usually matter much, though I'm not sure if OsmAnd currently has any mechanism for this and whether if it is feasible at all). 

Additionally, I've found there are few other causes for not displaying these node numbers (or rcn refs as they are called in OSM):
 - As mentioned, something else like a city name is in the way, which can often be fixed by zooming in closely.
 - Nodes that have a name in addition to the rcn ref, will show the name (This might be something to be fixed in osm data, though, since I can imagine that in other types of cycle routes, rcn nodes might have meaningful names that should be shown?). For example, see https://www.openstreetmap.org/node/44247896 and 
[this screenshot](https://user-images.githubusercontent.com/194491/44054841-f07891b0-9f43-11e8-9298-eeb673149758.png)
 - Nodes that have additional data might be rendered as such. For example, a node that has `traffic_calming=table` is rendered as such, rather than showing the rcn ref. This even seems to apply at zoom levels where the table icon is not normally shown, causing the node to have no table icon and no rcn ref (and after zooming in, only the table icon is shown). This is additionally harmful, since selecting the node also does not show the rcn ref (rather just "Table"). For example, see https://www.openstreetmap.org/node/43319582 and [this screenshot](https://user-images.githubusercontent.com/194491/44054619-60e59426-9f43-11e8-8410-a283c3db4136.png)
 - A variation of this might occur when there is another POI very nearby. For example, in the screenshot shown in the first post, rcn ref 10 is hidden, even though there is no city name nearby. However, zooming in shows there is an information post POI next to the junction, which I presume gets priority (even when it is not shown at the current zoom level). See https://www.openstreetmap.org/node/46586460 and https://www.openstreetmap.org/node/46586460, or https://www.openstreetmap.org/node/44244889 (which has a picnic table nearby and does not even show up at larger zoom, when the picnic table is further away, see [this screenshot](https://user-images.githubusercontent.com/194491/44055987-32a6b302-9f47-11e8-8b69-1f9811ae895a.png))
 - Sometimes I do not know what the cause is, for example see https://www.openstreetmap.org/node/43356003 and [this screenshot](https://user-images.githubusercontent.com/194491/44055627-42ebee04-9f46-11e8-915e-910edac8f4d5.png), or https://www.openstreetmap.org/node/44155328

A related problem is that in some places, the routes themselves are not rendered, sometimes also hiding adjacent nodes. For example, see https://www.openstreetmap.org/way/7186275 which is part of route https://www.openstreetmap.org/relation/6035235 but this is not rendered [on this screenshot](https://user-images.githubusercontent.com/194491/44056346-41aa78f6-9f48-11e8-9f90-c6bbb2681d0c.png). Or https://www.openstreetmap.org/way/182589097 and https://www.openstreetmap.org/way/182589097 which are part of https://www.openstreetmap.org/relation/15682 but not rendered [on this screenshot](https://user-images.githubusercontent.com/194491/44056488-b47ec5b2-9f48-11e8-8d7b-0aafb8ba7c60.png). Or https://www.openstreetmap.org/node/36155317 and nearby routes which are not rendered 
[on this screenshot](https://user-images.githubusercontent.com/194491/44056655-268da2d6-9f49-11e8-8c49-edf6dcd09e2d.png).

I hope providing some detailed and specific examples will help to fix any specific issues and generally improve the rendering of routes. All of the examples linked above can be found on the "The Netherlands" map in OsmAnd, screenshots were made with OsmAnd 3.1.5, but I originally noticed these issues with 3.0.something.

Am I correct in assuming that all of the decisions about whether to (not) render a thing on the map is made in the `.render.xml` files and fixing these issues should be done there (except when there are bugs or missing features in the render engine, of course)? If so, I might have a stab at trying to debug this. Are there any tools available to assist in debugging rendering styles (e.g. to inspect the data and the attributes assigned by the rendering style, instead of just the rendering result)? I've read that OsmAndMapCreator can also do rendering and is recommended, but from a first try that seems to mostly give me a way to test a modified rendering style faster, not any additional tools?

**Comment by vshcherb** [comment]
OsmAndMapCreator - also has optons to render. Specify them as in rendering style via "= and , ". Also it is very very useful to use binaryInspector cmd utility to see the underlying data cause sometimes it doesn't match 1 to 1 with OSM (OsmAnd doesn't have any low-level relations support for example).
 
![image](https://user-images.githubusercontent.com/1042025/44112186-b7d7b4fa-a004-11e8-8508-7f68e0bbcd7b.png)

**Comment by dmpr0** [comment]
Already fixed in 3.6.

**Comment by matthijskooijman** [comment]
I've noticed that a cycle routes are indeed much improved, awesome.

I doublechecked all the problematic cases from my https://github.com/osmandapp/Osmand/issues/5686#issuecomment-412665824 and indeed most of them are fixed, but unfortunately not all of them.

Can this be reopened, or should I rather open a new issue?

In particular, the following problems still exist:
 - https://www.openstreetmap.org/node/43356003 is shown at medium zoomlevels ([screenshot]()) but not when zoomed further in ([screenshot]()) or out ([screenshot]()). In Topo map style, it is not shown at all regardless of zoomlevel ([screenshot]()).
 - https://www.openstreetmap.org/node/44244889 is not shown when zoomed out ([screenshot]()), even when other nearby nodes are shown at that zoom level.
 - https://www.openstreetmap.org/way/97677179 is not shown ...

Additionally, these issues have been fixed for the OsmAnd map style, but still seem to exist for the "Topo" map style (which I rather like for cycling, because of its higher contrast):
 - https://www.openstreetmap.org/node/43319582 is not rendered [in this screenshot](). With OsmAnd style I originally this happened because the node is also `traffic_calming=table`, but it seems that Topo-style never renders those, so I'm not sure if that's still the cause.
 - https://www.openstreetmap.org/node/44244889 is not rendered [in this screenshot](). There is a picnic table very nearby, which might be the cause (though it happens even when the picnic table is not rendered at a particular zoom level).

https://www.openstreetmap.org/node/46586460 and https://www.openstreetmap.org/node/46586460, or https://www.openstreetmap.org/node/44244889 (which has a picnic table nearby and does not even show up at larger zoom, when the picnic table is further away, see this screenshot)
Sometimes I do not know what the cause is, for example see https://www.openstreetmap.org/node/43356003 and this screenshot, or https://www.openstreetmap.org/node/44155328

**Comment by matthijskooijman** [comment]
I've noticed that a cycle routes are indeed much improved, awesome.

I doublechecked all the problematic cases from my https://github.com/osmandapp/Osmand/issues/5686#issuecomment-412665824 and indeed most of them are fixed, but unfortunately not all of them. Also, some of them seem to be more pronounced in the Topo map style (which I rather like for cycling, because of its higher contrast), but also happen in some cases in the default OsmAnd style.

Can this be reopened, or should I rather open a new issue?

In particular, the following problems still exist:
 - https://www.openstreetmap.org/node/43356003 is shown at medium zoomlevels ([screenshot](https://user-images.githubusercontent.com/194491/86819407-e4cd5000-c087-11ea-9f17-271d4b680036.png)) but not when zoomed further in ([screenshot](https://user-images.githubusercontent.com/194491/86819410-e565e680-c087-11ea-80c8-7591b2581434.png)) or out ([screenshot](https://user-images.githubusercontent.com/194491/86819405-e434b980-c087-11ea-8220-7bf449dc8cd9.png)). In Topo map style, it is not shown at all regardless of zoomlevel ([screenshot](https://user-images.githubusercontent.com/194491/86819403-e39c2300-c087-11ea-9cb7-98bb33ead15b.png)).
 - https://www.openstreetmap.org/node/44244889 is not shown when zoomed out ([screenshot](https://user-images.githubusercontent.com/194491/86819399-e26af600-c087-11ea-8003-7a32b51c00ec.png)), even when other nearby nodes are shown at that zoom level. In Topo map style, it is not shown at all regardless of zoomlevel ([screenshot](https://user-images.githubusercontent.com/194491/86819400-e3038c80-c087-11ea-864b-b876a03e0075.png)). There is a picnic table very nearby, which I originally suspected to be the cause (though it happens even when the picnic table is not rendered at a particular zoom level).
 - https://www.openstreetmap.org/way/97677179 is not shown ([screenshot](https://user-images.githubusercontent.com/194491/86819399-e26af600-c087-11ea-8003-7a32b51c00ec.png)) when zoomed out somewhat (it is shown when zooming in more closely). The same happens with the Topo style ([screenshot](https://user-images.githubusercontent.com/194491/86825204-61176180-c08f-11ea-8e0d-f1a3a77f3051.png)). This is a new problem, not from the original comment, that I noticed because it was nearby the previous point.
 - https://www.openstreetmap.org/node/43319582 is not rendered when zoomed out ([screenshot](https://user-images.githubusercontent.com/194491/86824112-00d3f000-c08e-11ea-97d8-dd6bd00fcfca.png)) even when other nearby nodes are shown at that zoomlevel. WIth Topo map style, it is not shown at all regardless of zoomlevel ([screenshot](https://user-images.githubusercontent.com/194491/86819396-e1d25f80-c087-11ea-9d97-65217c179c1a.png)). I originally suspected this happened because the node is also `traffic_calming=table`, but the problem happens when the table is not rendered (Topo-style never seems to render those), so I'm not sure if that's actually the cause.


So there might actually be two separate issues:
 - For the OsmAnd style, some things are not shown depending on zoom level, but they can always be shown by (usually) zooming in or (sometimes) zooming out, so these are minor issue (though they still hurt usability when using OsmAnd for bike navigation). I suspect that the fixes made for this issue have helped to give routes more priority, but maybe there might still be priority conflicts in some cases.
 - For the Topo style, these issues occur regardless of zoom level, more like the OsmAnd style originally, so maybe the fixes made for this issue were made only to the OsmAnd style and not for Topo yet? These issues are also more significantly hurting usability.
