### ISSUE TITLE
Cycle routes are not taken into account in navigation

### ISSUE THREAD

**Issue by alyonapinchuk** [osmandapp/Osmand#6022]
Start Point 48.9171475, 11.2014703 
End Point 48.893168, 11.1850143.
There are much better ways for a bicycle but OsmAnd does not consider them as an option regardless of the chosen Driving Style.
![image](https://user-images.githubusercontent.com/40493090/45304643-31de4a80-b521-11e8-8dd3-979010d0d582.png)

**Comment by pebogufi** [comment]
Be shure **not** to check "avoid unpaved roads" (de:unbefestigte Wege meiden).

**Comment by quax2712** [comment]
this only happens when routing options are "use safe mode" but fastes or balanced rout on cycle way

**Comment by Posteinwurf** [comment]
just checked this:

At least in 'prefer byways'  mode, the bicycle route should be taken (my start point was church in preith).

**Comment by pebogufi** [comment]
I make a cycle tour along the river Loire in France using Euro Velo 6 (EV6), which is good fixed in OSM. But it is not working (in none setting) to follow the cycle route. I have to make a lot of waypoints to force the route to follow EV6. This is very annoying.

**Comment by Posteinwurf** [comment]
that's a great tour, have done it some time ago.

Osmand will not always follow cycle routes, because some if them are not the best alternative. I could give some examples (have done very extensive testing to optimize the routing values, evennin France). 

Having said that: thete is always room for improvement. So if you detect a suggestion that Osmand makes and that is worse than the cycle route: please post a screenshot and I will try to improve the routing based on this. please use elevation data with the flattest setting, and "prefer byways"

All the best

Malte

ps another solution could be a switch for strong prefernce of cycle routes.


--
Diese Nachricht wurde von meinem Mobiltelefon gesendet.Am 12.08.2019, 12:23, pebogufi <notifications@github.com> schrieb:
I make a cycle tour along the river Loire in France using Euro Velo 6 (EV6), which is good fixed in OSM. But it is not working (in none setting) to follow the cycle route. I have to make a lot of waypoints to force the route to follow EV6. This is very annoying.

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/osmandapp/Osmand/issues/6022?email_source=notifications\u0026email_token=AEEWM4ETTCUAZWQM5LMVMH3QEE23NA5CNFSM4FUGGTQKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD4CDXHQ#issuecomment-520371102",
"url": "https://github.com/osmandapp/Osmand/issues/6022?email_source=notifications\u0026email_token=AEEWM4ETTCUAZWQM5LMVMH3QEE23NA5CNFSM4FUGGTQKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD4CDXHQ#issuecomment-520371102",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by Logicuth** [comment]
It was the v.3.2.7 that did not take the cycle way.
With the v3.4.6 now, Osmand takes the cycle way over the village "Wimpasing".

But now there is another issue, in "navigation settings" -> "navigation service" it is not possible to choose "Brouter" as alternative routing engine.
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/43710795/64474995-c4d5b300-d17c-11e9-94ef-64ae67228755.png"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by moz0817** [comment]
Although this post is old, the problem still exists in the current version. It feels like the app is **avoiding** bike paths!

In the first example (DE: Würzburg -> Eibelstadt), a parallel bike path is visible, but it is ignored.
<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/43210db9-8166-4c80-b5f0-4a8408c32445"  width="500" height="auto"/> </td>
  </tr>
</table>


In the other case (FR: Ansouis -> Cocuron), it's even more blatant: You can see the intermediate destination on the bike path. Nevertheless, the route reverses and uses the road!

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/7ee880ee-3b5e-4c34-ba59-84533db9fa4d"  width="300" height="auto"/> </td>
  </tr>
</table>

Changing the driving style settings, elevation data, or avoiding roads couldn't persuade osmand to use the bike path.

That's a real shame, because otherwise I'm totally thrilled with it and have been using the app as a paying subscriber for many years.

**Comment by Posteinwurf** [comment]
Thank you for testing! That is really helpful, because I think you found an error. Surprisingly, the error is not in the routing, but seems to be in the "settings" section. This is what I found:

1) When I reproduce your destinations, I get different routing results. Osmand actually takes the bike paths that you suggested (both in Southern France and along the Main river). 

2) So what probably happened, is the following: When you are using bicycyle routing, your Osmand might be switched to car mode in the background (so it is not visible that you are in not in bicycle mode). So could you check if that is the case with your app? If you go to "navigation settings - bicycle" then "car" might be chosen as the navigation mode for "bicycle" (see my screenshot). 

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/1409e1be-8546-47b4-9a0a-f278812f74c5"  width="300" height="auto"/> </th>
  </tr>
</table>  

3)  @vshcherb I think this is a bug that needs to be corrected: It is possible to set "bicycle navigation" to "car mode" in the background. Once this has (accidentally) happened, it will use car mode when a user chooses "bicycle navigation" AND it will still look like you are using "bicycle navigation": the app will still show the bicycle mode options, so you can choose "prefer byways" (for example), but to no effect. - Osmand will just use car mode in the background. (I hope I am not mistaken, but this is what I see here).

All the best

Malte
