### ISSUE TITLE
Incorrect search results

### ISSUE THREAD

**Issue by alyonapinchuk** [osmandapp/Osmand#6821]
When searching for categories, they are shown multiple times, while only one of them works. 
![image](https://user-images.githubusercontent.com/40493090/56084567-77f3e780-5e3d-11e9-8d25-8080ae775521.png)

**Comment by vshcherb** [comment]
It is definitely not correct cause it doesn't show distance to the object, so it looks like multiple same categories

**Comment by vshcherb** [comment]
Fixed for 3.3.7

**Comment by rrooggiieerr** [comment]
Hi! This error was reported by me trough FB. Good to see this one is picked up. Next time I'll report errors directly here on GitHub.

**Comment by rrooggiieerr** [comment]
Hi! The issue is still present in 3.5.8

**Comment by rrooggiieerr** [comment]
Hi! I still face the issue in 3.7.4. Interestingly it does not seem to happen when my phone has restarted, but is introduced gradually when I'm using Osmand over a longer time. First showing a second duplicate, some time later a third duplicate. I have seen up to 4 duplicates of the category
