### ISSUE TITLE
Hiking mode renders horse/mtb OSMC symbols despite explicitly disabled

### ISSUE THREAD

**Issue by mahdi1234** [osmandapp/Osmand#8540]
Osmand 3.5.5~ with "Colouring according to OSMC" and Cycling/MTB/Horse routes disabled.

Switch to "hiking" profile and disable MTB/horse setting with only "Colouring according to OSMC"

![Screenshot_2020-02-22_21-14-02](https://user-images.githubusercontent.com/1097047/75098675-1221d180-55b1-11ea-9676-876486445cd2.png)

https://www.openstreetmap.org/way/94446603#map=19/49.13638/16.23797 has couple hiking relations

https://www.openstreetmap.org/relation/1425024
https://www.openstreetmap.org/relation/223319

but app renders bicycle route

https://www.openstreetmap.org/relation/1425026

![Screenshot_2020-02-22_21-13-11](https://user-images.githubusercontent.com/1097047/75098672-0c2bf080-55b1-11ea-9592-04d38e10a03a.png)

https://www.openstreetmap.org/way/171722722 has couple of hiking relations

https://www.openstreetmap.org/relation/1425024
https://www.openstreetmap.org/relation/967832

but app renders horse one

https://www.openstreetmap.org/relation/1996019

![Screenshot_2020-02-22_21-13-33](https://user-images.githubusercontent.com/1097047/75098698-4dbc9b80-55b1-11ea-800e-72297b2f682a.png)

**Comment by xmd5a2** [comment]
Fixed. Please test.

**Comment by mahdi1234** [comment]
@xmd5a2 tried with https://download.osmand.net/latest-night-build/OsmAnd-default.apk + Czech April maps, first problem with rendering bike relation https://www.openstreetmap.org/relation/1425026 still persists.

Second problem with horse route is fixed.

**Comment by aceman444** [comment]
Hi, so what is the fix? The proposed solution didn't work according to the tester and no further implementation was submitted, but the issue is suddenly closed?

**Comment by mahdi1234** [comment]
Hi @aceman444 as originator of the problem it works fine for me now in released 3.7.2 so either some submit is missing or it required maps regeneration, I guess.
